var path = require('path');

module.exports = {
  locales: [
    { id: 1, code: 'en', name: 'English' },
    { id: 2, code: 'cn', name: '简体中文' },
    { id: 3, code: 'th', name: 'ไทย' },
    { id: 4, code: 'id', name: 'Indonesia' },
    { id: 5, code: 'ko', name: '한국어' },
    { id: 6, code: 'de', name: 'Deutsch' },
    { id: 7, code: 'fr', name: 'Français' },
    { id: 8, code: 'pt', name: 'Português' },
    { id: 9, code: 'es', name: 'Español' },
    { id: 10, code: 'vn', name: 'Tiếng Việt' },
    { id: 11, code: 'ru', name: 'Русский' },
    { id: 12, code: 'ar', name: 'عربى' },
    { id: 13, code: 'cz', name: 'Česky' },
    { id: 14, code: 'my', name: 'Melayu' },
    { id: 15, code: 'it', name: 'Italiano' },
    { id: 16, code: 'bg', name: 'Български' },
    { id: 17, code: 'hr', name: 'Hrvatski' },
    { id: 18, code: 'tw', name: '繁體中文' }
  ],
  locales_per_regulator: [
    { regulator: 'asic', locales: [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18] },
    { regulator: 'cysec', locales: [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18] },
    { regulator: 'fsa', locales: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18] },
    { regulator: 'scb', locales: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18] },
    { regulator: 'fca', locales: [1] },
    { regulator: 'fsc', locales: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18] },
    { regulator: 'cima', locales: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18] }
  ],
  approve_pending_max_timeout: 1000,
  websocket: {
    ping: {
        frontend_period: 2000,
        server_max_wait: 4000
    }
  },
  icm_internal_ips: [
    '110.175.225.134', // AU
    '122.202.11.10', // AU
    '122.202.11.7', // AU
    '65.2.155.10', // IN
    '3.109.168.172', // IN
    '3.108.14.176', // IN - QA
    '93.109.254.146', // CY Main
    '46.28.176.161', // CY Secondary
    '46.28.176.162', // CY Secondary Backup
    '3.8.49.43' // Automation Testing
  ],
  ZENDESK_API_TOKEN: "9sZ47UQGQSolySu87Ucxlw9Q79vvphplonznjCU2",
  ZENDESK_OAUTH_TOKEN: "41a376c7affab0fa6569939f3efd5f9ae5c7932f2088e3397a0adbe5e4771875",
  JWT_SECRET: "kS2kVAkOVh6_i4Rf3CU376c7af_fab0fad1VX",
  IMPORT_REDIS_JSON_FROM_GITHUB_TOKEN: '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',
  //redis_host: process.env.REDIS_DB_HOST || "localhost",
  redis_host: process.env.REDIS_DB_HOST || "dev-registration-redis.icmarkets.com",
  redis_port: process.env.REDIS_DB_PORT || "6379",
  monitoring_url: "http://monitoring.icmarkets.com/write?json=",
  auth_service_url: "https://auth.icmarkets.com/v2",
  global_client_area_url: "https://secure.icmarkets.com",
  chinese_client_area_url: "https://secure.icmarkets-zhv.com",
  italian_client_area_url: "https://secure.icmarkets.eu",
  eu_client_area_url: "https://secure.icmarkets.eu",
  uk_client_area_url: "https://secure.icmarketsuk.com",
  client_area_global_url: "https://secure.icmarkets.com",
  client_area_bs_url: "https://secure.icmarkets.com",
  client_area_ru_url: "https://secure.icmarkets-ru.com",
  reg_service_1_url: "/regapi/",
  reg_service_2_url: "/regapi/",
  // reg_service_endpoint: process.env.REG_HOST_1 || "http://prod-registration1.icmarkets.com",
  // reg_service_endpoint: process.env.REG_HOST_1 || "http://staging-registration.icmarkets.com",
  reg_service_endpoint: process.env.REG_HOST_1 || "http://dev-reg-dev.internal.icmarkets.com",
  // reg_service_endpoint: "http://localhost:9001/",
  cysec_website_url: "https://www.icmarkets.eu",
  cysec_website_name: "www.icmarkets.eu",
  port: '8080',
  default_prefix: 'global',
  default_regulator: 'fsa',
  regulators: ['asic', 'cysec', 'fca', 'fsa', 'scb', 'fsc', 'cima'],
  regulators_cn: ['fsa'],
  regulators_prod: {
    asic: ['icmarkets.com'],
    cysec: ['icmarkets.eu'],
    fca: ['icmarketsuk.com'],
    fsa: ['icmarkets.com', 'icmarkets.ru'],
    scb: ['icmarkets.bs'],
    fsc: ['icmarkets.mu'],
    cima: ['icmarkets.ky']
  },
  regulators_prefixes: {
    asic: 'au',
    cysec: 'eu',
    fca: 'uk',
    fsa: 'global',
    scb: 'intl',
    fsc: 'mu',
    cima: 'ky'
  },
  regulator_by_prefix: {
    au: 'asic',
    bs: 'scb',
    eu: 'cysec',
    global: 'fsa',
    intl: 'scb',
    sc: 'fsa',
    uk: 'fca',
    mu: 'fsc',
    ky: 'cima'
  },
  legacy_prefixes: ['sc', 'bs', 'mu', 'ky'],
  branch_wcf_ids: {
    asic: '1',
    cysec: '2',
    fsa: '3',
    scb: '4',
    fca: '6',
    fsc: '8',
    cima: '9'
  },
  regulator_prefix_by_branch_wcf_id: {
    '1': 'au',
    '2': 'eu',
    '3': 'global',
    '4': 'intl',
    '6': 'uk',
    '8': 'mu',
    '9': 'ky'
  },
  bundler_tasks: [
    {
      name: 'forexCalculatorsBundle',
      path: path.join(__dirname, 'node_modules/forex-calculators/index.js')
    }
  ],
  apac_countries: [
    'my',
    'th',
    'vn',
    'in',
    'id',
    'cn',
    'hk',
    'mo',
    'tw'
  ],
  routes: {
    "it": {
      'company/about-icmarkets': 'informazioni/about-icmarkets',
      'company/aml-policy': 'informazioni/procedura-antiriciclaggio',
      'company/careers': 'informazioni/carriera',
      'company/contact-us': 'informazioni/contattaci',
      'company/dispute-resolution': 'informazioni/risoluzione-dispute',
      'company/legal-documents': 'informazioni/documentazione-legale',
      'company/monthly-volume-report': 'informazioni/report-dei-volumi',
      'company/press-releases': 'informazioni/pr',
      'company/privacy-policy': 'informazioni/privacy-policy',
      'company/regulation': 'informazioni/regolamentazioni',
      "company/why-icmarkets": 'informazioni/scegli-icmarkets',
      'education/advantages-of-cfds': 'educazione/vantaggi-dei-cfds',
      'education/advantages-of-forex': 'educazione/vantaggi-dei-forex',
      'education/education-overview': 'educazione/inizia-qui',
      'education/getting-started-lessons': 'educazione/informazioni-di-base',
      'education/trading-knowledge': 'educazione/forex-trading',
      'education/video-tutorials': 'educazione/video-tutorials',
      'education/web-tv': 'educazione/web-tv',
      'forex-trading-platform/myfxbook-autotrade': 'piattaforma-forex-trading/myfxook-autotrade',
      'forex-trading-platform-ctrader/calgo': 'piattaforma-forex-trading-ctrader/calgo',
      'forex-trading-platform-ctrader/ctrader-android': 'piattaforma-forex-trading-ctrader/android',
      'forex-trading-platform-ctrader/ctrader-iphone': 'piattaforma-forex-trading-ctrader/iphone',
      'forex-trading-platform-ctrader/ctrader-web': 'piattaforma-forex-trading-ctrader/web',
      'forex-trading-platform-ctrader/ctrader-windows': 'piattaforma-forex-trading-ctrader/windows',
      'forex-trading-platform-ctrader/smart-stop-out': 'piattaforma-forex-trading-ctrader/stop-out-intelligente',
      'forex-trading-platform-metatrader/android': 'piattaforma-forex-trading-metatrader/android',
      'forex-trading-platform-metatrader/apple-mac': 'piattaforma-forex-trading-metatrader/mac',
      'forex-trading-platform-metatrader/iphone': 'piattaforma-forex-trading-metatrader/iphone',
      'forex-trading-platform-metatrader/metatrader-4': 'piattaforma-forex-trading-metatrader/mt4',
      'forex-trading-platform-metatrader/metatrader-5': 'piattaforma-forex-trading-metatrader/mt5',
      'forex-trading-platform-metatrader/web-trader': 'piattaforma-forex-trading-metatrader/web-trader',
      'forex-trading-tools/api-trading': 'strumenti-forex/api',
      'forex-trading-tools/mam-pamm': 'strumenti-forex/copy-trading',
      'forex-trading-tools/mt4-advanced-tools': 'strumenti-forex/tools-mt4',
      'forex-trading-tools/mt4-advanced-trading-tools': 'strumenti-forex/mt4-strumenti-avanzati',
      'forex-trading-tools/trading-servers': 'strumenti-forex/server-per-il-trading',
      'forex-trading-tools/virtual-private-server': 'strumenti-forex/vps',
      'help-resources/economic-calendar': 'risorse/calendario-economico',
      'help-resources/forex-calculators': 'risorse/calcolatore-pips',
      'help-resources/forex-glossary': 'risorse/glossario-forex',
      'help-resources/help-centre': 'risorse/centro-supporto',
      'help-resources/market-analysis-blog': 'risorse/analisi-mercato',
      'introduction/forex-trading': 'forex/trading',
      'introduction/true-ecn': 'forex/true-ecn',
      'legal/client-suitability-test': 'legale/test-di-idoneita',
      "open-trading-account/live": "conto-trading/live",
      "open-trading-account/demo": "conto-trading/demo",
      'partnerships/affiliate-program': 'partnerships/programma-di-affiliazione',
      'partnerships/partnerships-overview': 'partnerships/overview',
      'partnerships/regional-partnerships': 'partnerships/partnership-regionali',
      'trading-accounts/funding-netellervip': 'tipologie-account/deposito-netellervip',
      'trading-accounts/funding': 'tipologie-account/metodi-deposito',
      'trading-accounts/islamic-account': 'tipologie-account/halal',
      'trading-accounts/overview': 'tipologie-account/overview',
      'trading-accounts/standard-account': 'tipologie-account/standard',
      'trading-accounts/true-ecn-account': 'tipologie-account/ecn',
      'trading-accounts/true-ecn-ct-account': 'tipologie-account/conto-ecn-ct',
      'trading-accounts/withdrawal': 'tipologie-account/prelievi',
      'trading-markets/commodities': 'trading-markets/materie-prime',
      'trading-markets/digitalcurrency': 'trading-markets/digitalmonete',
      'trading-markets/indices': 'trading-markets/indici',
      'trading-markets/range-of-markets': 'trading-markets/mercati-disponibili',
      'trading-markets/stocks': 'trading-markets/stock',
      'trading-pricing/spreads': "costi-di-trading/spreads",
      'trading-pricing/swap-rate': "costi-di-trading/swaps-rate",
      'trading-pricing/trading-conditions': "costi-di-trading/condizioni",
      'trading-pricing/trading-hours': 'costi-di-trading/orari-di-trading',
    },
    "es": {
      'company/about-icmarkets': 'informacion/acerca-de-icmarkets',
      'company/aml-policy': 'informacion/politica-aml',
      'company/careers': 'informacion/trabaje-con-nosotros',
      'company/contact-us': 'informacion/contactenos',
      'company/dispute-resolution': 'informacion/solucion-de-disputas',
      'company/legal-documents': 'informacion/documentos-legales',
      'company/monthly-volume-report': 'informacion/reporte-mensual-de-volumen',
      'company/press-releases': 'informacion/publicaciones',
      'company/privacy-policy': 'informacion/politica-de-privacidad',
      'company/regulation': 'informacion/regulacion',
      "company/why-icmarkets": 'informacion/por-que-icmarkets',
      'education/advantages-of-cfds': 'educazione/ventajas-de-los-cfds',
      'education/advantages-of-forex': 'educazione/ventajas-del-forex',
      'education/education-overview': 'educazione/resumen',
      'education/getting-started-lessons': 'educazione/lecciones-para-empezar',
      'education/trading-knowledge': 'educazione/conociemiento-del-trading',
      'education/video-tutorials': 'educazione/video-tutoriales',
      'education/web-tv': 'educazione/web-tv',
      'forex-trading-platform/myfxbook-autotrade': 'forex-trading-platform/myfxook-autotrade',
      'forex-trading-platform-ctrader/calgo': 'plataforma-de-trading-ctrader/calgo',
      'forex-trading-platform-ctrader/ctrader-android': 'plataforma-de-trading-ctrader/ctrader-android',
      'forex-trading-platform-ctrader/ctrader-iphone': 'plataforma-de-trading-ctrader/ctrader-iphone',
      'forex-trading-platform-ctrader/ctrader-web': 'plataforma-de-trading-ctrader/ctrader-web',
      'forex-trading-platform-ctrader/ctrader-windows': 'plataforma-de-trading-ctrader/ctrader-windows',
      'forex-trading-platform-ctrader/smart-stop-out': 'plataforma-de-trading-ctrader/stop-out-inteligente',
      'forex-trading-platform-metatrader/android': 'plataforma-de-trading-metatrader/android',
      'forex-trading-platform-metatrader/apple-mac': 'plataforma-de-trading-metatrader/apple-mac',
      'forex-trading-platform-metatrader/iphone': 'plataforma-de-trading-metatrader/iphone',
      'forex-trading-platform-metatrader/metatrader-4': 'plataforma-de-trading-metatrader/metatrader-4',
      'forex-trading-platform-metatrader/metatrader-5': 'plataforma-de-trading-metatrader/metatrader-5',
      'forex-trading-platform-metatrader/web-trader': 'plataforma-de-trading-metatrader/web-trader',
      'forex-trading-tools/api-trading': 'herramientas-forex-trading/api',
      'forex-trading-tools/mt4-advanced-tools': 'herramientas-forex-trading/herramientas-avanzadas-mt4',
      'forex-trading-tools/mt4-advanced-trading-tools': 'herramientas-forex-trading/herramientas-avanzadas-de-trading-mt4',
      'forex-trading-tools/trading-servers': 'herramientas-forex-trading/servidores-disponibles-para-trading',
      'forex-trading-tools/virtual-private-server': 'herramientas-forex-trading/vps',
      'help-resources/economic-calendar': 'recursos-ayuda/calendario-economico',
      'help-resources/forex-calculators': 'recursos-ayuda/calculadora-forex',
      'help-resources/forex-glossary': 'recursos-ayuda/glosario-forex',
      'help-resources/help-centre': 'recursos-ayuda/centro-de-ayuda',
      'help-resources/market-analysis-blog': 'recursos-ayuda/blog-de-analisis-del-mercado',
      'introduction/forex-trading': 'introduccion/forex-trading',
      'introduction/true-ecn': 'introduccion/true-ecn',
      'legal/client-suitability-test': 'legal/test-de-idoneidad',
      "open-trading-account/live": "abrir-cuenta-trading/live",
      "open-trading-account/demo": "abrir-cuenta-trading/demo",
      'partnerships/affiliate-program': 'partnerships/programa-de-afiliados',
      'partnerships/money-managers': 'partnerships/administradores-de-diner',
      'partnerships/partnerships-overview': 'partnerships/partnerships-resumen',
      'partnerships/refer-a-friend': 'partnerships/refiera-un-amigo',
      'trading-accounts/funding-netellervip': 'tipo-de-cuenta/deposito-netellervip',
      'trading-accounts/funding': 'tipo-de-cuenta/metodos-de-deposito',
      'trading-accounts/islamic-account': 'tipo-de-cuenta/cuenta-islamica',
      'trading-accounts/overview': 'tipo-de-cuenta/resumen',
      'trading-accounts/standard-account': 'tipo-de-cuenta/cuenta-standard',
      'trading-accounts/true-ecn-account': 'tipo-de-cuenta/cuenta-true-ecn',
      'trading-accounts/true-ecn-ct-account': 'tipo-de-cuenta/cuenta-true-ecn-ct',
      'trading-accounts/withdrawal': 'tipo-de-cuenta/retiro',
      'trading-markets/bonds': 'trading-markets/bonos',
      'trading-markets/digitalcurrency': 'trading-markets/digitalmonedas',
      'trading-markets/futures': 'trading-markets/futuros',
      'trading-markets/range-of-markets': 'trading-markets/mercado-disponible',
      'trading-markets/stocks': 'trading-markets/stocks-acciones',
      'trading-pricing/spreads': 'costos-de-trading/spreads',
      'trading-pricing/swap-rate': 'costos-de-trading/cobros-de-swap',
      'trading-pricing/trading-conditions': 'costos-de-trading/condiciones-de-trading',
      'trading-pricing/trading-hours': 'costos-de-trading/horario-de-trading'
    }
  },
  seo_redirects: {
    "index.html": "",
    "trading-accounts/true-ecn-ct-account": "trading-accounts/ctrader-raw",
    "trading-accounts/true-ecn-account": "trading-accounts/raw-spread-account",
    "trading-accounts/ctrader-ecn": "trading-accounts/ctrader-raw",
    "introduction/true-ecn": "trading-pricing/spreads",
    "en": "",
    "forex-trading": "trading-markets/forex",
    "open-new-live-account": "open-trading-account/live",
    "open-new-demo-account": "open-trading-account/demo",
    "forex-trading/open-a-live-account": "open-trading-account/live",
    "forex-trading/open-a-demo-account": "open-trading-account/demo",
    "forex-trading/trading-account-types": "trading-accounts/overview",
    "forex-trading/trading-account-types/standard-account": "trading-accounts/standard-account",
    "forex-trading/trading-account-types/true-ecn-account": "trading-accounts/raw-spread-account",
    "forex-trading/trading-account-types/ctrader-ecn": "trading-accounts/ctrader-raw",
    "forex-trading/trading-account-types/islamic-accounts": "trading-accounts/islamic-account",
    "forex-trading/forex": "trading-markets/forex",
    "forex-trading/indices": "trading-markets/indices",
    "forex-trading/futures": "trading-markets/futures",
    "forex-trading/commodities-trading": "trading-markets/commodities",
    "forex-trading/virtual-private-server": "forex-trading-tools/virtual-private-server",
    "forex-trading/trading-conditions": "trading-pricing/trading-conditions",
    "forex-trading/trading-conditions/spreads": "trading-pricing/spreads",
    "trading-hours": "trading-pricing/trading-hours",
    "forex-trading/trading-conditions/swap-rates": "trading-pricing/swap-rates",
    "forex-trading/trading-conditions/currency-pairs": "trading-markets/forex",
    "forex-trading-platform": "forex-trading-platform-metatrader/metatrader-5",
    "forex-trading-platform/meta-trader-4": "forex-trading-platform-metatrader/metatrader-4",
    "forex-trading-platform/meta-trader-4/iphone": "forex-trading-platform-metatrader/iphone",
    "forex-trading-platform/meta-trader-4/android": "forex-trading-platform-metatrader/android",
    "forex-trading-platform/meta-trader-4/apple-mac": "forex-trading-platform-metatrader/apple-mac",
    "forex-trading-platform/ctrader": "forex-trading-platform-ctrader/ctrader-windows",
    "trading-platform/ctrader/ctrader-web": "forex-trading-platform-ctrader/ctrader-web",
    "forex-trading-platform/ctrader/ctrader-mobile-web": "forex-trading-platform-ctrader/ctrader-iphone",
    "forex-trading-platform/ctrader/ctrader-algo": "forex-trading-platform-ctrader/calgo",
    "advanced-trading-tools": "forex-trading-tools/mt4-advanced-trading-tools",
    "trading-platform/meta-trader-5": "forex-trading-platform-metatrader/metatrader-5",
    "forex-trading-platform/mam-pamm": "forex-trading-tools/mam-pamm",
    "forex-trading-platform/fix-api": "",
    "forex-trading-platform/trading-servers": "forex-trading-tools/trading-servers",
    "partnerships": "partnerships/partnerships-overview",
    "partnerships/money-manager": "partnerships/money-managers",
    "partnerships/white-label": "partnerships/white-label-partnerships",
    "education": "education/education-overview",
    "education/getting-started": "",
    "technical-analysis-101-a-beginners-guide-to-technical-analysis": "",
    "fundamental-analysis-101-a-beginners-guide-to-fundamental-analysis": "",
    "risk-management-101": "",
    "trading-psychology-101": "",
    "education/forex-news-and-calendar": "",
    "about-us": "company/about-icmarkets",
    "about-us/about-ic-markets": "company/about-icmarkets",
    "about-us/why-choose-ic-markets": "company/why-icmarkets",
    "about-us/regulation-2": "company/regulation",
    "about-us/careers": "company/careers",
    "about-us/legal-documents": "company/legal-documents",
    "client-area": "",
    "client-area/funding": "trading-accounts/funding",
    "client-area/funding/4": "trading-accounts/funding",
    "client-area/withdrawals": "trading-accounts/withdrawal",
    "client-area/downloads": "forex-trading-platform-metatrader/metatrader-4",
    "client-area/support": "help-resources/help-centre",
    "client-area/faq": "help-resources/help-centre",
    "client-area/forex-glossary": "help-resources/help-centre",
    "client-area/contact-us": "company/contact-us",
    "forex-trading/stocks": "trading-markets/stocks",
    "forex-trading/bond-futures": "trading-markets/bonds",
    "forex-trading/cryptocurrency": "trading-markets/digitalcurrency",
    "bitcoin-trading": "trading-markets/digitalcurrency",
    "trading-markets/cryptocurrency": "trading-markets/digitalcurrency",
    "forex-trading-platform/metatrader-5": "forex-trading-platform-metatrader/metatrader-5",
    "forex-trading-platform/ctrader/ctrader-iphone": "forex-trading-platform-ctrader/ctrader-iphone",
    "forex-trading-platform/ctrader/ctrader-android": "forex-trading-platform-ctrader/ctrader-android",
    "monthly-volume-report": "company/monthly-volume-report",
    "aml-policy": "company/aml-policy",
    "advanced-trading-tools/forex-calculators": "help-resources/forex-calculators",
    "forex-trading-platform/zulutrade": "zulutrade",
    "education/spreads-and-liquidity": "trading-pricing/spreads",
    "client-area/funding/netellervip": "trading-accounts/funding",
    "true-ecn": "trading-accounts/raw-spread-account",
    "forex-trading-platform/ctrader/ctrader-web": "forex-trading-platform-ctrader/ctrader-web",
    "client-area/credit-card": "trading-accounts/funding",
    "client-area/bank-transfer": "trading-accounts/funding",
    "forex-trading/indices/feed": "trading-markets/indices",
    "forex-trading-platform/meta-trader/apple-mac": "forex-trading-platform-metatrader/apple-mac",
    "trading/markets/bonds": "trading-markets/bonds",
    "partnerships/partnerships/money-managers": "partnerships/money-managers",
    "partnerships/refer/affiliate-program": "partnerships/affiliate-program",
    "forex-trading-platform/trading-tools/api-trading": "",
    "forex-trading-platform/trading-tools/mt4-advanced-trading-tools": "forex-trading-tools/mt4-advanced-trading-tools",
    "forex-trading-tools/api-trading": "",
    "advanced-trading-tools-index": "forex-trading-tools/mt4-advanced-tools",
    "partnerships/refer-a-friend": "",
    "company/monthly-volume-report": "",
    "help-resources/fsa-migration-help": "",
    "company/news": "blog/category/company-news",
    "company/press-releases": "blog/category/press-releases",
    "education/getting-started-lessons": "blog/getting-started",
    "education/trading-knowledge": "blog/category/forex-trading-101",
    "company/entities": "",
  },
  cysec_pages: [
    "",
    "open-trading-account/live",
    "open-trading-account/demo",
    "company/about-icmarkets",
    "company/regulation",
    "company/legal-documents",
    "trading-markets/range-of-markets",
    "trading-markets/forex",
    "trading-markets/commodities",
    "trading-markets/indices",
    "trading-markets/bonds",
    "trading-markets/stocks",
    "trading-markets/futures",
    "trading-accounts/overview",
    "trading-accounts/funding",
    "trading-accounts/withdrawal",
    "trading-accounts/raw-spread-account",
    "help-resources/help-centre",
    "company/contact-us",
    "company/careers",
    "forex-trading-platform-metatrader/metatrader-4",
    "forex-trading-platform-metatrader/metatrader-5",
    "forex-trading-platform-ctrader/ctrader-windows",
    "forex-trading-platform-ctrader/ctrader-web",
    "forex-trading-platform-ctrader/ctrader-iphone",
    "forex-trading-platform-ctrader/ctrader-android",
    "forex-trading-platform-ctrader/calgo",
    "trading-pricing/swap-rates",
    "trading-pricing/spreads",
    "trading-pricing/trading-hours",
    "education/education-overview",
    "education/advantages-of-forex",
    "education/advantages-of-cfds",
    "education/video-tutorials",
    "education/web-tv",
    "help-resources/forex-calculators",
    "help-resources/economic-calendar",
    "help-resources/forex-glossary",
    "forex-trading-tools/virtual-private-server",
    "introduction/icmarkets-mobile-app"
  ],
  cysec_pages_only: [
  ],
  per_branch_redirects: {
    "1": {
      "company/insurance": "404",
      "partnerships/partnerships-overview": "partnerships/affiliate-program",
      "partnerships/money-managers": "partnerships/affiliate-program",
      "partnerships/white-label-partnerships": "partnerships/affiliate-program",
      "partnerships/regional-partnerships": "partnerships/affiliate-program",
      "partnerships/introducing-broker": "partnerships/affiliate-program",
      "forex-trading-tools/mam-pamm": "404",
      "forex-trading-platform-ctrader/ctrader-copy-trading": "404"
    },
    "2": {
      "company/insurance": "404",
      "partnerships/partnerships-overview": "404",
      "partnerships/money-managers": "404",
      "partnerships/white-label-partnerships": "404",
      "partnerships/regional-partnerships": "404",
      "partnerships/introducing-broker": "404",
      "trading-markets/cryptocurrency": "trading-markets/digitalcurrency",
      "forex-trading-platform-ctrader/ctrader-copy-trading": "404",
      "forex-trading-tools/mam-pamm": "404",
    },
    "3": {
      "company/privacy-policy": "404",
      "forex-trading-tools/mam-pamm": "404",
    },
    "4": {
      "company/insurance": "404",
      "xp-trader": "404",
      "company/privacy-policy": "company/legal-documents",
      "forex-trading-platform-ctrader/ctrader-copy-trading": "404",
      "forex-trading-tools/mam-pamm": "404",
    }
  },
  per_branch_redirects_to_outside: {
    "1": {
      "partnerships/partnerships-overview": "https://www.icmarketspartners.com/",
      "partnerships/money-managers": "https://www.icmarketspartners.com/",
      "partnerships/white-label-partnerships": "https://www.icmarketspartners.com/",
      "partnerships/regional-partnerships": "https://www.icmarketspartners.com/",
      "partnerships/introducing-broker": "https://www.icmarketspartners.com/",
      "partnerships/affiliate-program": "https://www.icmarketspartners.com/"
    },
    "2": {
      "partnerships/partnerships-overview": "https://www.icmarketspartners.com/",
      "partnerships/money-managers": "https://www.icmarketspartners.com/",
      "partnerships/white-label-partnerships": "https://www.icmarketspartners.com/",
      "partnerships/regional-partnerships": "https://www.icmarketspartners.com/",
      "partnerships/introducing-broker": "https://www.icmarketspartners.com/",
      "partnerships/affiliate-program": "https://www.icmarketspartners.com/"
    },
    "3": {
      "partnerships/partnerships-overview": "https://www.icmarketspartners.com/",
      "partnerships/money-managers": "https://www.icmarketspartners.com/",
      "partnerships/white-label-partnerships": "https://www.icmarketspartners.com/",
      "partnerships/regional-partnerships": "https://www.icmarketspartners.com/",
      "partnerships/introducing-broker": "https://www.icmarketspartners.com/",
      "partnerships/affiliate-program": "https://www.icmarketspartners.com/"
    },
    "4": {
      "partnerships/partnerships-overview": "https://www.icmarketspartners.com/",
      "partnerships/money-managers": "https://www.icmarketspartners.com/",
      "partnerships/white-label-partnerships": "https://www.icmarketspartners.com/",
      "partnerships/regional-partnerships": "https://www.icmarketspartners.com/",
      "partnerships/introducing-broker": "https://www.icmarketspartners.com/",
      "partnerships/affiliate-program": "https://www.icmarketspartners.com/"
    }
  },
  per_host_redirects: {
    "sc_host": {
    },
    "bs_host": {
    }
  },
  google_internal_ips_for_seo: [
    "8.8.4.0","8.8.8.0","8.34.208.0","8.35.192.0","23.236.48.0",
    "23.251.128.0","34.0.0.0","34.2.0.0","34.3.0.0","34.3.3.0",
    "34.3.4.0","34.3.8.0","34.3.16.0","34.3.32.0","34.3.64.0",
    "34.3.128.0","34.4.0.0","34.8.0.0","34.16.0.0","34.32.0.0",
    "34.64.0.0","34.128.0.0","35.184.0.0","35.192.0.0","35.196.0.0",
    "35.198.0.0","35.199.0.0","35.199.128.0","35.200.0.0","35.208.0.0",
    "35.224.0.0","35.240.0.0","64.15.112.0","64.233.160.0","66.22.228.0",
    "66.102.0.0","66.249.64.0","70.32.128.0","72.14.192.0","74.114.24.0",
    "74.125.0.0","104.154.0.0","104.196.0.0","104.237.160.0","107.167.160.0",
    "107.178.192.0","108.59.80.0","108.170.192.0","108.177.0.0","130.211.0.0",
    "136.112.0.0","142.250.0.0","146.148.0.0","162.216.148.0","162.222.176.0",
    "172.110.32.0","172.217.0.0","172.253.0.0","173.194.0.0","173.255.112.0",
    "192.158.28.0","192.178.0.0","193.186.4.0","199.36.154.0","199.36.156.0",
    "199.192.112.0","199.223.232.0","207.223.160.0","208.65.152.0","208.68.108.0",
    "208.81.188.0","208.117.224.0","209.85.128.0","216.58.192.0","216.73.80.0","216.239.32.0"
  ]
};
