export enum ActionType {
    GET_FEED_DATA = "GET_FEED_DATA",
    GET_FEED_DATA_SUCCESS = "GET_FEED_DATA_SUCCESS",
    GET_FEED_DATA_ERROR = "GET_FEED_DATA_ERROR",
    GO_TO_STEP = "GO_TO_STEP",
    SET_STEP_STATUS = "SET_STEP_STATUS",
    UPDATE_FORM_VALUES = "UPDATE_FORM_VALUES",
    CHANGE_ACCOUNT_TYPE = "CHANGE_ACCOUNT_TYPE",
    CHANGE_CURRENT_COUNTRY = "CHANGE_CURRENT_COUNTRY",
    USE_REGISTERED_ADDRESS = "USE_REGISTERED_ADDRESS",
    FORCE_USE_CN_NAMES = "FORCE_USE_CN_NAMES",
    UPDATE_EMAIL_VERIFIED_STATUS = "UPDATE_EMAIL_VERIFIED_STATUS",
    UPDATE_PHONE_VERIFIED_STATUS = "UPDATE_PHONE_VERIFIED_STATUS",
    UPDATE_SHOW_AUTO_ADDRESS_STATUS = "UPDATE_SHOW_AUTO_ADDRESS_STATUS",
    UPDATE_SUMSUB_CREDENTIAL = "UPDATE_SUMSUB_CREDENTIAL",
    UPDATE_SUMSUB_VERIFIED_STATUS = "UPDATE_SUMSUB_VERIFIED_STATUS",
    UPDATE_MODAL_DATA = "UPDATE_MODAL_DATA",
    SET_SHOW_REG_OVERLAY = "SET_SHOW_REG_OVERLAY"
}
