// from the page trading-markets/stocks call this one:
// $('.table-row:visible').length (count of stocks we have in website now)
//
// let wehave = {};
// $('.table-row:visible').each(function (e) { let key = $(this).find('.c1').text(); wehave[key] = key; });
// console.log(Object.keys(wehave).length);
//

// orig - is a values from the all_stocks Excel table
let orig = {
    "AAPL.NAS": "AAPL.NAS",
    "ADBE.NAS": "ADBE.NAS",
    "ADI.NAS": "ADI.NAS",
    "ADP.NAS": "ADP.NAS",
    "AMAT.NAS": "AMAT.NAS",
    "AMGN.NAS": "AMGN.NAS",
    "AMZN.NAS": "AMZN.NAS",
    "ATVI.NAS": "ATVI.NAS",
    "AVGO.NAS": "AVGO.NAS",
    "BIIB.NAS": "BIIB.NAS",
    "BKNG.NAS": "BKNG.NAS",
    "CHTR.NAS": "CHTR.NAS",
    "CME.NAS": "CME.NAS",
    "CMCSA.NAS": "CMCSA.NAS",
    "COST.NAS": "COST.NAS",
    "CRON.NAS": "CRON.NAS",
    "CSCO.NAS": "CSCO.NAS",
    "CSX.NAS": "CSX.NAS",
    "CTSH.NAS": "CTSH.NAS",
    "DISH.NAS": "DISH.NAS",
    "EA.NAS": "EA.NAS",
    "EBAY.NAS": "EBAY.NAS",
    "EQIX.NAS": "EQIX.NAS",
    "FB.NAS": "FB.NAS",
    "LYFT.NAS": "LYFT.NAS",
    "FOX.NAS": "FOX.NAS",
    "FOXA.NAS": "FOXA.NAS",
    "GILD.NAS": "GILD.NAS",
    "GOOG.NAS": "GOOG.NAS",
    "INTC.NAS": "INTC.NAS",
    "INTU.NAS": "INTU.NAS",
    "ISRG.NAS": "ISRG.NAS",
    "KHC.NAS": "KHC.NAS",
    "MAR.NAS": "MAR.NAS",
    "MDLZ.NAS": "MDLZ.NAS",
    "MSFT.NAS": "MSFT.NAS",
    "MU.NAS": "MU.NAS",
    "NFLX.NAS": "NFLX.NAS",
    "NVDA.NAS": "NVDA.NAS",
    "PEP.NAS": "PEP.NAS",
    "PYPL.NAS": "PYPL.NAS",
    "QCOM.NAS": "QCOM.NAS",
    "REGN.NAS": "REGN.NAS",
    "SBUX.NAS": "SBUX.NAS",
    "TLRY.NAS": "TLRY.NAS",
    "TMUS.NAS": "TMUS.NAS",
    "TSLA.NAS": "TSLA.NAS",
    "TXN.NAS": "TXN.NAS",
    "VRTX.NAS": "VRTX.NAS",
    "WBA.NAS": "WBA.NAS",
    "ABMD.NAS": "ABMD.NAS",
    "AMD.NAS": "AMD.NAS",
    "AKAM.NAS": "AKAM.NAS",
    "ALXN.NAS": "ALXN.NAS",
    "ALGN.NAS": "ALGN.NAS",
    "LNT.NAS": "LNT.NAS",
    "AAL.NAS": "AAL.NAS",
    "AEP.NAS": "AEP.NAS",
    "ANSS.NAS": "ANSS.NAS",
    "APA.NAS": "APA.NAS",
    "ADSK.NAS": "ADSK.NAS",
    "CHRW.NAS": "CHRW.NAS",
    "CDNS.NAS": "CDNS.NAS",
    "CDW.NAS": "CDW.NAS",
    "CERN.NAS": "CERN.NAS",
    "CINF.NAS": "CINF.NAS",
    "CTAS.NAS": "CTAS.NAS",
    "CTXS.NAS": "CTXS.NAS",
    "CPRT.NAS": "CPRT.NAS",
    "XRAY.NAS": "XRAY.NAS",
    "DXCM.NAS": "DXCM.NAS",
    "FANG.NAS": "FANG.NAS",
    "DLTR.NAS": "DLTR.NAS",
    "ENPH.NAS": "ENPH.NAS",
    "ETSY.NAS": "ETSY.NAS",
    "EXC.NAS": "EXC.NAS",
    "EXPE.NAS": "EXPE.NAS",
    "EXPD.NAS": "EXPD.NAS",
    "FFIV.NAS": "FFIV.NAS",
    "FAST.NAS": "FAST.NAS",
    "FITB.NAS": "FITB.NAS",
    "FISV.NAS": "FISV.NAS",
    "FTNT.NAS": "FTNT.NAS",
    "GRMN.NAS": "GRMN.NAS",
    "GPC.NAS": "GPC.NAS",
    "HAS.NAS": "HAS.NAS",
    "HSIC.NAS": "HSIC.NAS",
    "HOLX.NAS": "HOLX.NAS",
    "HST.NAS": "HST.NAS",
    "HBAN.NAS": "HBAN.NAS",
    "IDXX.NAS": "IDXX.NAS",
    "ILMN.NAS": "ILMN.NAS",
    "INCY.NAS": "INCY.NAS",
    "IPGP.NAS": "IPGP.NAS",
    "JBHT.NAS": "JBHT.NAS",
    "KLAC.NAS": "KLAC.NAS",
    "LRCX.NAS": "LRCX.NAS",
    "MXIM.NAS": "MXIM.NAS",
    "MCHP.NAS": "MCHP.NAS",
    "MNST.NAS": "MNST.NAS",
    "NDAQ.NAS": "NDAQ.NAS",
    "NTAP.NAS": "NTAP.NAS",
    "NWL.NAS": "NWL.NAS",
    "NWSA.NAS": "NWSA.NAS",
    "NWS.NAS": "NWS.NAS",
    "NTRS.NAS": "NTRS.NAS",
    "NLOK.NAS": "NLOK.NAS",
    "ORLY.NAS": "ORLY.NAS",
    "PCAR.NAS": "PCAR.NAS",
    "PAYX.NAS": "PAYX.NAS",
    "PBCT.NAS": "PBCT.NAS",
    "PFG.NAS": "PFG.NAS",
    "REG.NAS": "REG.NAS",
    "ROST.NAS": "ROST.NAS",
    "STX.NAS": "STX.NAS",
    "TROW.NAS": "TROW.NAS",
    "TER.NAS": "TER.NAS",
    "ULTA.NAS": "ULTA.NAS",
    "UAL.NAS": "UAL.NAS",
    "VRSN.NAS": "VRSN.NAS",
    "VIAC.NAS": "VIAC.NAS",
    "VTRS.NAS": "VTRS.NAS",
    "VG.NAS": "VG.NAS",
    "WDC.NAS": "WDC.NAS",
    "WLTW.NAS": "WLTW.NAS",
    "WYNN.NAS": "WYNN.NAS",
    "XEL.NAS": "XEL.NAS",
    "XLNX.NAS": "XLNX.NAS",
    "ZION.NAS": "ZION.NAS",
    "JKHY.NAS": "JKHY.NAS",
    "LKQ.NAS": "LKQ.NAS",
    "MKTX.NAS": "MKTX.NAS",
    "ODFL.NAS": "ODFL.NAS",
    "POOL.NAS": "POOL.NAS",
    "QRVO.NAS": "QRVO.NAS",
    "RDWR.NAS": "RDWR.NAS",
    "SBAC.NAS": "SBAC.NAS",
    "SWKS.NAS": "SWKS.NAS",
    "SIVB.NAS": "SIVB.NAS",
    "SNPS.NAS": "SNPS.NAS",
    "TTWO.NAS": "TTWO.NAS",
    "TSCO.NAS": "TSCO.NAS",
    "TRMB.NAS": "TRMB.NAS",
    "VRSK.NAS": "VRSK.NAS",
    "ZBRA.NAS": "ZBRA.NAS",
    "ABNB.NAS": "ABNB.NAS",
    "ZM.NAS": "ZM.NAS",
    "MRNA.NAS": "MRNA.NAS",
    "WDAY.NAS": "WDAY.NAS",
    "ROKU.NAS": "ROKU.NAS",
    "CRWD.NAS": "CRWD.NAS",
    "DOCU.NAS": "DOCU.NAS",
    "ZG.NAS": "ZG.NAS",
    "Z.NAS": "Z.NAS",
    "PTON.NAS": "PTON.NAS",
    "MTCH.NAS": "MTCH.NAS",
    "KDP.NAS": "KDP.NAS",
    "TTD.NAS": "TTD.NAS",
    "OKTA.NAS": "OKTA.NAS",
    "CSGP.NAS": "CSGP.NAS",
    "LBRDK.NAS": "LBRDK.NAS",
    "LBRDA.NAS": "LBRDA.NAS",
    "DDOG.NAS": "DDOG.NAS",
    "PLUG.NAS": "PLUG.NAS",
    "IBKR.NAS": "IBKR.NAS",
    "AFRM.NAS": "AFRM.NAS",
    "ZS.NAS": "ZS.NAS",
    "RPRX.NAS": "RPRX.NAS",
    "SGEN.NAS": "SGEN.NAS",
    "SPLK.NAS": "SPLK.NAS",
    "COUP.NAS": "COUP.NAS",
    "EXAS.NAS": "EXAS.NAS",
    "MDB.NAS": "MDB.NAS",
    "SIRI.NAS": "SIRI.NAS",
    "DKNG.NAS": "DKNG.NAS",
    "DISCA.NAS": "DISCA.NAS",
    "IAC.NAS": "IAC.NAS",
    "ZI.NAS": "ZI.NAS",
    "GDRX.NAS": "GDRX.NAS",
    "EXPI.NAS": "EXPI.NAS",
    "TXG.NAS": "TXG.NAS",
    "LOGI.NAS": "LOGI.NAS",
    "DISCK.NAS": "DISCK.NAS",
    "NVAX.NAS": "NVAX.NAS",
    "WMG.NAS": "WMG.NAS",
    "PODD.NAS": "PODD.NAS",
    "WISH.NAS": "WISH.NAS",
    "OPEN.NAS": "OPEN.NAS",
    "PENN.NAS": "PENN.NAS",
    "ALNY.NAS": "ALNY.NAS",
    "MPWR.NAS": "MPWR.NAS",
    "ON.NAS": "ON.NAS",
    "SSNC.NAS": "SSNC.NAS",
    "CZR.NAS": "CZR.NAS",
    "PTC.NAS": "PTC.NAS",
    "RUN.NAS": "RUN.NAS",
    "CGNX.NAS": "CGNX.NAS",
    "BMRN.NAS": "BMRN.NAS",
    "APPN.NAS": "APPN.NAS",
    "TECH.NAS": "TECH.NAS",
    "MASI.NAS": "MASI.NAS",
    "LSXMK.NAS": "LSXMK.NAS",
    "IEP.NAS": "IEP.NAS",
    "NUAN.NAS": "NUAN.NAS",
    "ENTG.NAS": "ENTG.NAS",
    "CREE.NAS": "CREE.NAS",
    "ERIE.NAS": "ERIE.NAS",
    "PPD.NAS": "PPD.NAS",
    "CG.NAS": "CG.NAS",
    "BSY.NAS": "BSY.NAS",
    "SPWR.NAS": "SPWR.NAS",
    "ZNGA.NAS": "ZNGA.NAS",
    "RGEN.NAS": "RGEN.NAS",
    "LAZR.NAS": "LAZR.NAS",
    "FIVN.NAS": "FIVN.NAS",
    "PEGA.NAS": "PEGA.NAS",
    "SBNY.NAS": "SBNY.NAS",
    "OLED.NAS": "OLED.NAS",
    "PCTY.NAS": "PCTY.NAS",
    "BYND.NAS": "BYND.NAS",
    "NDSN.NAS": "NDSN.NAS",
    "AZPN.NAS": "AZPN.NAS",
    "FIVE.NAS": "FIVE.NAS",
    "NBIX.NAS": "NBIX.NAS",
    "FSLR.NAS": "FSLR.NAS",
    "MORN.NAS": "MORN.NAS",
    "NTRA.NAS": "NTRA.NAS",
    "MRTX.NAS": "MRTX.NAS",
    "FWONK.NAS": "FWONK.NAS",
    "LPLA.NAS": "LPLA.NAS",
    "DBX.NAS": "DBX.NAS",
    "AMED.NAS": "AMED.NAS",
    "GLPI.NAS": "GLPI.NAS",
    "ONTX.NAS": "ONTX.NAS",
    "SNDL.NAS": "SNDL.NAS",
    "TNXP.NAS": "TNXP.NAS",
    "TXMD.NAS": "TXMD.NAS",
    "NOVN.NAS": "NOVN.NAS",
    "ACRX.NAS": "ACRX.NAS",
    "TTOO.NAS": "TTOO.NAS",
    "GERN.NAS": "GERN.NAS",
    "XSPA.NAS": "XSPA.NAS",
    "JFU.NAS": "JFU.NAS",
    "VEON.NAS": "VEON.NAS",
    "TRVN.NAS": "TRVN.NAS",
    "GNUS.NAS": "GNUS.NAS",
    "ATHX.NAS": "ATHX.NAS",
    "CRBP.NAS": "CRBP.NAS",
    "AGRX.NAS": "AGRX.NAS",
    "MARK.NAS": "MARK.NAS",
    "TELL.NAS": "TELL.NAS",
    "NBEV.NAS": "NBEV.NAS",
    "NERV.NAS": "NERV.NAS",
    "WTRH.NAS": "WTRH.NAS",
    "VSTM.NAS": "VSTM.NAS",
    "AGEN.NAS": "AGEN.NAS",
    "VBIV.NAS": "VBIV.NAS",
    "CHMA.NAS": "CHMA.NAS",
    "SPPI.NAS": "SPPI.NAS",
    "ABUS.NAS": "ABUS.NAS",
    "RIGL.NAS": "RIGL.NAS",
    "IFRX.NAS": "IFRX.NAS",
    "LLNW.NAS": "LLNW.NAS",
    "KDMN.NAS": "KDMN.NAS",
    "OVID.NAS": "OVID.NAS",
    "CRNT.NAS": "CRNT.NAS",
    "WATT.NAS": "WATT.NAS",
    "RESN.NAS": "RESN.NAS",
    "SELB.NAS": "SELB.NAS",
    "ATRS.NAS": "ATRS.NAS",
    "GNPX.NAS": "GNPX.NAS",
    "MNKD.NAS": "MNKD.NAS",
    "ATNX.NAS": "ATNX.NAS",
    "TRVG.NAS": "TRVG.NAS",
    "VRAY.NAS": "VRAY.NAS",
    "CDEV.NAS": "CDEV.NAS",
    "OPK.NAS": "OPK.NAS",
    "CPRX.NAS": "CPRX.NAS",
    "CBAY.NAS": "CBAY.NAS",
    "NYMT.NAS": "NYMT.NAS",
    "ZYNE.NAS": "ZYNE.NAS",
    "NCMI.NAS": "NCMI.NAS",
    "IZEA.NAS": "IZEA.NAS",
    "VYGR.NAS": "VYGR.NAS",
    "SOLO.NAS": "SOLO.NAS",
    "ARAY.NAS": "ARAY.NAS",
    "ADAP.NAS": "ADAP.NAS",
    "KIN.NAS": "KIN.NAS",
    "BGCP.NAS": "BGCP.NAS",
    "LXRX.NAS": "LXRX.NAS",
    "VXRT.NAS": "VXRT.NAS",
    "FRSX.NAS": "FRSX.NAS",
    "PNNT.NAS": "PNNT.NAS",
    "CERS.NAS": "CERS.NAS",
    "VKTX.NAS": "VKTX.NAS",
    "CLMT.NAS": "CLMT.NAS",
    "AYRO.NAS": "AYRO.NAS",
    "WIMI.NAS": "WIMI.NAS",
    "GSKY.NAS": "GSKY.NAS",
    "LTRPA.NAS": "LTRPA.NAS",
    "XNET.NAS": "XNET.NAS",
    "KNDI.NAS": "KNDI.NAS",
    "WETF.NAS": "WETF.NAS",
    "PRQR.NAS": "PRQR.NAS",
    "VYNE.NAS": "VYNE.NAS",
    "CLVS.NAS": "CLVS.NAS",
    "CNDT.NAS": "CNDT.NAS",
    "MGI.NAS": "MGI.NAS",
    "ORTX.NAS": "ORTX.NAS",
    "PTEN.NAS": "PTEN.NAS",
    "AYTU.NAS": "AYTU.NAS",
    "PGEN.NAS": "PGEN.NAS",
    "PRTK.NAS": "PRTK.NAS",
    "HMHC.NAS": "HMHC.NAS",
    "PLYA.NAS": "PLYA.NAS",
    "HTBX.NAS": "HTBX.NAS",
    "SRNE.NAS": "SRNE.NAS",
    "ORBC.NAS": "ORBC.NAS",
    "BNGO.NAS": "BNGO.NAS",
    "OCGN.NAS": "OCGN.NAS",
    "IMGN.NAS": "IMGN.NAS",
    "NNDM.NAS": "NNDM.NAS",
    "PSEC.NAS": "PSEC.NAS",
    "HLIT.NAS": "HLIT.NAS",
    "SURF.NAS": "SURF.NAS",
    "EPZM.NAS": "EPZM.NAS",
    "SFT.NAS": "SFT.NAS",
    "GEVO.NAS": "GEVO.NAS",
    "INO.NAS": "INO.NAS",
    "DTIL.NAS": "DTIL.NAS",
    "INSG.NAS": "INSG.NAS",
    "GOSS.NAS": "GOSS.NAS",
    "PAA.NAS": "PAA.NAS",
    "CASA.NAS": "CASA.NAS",
    "CODX.NAS": "CODX.NAS",
    "EGAN.NAS": "EGAN.NAS",
    "FOLD.NAS": "FOLD.NAS",
    "PBYI.NAS": "PBYI.NAS",
    "PAGP.NAS": "PAGP.NAS",
    "ADVM.NAS": "ADVM.NAS",
    "SY.NAS": "SY.NAS",
    "INFN.NAS": "INFN.NAS",
    "TACO.NAS": "TACO.NAS",
    "CRMD.NAS": "CRMD.NAS",
    "DVAX.NAS": "DVAX.NAS",
    "PRVB.NAS": "PRVB.NAS",
    "GOGO.NAS": "GOGO.NAS",
    "SDC.NAS": "SDC.NAS",
    "DOYU.NAS": "DOYU.NAS",
    "GLAD.NAS": "GLAD.NAS",
    "NMRK.NAS": "NMRK.NAS",
    "LUNA.NAS": "LUNA.NAS",
    "BCRX.NAS": "BCRX.NAS",
    "QIWI.NAS": "QIWI.NAS",
    "NDLS.NAS": "NDLS.NAS",
    "OSUR.NAS": "OSUR.NAS",
    "GLNG.NAS": "GLNG.NAS",
    "VRA.NAS": "VRA.NAS",
    "UNIT.NAS": "UNIT.NAS",
    "CAMP.NAS": "CAMP.NAS",
    "CRIS.NAS": "CRIS.NAS",
    "SGMO.NAS": "SGMO.NAS",
    "QRTEA.NAS": "QRTEA.NAS",
    "SVC.NAS": "SVC.NAS",
    "GPRO.NAS": "GPRO.NAS",
    "PFLT.NAS": "PFLT.NAS",
    "ALDX.NAS": "ALDX.NAS",
    "FOSL.NAS": "FOSL.NAS",
    "CWCO.NAS": "CWCO.NAS",
    "NESR.NAS": "NESR.NAS",
    "FCEL.NAS": "FCEL.NAS",
    "NKLA.NAS": "NKLA.NAS",
    "PVAC.NAS": "PVAC.NAS",
    "ERIC.NAS": "ERIC.NAS",
    "WKHS.NAS": "WKHS.NAS",
    "ALT.NAS": "ALT.NAS",
    "LILA.NAS": "LILA.NAS",
    "CLNE.NAS": "CLNE.NAS",
    "EOLS.NAS": "EOLS.NAS",
    "ATRA.NAS": "ATRA.NAS",
    "AINV.NAS": "AINV.NAS",
    "ANGI.NAS": "ANGI.NAS",
    "ISBC.NAS": "ISBC.NAS",
    "NAVI.NAS": "NAVI.NAS",
    "CHRS.NAS": "CHRS.NAS",
    "SSSS.NAS": "SSSS.NAS",
    "MRNS.NAS": "MRNS.NAS",
    "ZYXI.NAS": "ZYXI.NAS",
    "MITK.NAS": "MITK.NAS",
    "COMM.NAS": "COMM.NAS",
    "SSRM.NAS": "SSRM.NAS",
    "MOMO.NAS": "MOMO.NAS",
    "SABR.NAS": "SABR.NAS",
    "MVIS.NAS": "MVIS.NAS",
    "AVXL.NAS": "AVXL.NAS",
    "VIAV.NAS": "VIAV.NAS",
    "ROIC.NAS": "ROIC.NAS",
    "MDIV.NAS": "MDIV.NAS",
    "APHA.NAS": "APHA.NAS",
    "OCUL.NAS": "OCUL.NAS",
    "AGNC.NAS": "AGNC.NAS",
    "XBIT.NAS": "XBIT.NAS",
    "SPWH.NAS": "SPWH.NAS",
    "IHRT.NAS": "IHRT.NAS",
    "BPY.NAS": "BPY.NAS",
    "SWBI.NAS": "SWBI.NAS",
    "DENN.NAS": "DENN.NAS",
    "AMRS.NAS": "AMRS.NAS",
    "GT.NAS": "GT.NAS",
    "CAN.NAS": "CAN.NAS",
    "SBRA.NAS": "SBRA.NAS",
    "FLEX.NAS": "FLEX.NAS",
    "SVMK.NAS": "SVMK.NAS",
    "SLM.NAS": "SLM.NAS",
    "ARCC.NAS": "ARCC.NAS",
    "AXGN.NAS": "AXGN.NAS",
    "NKTR.NAS": "NKTR.NAS",
    "SPTN.NAS": "SPTN.NAS",
    "FEYE.NAS": "FEYE.NAS",
    "STAY.NAS": "STAY.NAS",
    "TTCF.NAS": "TTCF.NAS",
    "MCRB.NAS": "MCRB.NAS",
    "GOOD.NAS": "GOOD.NAS",
    "MLCO.NAS": "MLCO.NAS",
    "MAT.NAS": "MAT.NAS",
    "ACAD.NAS": "ACAD.NAS",
    "JBLU.NAS": "JBLU.NAS",
    "PCVX.NAS": "PCVX.NAS",
    "CLDX.NAS": "CLDX.NAS",
    "VREX.NAS": "VREX.NAS",
    "CLSK.NAS": "CLSK.NAS",
    "WEN.NAS": "WEN.NAS",
    "AVID.NAS": "AVID.NAS",
    "CONN.NAS": "CONN.NAS",
    "NMIH.NAS": "NMIH.NAS",
    "TVTY.NAS": "TVTY.NAS",
    "LI.NAS": "LI.NAS",
    "ICPT.NAS": "ICPT.NAS",
    "CYTK.NAS": "CYTK.NAS",
    "SNDX.NAS": "SNDX.NAS",
    "CNST.NAS": "CNST.NAS",
    "EXEL.NAS": "EXEL.NAS",
    "ILPT.NAS": "ILPT.NAS",
    "RUBY.NAS": "RUBY.NAS",
    "CDXS.NAS": "CDXS.NAS",
    "ALVR.NAS": "ALVR.NAS",
    "RUTH.NAS": "RUTH.NAS",
    "QFIN.NAS": "QFIN.NAS",
    "LBTYK.NAS": "LBTYK.NAS",
    "LBTYA.NAS": "LBTYA.NAS",
    "SFM.NAS": "SFM.NAS",
    "HA.NAS": "HA.NAS",
    "RVNC.NAS": "RVNC.NAS",
    "CARA.NAS": "CARA.NAS",
    "BLMN.NAS": "BLMN.NAS",
    "FLWS.NAS": "FLWS.NAS",
    "ANDE.NAS": "ANDE.NAS",
    "HEAR.NAS": "HEAR.NAS",
    "NTNX.NAS": "NTNX.NAS",
    "KTOS.NAS": "KTOS.NAS",
    "OPI.NAS": "OPI.NAS",
    "BBBY.NAS": "BBBY.NAS",
    "GPRE.NAS": "GPRE.NAS",
    "TSEM.NAS": "TSEM.NAS",
    "VUZI.NAS": "VUZI.NAS",
    "BLUE.NAS": "BLUE.NAS",
    "SBGI.NAS": "SBGI.NAS",
    "GIII.NAS": "GIII.NAS",
    "MMYT.NAS": "MMYT.NAS",
    "ITCI.NAS": "ITCI.NAS",
    "CHEF.NAS": "CHEF.NAS",
    "PDCO.NAS": "PDCO.NAS",
    "WW.NAS": "WW.NAS",
    "PACB.NAS": "PACB.NAS",
    "QURE.NAS": "QURE.NAS",
    "PINC.NAS": "PINC.NAS",
    "SNSR.NAS": "SNSR.NAS",
    "EGLE.NAS": "EGLE.NAS",
    "EH.NAS": "EH.NAS",
    "SSTI.NAS": "SSTI.NAS",
    "PDCE.NAS": "PDCE.NAS",
    "BLFS.NAS": "BLFS.NAS",
    "STOK.NAS": "STOK.NAS",
    "GNTX.NAS": "GNTX.NAS",
    "NIU.NAS": "NIU.NAS",
    "AY.NAS": "AY.NAS",
    "EVER.NAS": "EVER.NAS",
    "GO.NAS": "GO.NAS",
    "BZUN.NAS": "BZUN.NAS",
    "URBN.NAS": "URBN.NAS",
    "TCOM.NAS": "TCOM.NAS",
    "XP.NAS": "XP.NAS",
    "PFF.NAS": "PFF.NAS",
    "VRM.NAS": "VRM.NAS",
    "RRGB.NAS": "RRGB.NAS",
    "TIGO.NAS": "TIGO.NAS",
    "ARCT.NAS": "ARCT.NAS",
    "FWONA.NAS": "FWONA.NAS",
    "SONO.NAS": "SONO.NAS",
    "IRDM.NAS": "IRDM.NAS",
    "ONEM.NAS": "ONEM.NAS",
    "CORE.NAS": "CORE.NAS",
    "EDIT.NAS": "EDIT.NAS",
    "SANM.NAS": "SANM.NAS",
    "ODP.NAS": "ODP.NAS",
    "BLNK.NAS": "BLNK.NAS",
    "SLGN.NAS": "SLGN.NAS",
    "HALO.NAS": "HALO.NAS",
    "CIBR.NAS": "CIBR.NAS",
    "AVT.NAS": "AVT.NAS",
    "HAIN.NAS": "HAIN.NAS",
    "NATI.NAS": "NATI.NAS",
    "PGNY.NAS": "PGNY.NAS",
    "PLAY.NAS": "PLAY.NAS",
    "IONS.NAS": "IONS.NAS",
    "CSOD.NAS": "CSOD.NAS",
    "CSIQ.NAS": "CSIQ.NAS",
    "UPWK.NAS": "UPWK.NAS",
    "RVMD.NAS": "RVMD.NAS",
    "BHF.NAS": "BHF.NAS",
    "VIR.NAS": "VIR.NAS",
    "FROG.NAS": "FROG.NAS",
    "BLDR.NAS": "BLDR.NAS",
    "MARA.NAS": "MARA.NAS",
    "FIZZ.NAS": "FIZZ.NAS",
    "LSCC.NAS": "LSCC.NAS",
    "WB.NAS": "WB.NAS",
    "MRVL.NAS": "MRVL.NAS",
    "ISTB.NAS": "ISTB.NAS",
    "STLD.NAS": "STLD.NAS",
    "VTIP.NAS": "VTIP.NAS",
    "SFIX.NAS": "SFIX.NAS",
    "ABCB.NAS": "ABCB.NAS",
    "VCYT.NAS": "VCYT.NAS",
    "IUSB.NAS": "IUSB.NAS",
    "INGN.NAS": "INGN.NAS",
    "TRIP.NAS": "TRIP.NAS",
    "SKYW.NAS": "SKYW.NAS",
    "TPIC.NAS": "TPIC.NAS",
    "AXSM.NAS": "AXSM.NAS",
    "UEIC.NAS": "UEIC.NAS",
    "HTHT.NAS": "HTHT.NAS",
    "PCH.NAS": "PCH.NAS",
    "LPSN.NAS": "LPSN.NAS",
    "DOMO.NAS": "DOMO.NAS",
    "BBIO.NAS": "BBIO.NAS",
    "CEVA.NAS": "CEVA.NAS",
    "CAKE.NAS": "CAKE.NAS",
    "SEIC.NAS": "SEIC.NAS",
    "REGI.NAS": "REGI.NAS",
    "YNDX.NAS": "YNDX.NAS",
    "JOBS.NAS": "JOBS.NAS",
    "PRFT.NAS": "PRFT.NAS",
    "OSTK.NAS": "OSTK.NAS",
    "ARWR.NAS": "ARWR.NAS",
    "STNE.NAS": "STNE.NAS",
    "SNEX.NAS": "SNEX.NAS",
    "USCR.NAS": "USCR.NAS",
    "NUVA.NAS": "NUVA.NAS",
    "RDFN.NAS": "RDFN.NAS",
    "BRKR.NAS": "BRKR.NAS",
    "HQY.NAS": "HQY.NAS",
    "SRCL.NAS": "SRCL.NAS",
    "IUSV.NAS": "IUSV.NAS",
    "IDCC.NAS": "IDCC.NAS",
    "SMTC.NAS": "SMTC.NAS",
    "CONE.NAS": "CONE.NAS",
    "PLCE.NAS": "PLCE.NAS",
    "EHTH.NAS": "EHTH.NAS",
    "IXUS.NAS": "IXUS.NAS",
    "SRPT.NAS": "SRPT.NAS",
    "MRCY.NAS": "MRCY.NAS",
    "CAR.NAS": "CAR.NAS",
    "IIVI.NAS": "IIVI.NAS",
    "SDGR.NAS": "SDGR.NAS",
    "NTLA.NAS": "NTLA.NAS",
    "SYNH.NAS": "SYNH.NAS",
    "RPD.NAS": "RPD.NAS",
    "FATE.NAS": "FATE.NAS",
    "SAGE.NAS": "SAGE.NAS",
    "MCHI.NAS": "MCHI.NAS",
    "POWI.NAS": "POWI.NAS",
    "CROX.NAS": "CROX.NAS",
    "SHY.NAS": "SHY.NAS",
    "ALRM.NAS": "ALRM.NAS",
    "CRUS.NAS": "CRUS.NAS",
    "OLLI.NAS": "OLLI.NAS",
    "ACMR.NAS": "ACMR.NAS",
    "TNDM.NAS": "TNDM.NAS",
    "LITE.NAS": "LITE.NAS",
    "CVAC.NAS": "CVAC.NAS",
    "PZZA.NAS": "PZZA.NAS",
    "AAXJ.NAS": "AAXJ.NAS",
    "ITRI.NAS": "ITRI.NAS",
    "IUSG.NAS": "IUSG.NAS",
    "BPMC.NAS": "BPMC.NAS",
    "RETA.NAS": "RETA.NAS",
    "LAMR.NAS": "LAMR.NAS",
    "ACWI.NAS": "ACWI.NAS",
    "BRKS.NAS": "BRKS.NAS",
    "TXRH.NAS": "TXRH.NAS",
    "SKYY.NAS": "SKYY.NAS",
    "NTES.NAS": "NTES.NAS",
    "AMBA.NAS": "AMBA.NAS",
    "BILI.NAS": "BILI.NAS",
    "CDLX.NAS": "CDLX.NAS",
    "EMB.NAS": "EMB.NAS",
    "SHV.NAS": "SHV.NAS",
    "NARI.NAS": "NARI.NAS",
    "JACK.NAS": "JACK.NAS",
    "RYAAY.NAS": "RYAAY.NAS",
    "IEF.NAS": "IEF.NAS",
    "BNTX.NAS": "BNTX.NAS",
    "AVAV.NAS": "AVAV.NAS",
    "CHKP.NAS": "CHKP.NAS",
    "DVY.NAS": "DVY.NAS",
    "IRBT.NAS": "IRBT.NAS",
    "CRSP.NAS": "CRSP.NAS",
    "LECO.NAS": "LECO.NAS",
    "VC.NAS": "VC.NAS",
    "EVBG.NAS": "EVBG.NAS",
    "PFPT.NAS": "PFPT.NAS",
    "QDEL.NAS": "QDEL.NAS",
    "SWAV.NAS": "SWAV.NAS",
    "NVCR.NAS": "NVCR.NAS",
    "IRTC.NAS": "IRTC.NAS",
    "CYBR.NAS": "CYBR.NAS",
    "SYNA.NAS": "SYNA.NAS",
    "PDD.NAS": "PDD.NAS",
    "APPF.NAS": "APPF.NAS",
    "EEFT.NAS": "EEFT.NAS",
    "NXST.NAS": "NXST.NAS",
    "SLAB.NAS": "SLAB.NAS",
    "JOUT.NAS": "JOUT.NAS",
    "IBB.NAS": "IBB.NAS",
    "PRAH.NAS": "PRAH.NAS",
    "FRPT.NAS": "FRPT.NAS",
    "JAZZ.NAS": "JAZZ.NAS",
    "SAFM.NAS": "SAFM.NAS",
    "CBRL.NAS": "CBRL.NAS",
    "UTHR.NAS": "UTHR.NAS",
    "MKSI.NAS": "MKSI.NAS",
    "STMP.NAS": "STMP.NAS",
    "NXPI.NAS": "NXPI.NAS",
    "IDEX.NAS": "IDEX.NAS",
    "CASY.NAS": "CASY.NAS",
    "TEAM.NAS": "TEAM.NAS",
    "BIDU.NAS": "BIDU.NAS",
    "TREE.NAS": "TREE.NAS",
    "CHDN.NAS": "CHDN.NAS",
    "NICE.NAS": "NICE.NAS",
    "SMH.NAS": "SMH.NAS",
    "VONG.NAS": "VONG.NAS",
    "SEDG.NAS": "SEDG.NAS",
    "WIX.NAS": "WIX.NAS",
    "LULU.NAS": "LULU.NAS",
    "CACC.NAS": "CACC.NAS",
    "SOXX.NAS": "SOXX.NAS",
    "MSTR.NAS": "MSTR.NAS",
    "MELI.NAS": "MELI.NAS",
    "TLT.NAS": "TLT.NAS",
    "QQQ.NAS": "QQQ.NAS",
    "AMC.ASX": "AMC.ASX",
    "AMP.ASX": "AMP.ASX",
    "ANZ.ASX": "ANZ.ASX",
    "BHP.ASX": "BHP.ASX",
    "BXB.ASX": "BXB.ASX",
    "CBA.ASX": "CBA.ASX",
    "CSL.ASX": "CSL.ASX",
    "FMG.ASX": "FMG.ASX",
    "IAG.ASX": "IAG.ASX",
    "MQG.ASX": "MQG.ASX",
    "NAB.ASX": "NAB.ASX",
    "QBE.ASX": "QBE.ASX",
    "RIO.ASX": "RIO.ASX",
    "SCG.ASX": "SCG.ASX",
    "SUN.ASX": "SUN.ASX",
    "TCL.ASX": "TCL.ASX",
    "TLS.ASX": "TLS.ASX",
    "WBC.ASX": "WBC.ASX",
    "WES.ASX": "WES.ASX",
    "WOW.ASX": "WOW.ASX",
    "WPL.ASX": "WPL.ASX",
    "ABBV.NYSE": "ABBV.NYSE",
    "ABT.NYSE": "ABT.NYSE",
    "ACB.NYSE": "ACB.NYSE",
    "AGN.NYSE": "AGN.NYSE",
    "AMT.NYSE": "AMT.NYSE",
    "AXP.NYSE": "AXP.NYSE",
    "BA.NYSE": "BA.NYSE",
    "BABA.NYSE": "BABA.NYSE",
    "BAC.NYSE": "BAC.NYSE",
    "BLK.NYSE": "BLK.NYSE",
    "BMY.NYSE": "BMY.NYSE",
    "BRK-B.NYSE": "BRK-B.NYSE",
    "C.NYSE": "C.NYSE",
    "CGC.NYSE": "CGC.NYSE",
    "CVS.NYSE": "CVS.NYSE",
    "CVX.NYSE": "CVX.NYSE",
    "DD.NYSE": "DD.NYSE",
    "DEO.NYSE": "DEO.NYSE",
    "DIS.NYSE": "DIS.NYSE",
    "GE.NYSE": "GE.NYSE",
    "GS.NYSE": "GS.NYSE",
    "HD.NYSE": "HD.NYSE",
    "HON.NYSE": "HON.NYSE",
    "IBM.NYSE": "IBM.NYSE",
    "JNJ.NYSE": "JNJ.NYSE",
    "JPM.NYSE": "JPM.NYSE",
    "KO.NYSE": "KO.NYSE",
    "LIN.NYSE": "LIN.NYSE",
    "LLY.NYSE": "LLY.NYSE",
    "LMT.NYSE": "LMT.NYSE",
    "MA.NYSE": "MA.NYSE",
    "MCD.NYSE": "MCD.NYSE",
    "MMM.NYSE": "MMM.NYSE",
    "MO.NYSE": "MO.NYSE",
    "MRK.NYSE": "MRK.NYSE",
    "MS.NYSE": "MS.NYSE",
    "NEE.NYSE": "NEE.NYSE",
    "NKE.NYSE": "NKE.NYSE",
    "ORCL.NYSE": "ORCL.NYSE",
    "PFE.NYSE": "PFE.NYSE",
    "PG.NYSE": "PG.NYSE",
    "PM.NYSE": "PM.NYSE",
    "SLB.NYSE": "SLB.NYSE",
    "SPOT.NYSE": "SPOT.NYSE",
    "T.NYSE": "T.NYSE",
    "TM.NYSE": "TM.NYSE",
    "TMO.NYSE": "TMO.NYSE",
    "UNH.NYSE": "UNH.NYSE",
    "UNP.NYSE": "UNP.NYSE",
    "UPS.NYSE": "UPS.NYSE",
    "USB.NYSE": "USB.NYSE",
    "V.NYSE": "V.NYSE",
    "VZ.NYSE": "VZ.NYSE",
    "WFC.NYSE": "WFC.NYSE",
    "WMT.NYSE": "WMT.NYSE",
    "XOM.NYSE": "XOM.NYSE",
    "UBER.NYSE": "UBER.NYSE",
    "PINS.NYSE": "PINS.NYSE",
    "DOW.NYSE": "DOW.NYSE",
    "ACN.NYSE": "ACN.NYSE",
    "AAP.NYSE": "AAP.NYSE",
    "AES.NYSE": "AES.NYSE",
    "AFL.NYSE": "AFL.NYSE",
    "A.NYSE": "A.NYSE",
    "APD.NYSE": "APD.NYSE",
    "ALK.NYSE": "ALK.NYSE",
    "ALB.NYSE": "ALB.NYSE",
    "ARE.NYSE": "ARE.NYSE",
    "ALLE.NYSE": "ALLE.NYSE",
    "ALL.NYSE": "ALL.NYSE",
    "AMCR.NYSE": "AMCR.NYSE",
    "AEE.NYSE": "AEE.NYSE",
    "AIG.NYSE": "AIG.NYSE",
    "AWK.NYSE": "AWK.NYSE",
    "AMP.NYSE": "AMP.NYSE",
    "ABC.NYSE": "ABC.NYSE",
    "AME.NYSE": "AME.NYSE",
    "APH.NYSE": "APH.NYSE",
    "ANTM.NYSE": "ANTM.NYSE",
    "AON.NYSE": "AON.NYSE",
    "AOS.NYSE": "AOS.NYSE",
    "APTV.NYSE": "APTV.NYSE",
    "ADM.NYSE": "ADM.NYSE",
    "ANET.NYSE": "ANET.NYSE",
    "AJG.NYSE": "AJG.NYSE",
    "AIZ.NYSE": "AIZ.NYSE",
    "ATO.NYSE": "ATO.NYSE",
    "AZO.NYSE": "AZO.NYSE",
    "AVB.NYSE": "AVB.NYSE",
    "AVY.NYSE": "AVY.NYSE",
    "BLL.NYSE": "BLL.NYSE",
    "BKR.NYSE": "BKR.NYSE",
    "BK.NYSE": "BK.NYSE",
    "BAX.NYSE": "BAX.NYSE",
    "BDX.NYSE": "BDX.NYSE",
    "BBY.NYSE": "BBY.NYSE",
    "BIO.NYSE": "BIO.NYSE",
    "BWA.NYSE": "BWA.NYSE",
    "BXP.NYSE": "BXP.NYSE",
    "BSX.NYSE": "BSX.NYSE",
    "BR.NYSE": "BR.NYSE",
    "COG.NYSE": "COG.NYSE",
    "CPB.NYSE": "CPB.NYSE",
    "COF.NYSE": "COF.NYSE",
    "CAH.NYSE": "CAH.NYSE",
    "KMX.NYSE": "KMX.NYSE",
    "CCL.NYSE": "CCL.NYSE",
    "CARR.NYSE": "CARR.NYSE",
    "CTLT.NYSE": "CTLT.NYSE",
    "CAT.NYSE": "CAT.NYSE",
    "CBRE.NYSE": "CBRE.NYSE",
    "CE.NYSE": "CE.NYSE",
    "CNC.NYSE": "CNC.NYSE",
    "CNP.NYSE": "CNP.NYSE",
    "CF.NYSE": "CF.NYSE",
    "SCHW.NYSE": "SCHW.NYSE",
    "CMG.NYSE": "CMG.NYSE",
    "CB.NYSE": "CB.NYSE",
    "CHD.NYSE": "CHD.NYSE",
    "CI.NYSE": "CI.NYSE",
    "CFG.NYSE": "CFG.NYSE",
    "CLX.NYSE": "CLX.NYSE",
    "CMS.NYSE": "CMS.NYSE",
    "CL.NYSE": "CL.NYSE",
    "CMA.NYSE": "CMA.NYSE",
    "CAG.NYSE": "CAG.NYSE",
    "COP.NYSE": "COP.NYSE",
    "ED.NYSE": "ED.NYSE",
    "STZ.NYSE": "STZ.NYSE",
    "COO.NYSE": "COO.NYSE",
    "GLW.NYSE": "GLW.NYSE",
    "CTVA.NYSE": "CTVA.NYSE",
    "CCI.NYSE": "CCI.NYSE",
    "CMI.NYSE": "CMI.NYSE",
    "DHI.NYSE": "DHI.NYSE",
    "DHR.NYSE": "DHR.NYSE",
    "DRI.NYSE": "DRI.NYSE",
    "DVA.NYSE": "DVA.NYSE",
    "DE.NYSE": "DE.NYSE",
    "BF/B.NYSE": "BF/B.NYSE",
    "DAL.NYSE": "DAL.NYSE",
    "DVN.NYSE": "DVN.NYSE",
    "DLR.NYSE": "DLR.NYSE",
    "DFS.NYSE": "DFS.NYSE",
    "DG.NYSE": "DG.NYSE",
    "D.NYSE": "D.NYSE",
    "DPZ.NYSE": "DPZ.NYSE",
    "DOV.NYSE": "DOV.NYSE",
    "DTE.NYSE": "DTE.NYSE",
    "DUK.NYSE": "DUK.NYSE",
    "DRE.NYSE": "DRE.NYSE",
    "DXC.NYSE": "DXC.NYSE",
    "EMN.NYSE": "EMN.NYSE",
    "ETN.NYSE": "ETN.NYSE",
    "ECL.NYSE": "ECL.NYSE",
    "EIX.NYSE": "EIX.NYSE",
    "EW.NYSE": "EW.NYSE",
    "EMR.NYSE": "EMR.NYSE",
    "ETR.NYSE": "ETR.NYSE",
    "EOG.NYSE": "EOG.NYSE",
    "EFX.NYSE": "EFX.NYSE",
    "EQR.NYSE": "EQR.NYSE",
    "ESS.NYSE": "ESS.NYSE",
    "EL.NYSE": "EL.NYSE",
    "EVRG.NYSE": "EVRG.NYSE",
    "ES.NYSE": "ES.NYSE",
    "RE.NYSE": "RE.NYSE",
    "EXR.NYSE": "EXR.NYSE",
    "FRT.NYSE": "FRT.NYSE",
    "FDX.NYSE": "FDX.NYSE",
    "FIS.NYSE": "FIS.NYSE",
    "FE.NYSE": "FE.NYSE",
    "FRC.NYSE": "FRC.NYSE",
    "FLT.NYSE": "FLT.NYSE",
    "FLS.NYSE": "FLS.NYSE",
    "FMC.NYSE": "FMC.NYSE",
    "F.NYSE": "F.NYSE",
    "FTV.NYSE": "FTV.NYSE",
    "FBHS.NYSE": "FBHS.NYSE",
    "FCX.NYSE": "FCX.NYSE",
    "IT.NYSE": "IT.NYSE",
    "BEN.NYSE": "BEN.NYSE",
    "GPS.NYSE": "GPS.NYSE",
    "GD.NYSE": "GD.NYSE",
    "GIS.NYSE": "GIS.NYSE",
    "GM.NYSE": "GM.NYSE",
    "GL.NYSE": "GL.NYSE",
    "GPN.NYSE": "GPN.NYSE",
    "GWW.NYSE": "GWW.NYSE",
    "HAL.NYSE": "HAL.NYSE",
    "HBI.NYSE": "HBI.NYSE",
    "HIG.NYSE": "HIG.NYSE",
    "HCA.NYSE": "HCA.NYSE",
    "PEAK.NYSE": "PEAK.NYSE",
    "HSY.NYSE": "HSY.NYSE",
    "HES.NYSE": "HES.NYSE",
    "HPE.NYSE": "HPE.NYSE",
    "HLT.NYSE": "HLT.NYSE",
    "HFC.NYSE": "HFC.NYSE",
    "HRL.NYSE": "HRL.NYSE",
    "HWM.NYSE": "HWM.NYSE",
    "HPQ.NYSE": "HPQ.NYSE",
    "HUM.NYSE": "HUM.NYSE",
    "HII.NYSE": "HII.NYSE",
    "IEX.NYSE": "IEX.NYSE",
    "INFO.NYSE": "INFO.NYSE",
    "ITW.NYSE": "ITW.NYSE",
    "IR.NYSE": "IR.NYSE",
    "ICE.NYSE": "ICE.NYSE",
    "IP.NYSE": "IP.NYSE",
    "IPG.NYSE": "IPG.NYSE",
    "IFF.NYSE": "IFF.NYSE",
    "IVZ.NYSE": "IVZ.NYSE",
    "NI.NYSE": "NI.NYSE",
    "IQV.NYSE": "IQV.NYSE",
    "IRM.NYSE": "IRM.NYSE",
    "J.NYSE": "J.NYSE",
    "SJM.NYSE": "SJM.NYSE",
    "JCI.NYSE": "JCI.NYSE",
    "JNPR.NYSE": "JNPR.NYSE",
    "KSU.NYSE": "KSU.NYSE",
    "K.NYSE": "K.NYSE",
    "KEY.NYSE": "KEY.NYSE",
    "KEYS.NYSE": "KEYS.NYSE",
    "KMB.NYSE": "KMB.NYSE",
    "KIM.NYSE": "KIM.NYSE",
    "KMI.NYSE": "KMI.NYSE",
    "KR.NYSE": "KR.NYSE",
    "LB.NYSE": "LB.NYSE",
    "LHX.NYSE": "LHX.NYSE",
    "LH.NYSE": "LH.NYSE",
    "LW.NYSE": "LW.NYSE",
    "LVS.NYSE": "LVS.NYSE",
    "LEG.NYSE": "LEG.NYSE",
    "LDOS.NYSE": "LDOS.NYSE",
    "LEN.NYSE": "LEN.NYSE",
    "LNC.NYSE": "LNC.NYSE",
    "LYV.NYSE": "LYV.NYSE",
    "L.NYSE": "L.NYSE",
    "LOW.NYSE": "LOW.NYSE",
    "LUMN.NYSE": "LUMN.NYSE",
    "LYB.NYSE": "LYB.NYSE",
    "MTB.NYSE": "MTB.NYSE",
    "MRO.NYSE": "MRO.NYSE",
    "MPC.NYSE": "MPC.NYSE",
    "MMC.NYSE": "MMC.NYSE",
    "MLM.NYSE": "MLM.NYSE",
    "MAS.NYSE": "MAS.NYSE",
    "MKC.NYSE": "MKC.NYSE",
    "MCK.NYSE": "MCK.NYSE",
    "MDT.NYSE": "MDT.NYSE",
    "MET.NYSE": "MET.NYSE",
    "MTD.NYSE": "MTD.NYSE",
    "MGM.NYSE": "MGM.NYSE",
    "MAA.NYSE": "MAA.NYSE",
    "MHK.NYSE": "MHK.NYSE",
    "TAP.NYSE": "TAP.NYSE",
    "MCO.NYSE": "MCO.NYSE",
    "MOS.NYSE": "MOS.NYSE",
    "MSI.NYSE": "MSI.NYSE",
    "MSCI.NYSE": "MSCI.NYSE",
    "NEM.NYSE": "NEM.NYSE",
    "NLSN.NYSE": "NLSN.NYSE",
    "NSC.NYSE": "NSC.NYSE",
    "NOC.NYSE": "NOC.NYSE",
    "NCLH.NYSE": "NCLH.NYSE",
    "NOV.NYSE": "NOV.NYSE",
    "NRG.NYSE": "NRG.NYSE",
    "NUE.NYSE": "NUE.NYSE",
    "NVR.NYSE": "NVR.NYSE",
    "OXY.NYSE": "OXY.NYSE",
    "OMC.NYSE": "OMC.NYSE",
    "OKE.NYSE": "OKE.NYSE",
    "OTIS.NYSE": "OTIS.NYSE",
    "PKG.NYSE": "PKG.NYSE",
    "PH.NYSE": "PH.NYSE",
    "PAYC.NYSE": "PAYC.NYSE",
    "PNR.NYSE": "PNR.NYSE",
    "PKI.NYSE": "PKI.NYSE",
    "PRGO.NYSE": "PRGO.NYSE",
    "PSX.NYSE": "PSX.NYSE",
    "PNW.NYSE": "PNW.NYSE",
    "PXD.NYSE": "PXD.NYSE",
    "PNC.NYSE": "PNC.NYSE",
    "PPG.NYSE": "PPG.NYSE",
    "PPL.NYSE": "PPL.NYSE",
    "PGR.NYSE": "PGR.NYSE",
    "PLD.NYSE": "PLD.NYSE",
    "PRU.NYSE": "PRU.NYSE",
    "PEG.NYSE": "PEG.NYSE",
    "PSA.NYSE": "PSA.NYSE",
    "PHM.NYSE": "PHM.NYSE",
    "PVH.NYSE": "PVH.NYSE",
    "PWR.NYSE": "PWR.NYSE",
    "DGX.NYSE": "DGX.NYSE",
    "RJF.NYSE": "RJF.NYSE",
    "RYN.NYSE": "RYN.NYSE",
    "O.NYSE": "O.NYSE",
    "RF.NYSE": "RF.NYSE",
    "RSG.NYSE": "RSG.NYSE",
    "RMD.NYSE": "RMD.NYSE",
    "RHI.NYSE": "RHI.NYSE",
    "ROK.NYSE": "ROK.NYSE",
    "ROL.NYSE": "ROL.NYSE",
    "ROP.NYSE": "ROP.NYSE",
    "RCL.NYSE": "RCL.NYSE",
    "SPGI.NYSE": "SPGI.NYSE",
    "CRM.NYSE": "CRM.NYSE",
    "SEE.NYSE": "SEE.NYSE",
    "SRE.NYSE": "SRE.NYSE",
    "NOW.NYSE": "NOW.NYSE",
    "SHW.NYSE": "SHW.NYSE",
    "SPG.NYSE": "SPG.NYSE",
    "SLG.NYSE": "SLG.NYSE",
    "SNA.NYSE": "SNA.NYSE",
    "SO.NYSE": "SO.NYSE",
    "LUV.NYSE": "LUV.NYSE",
    "SWK.NYSE": "SWK.NYSE",
    "STT.NYSE": "STT.NYSE",
    "STE.NYSE": "STE.NYSE",
    "SYK.NYSE": "SYK.NYSE",
    "SYF.NYSE": "SYF.NYSE",
    "SYY.NYSE": "SYY.NYSE",
    "TPR.NYSE": "TPR.NYSE",
    "TGT.NYSE": "TGT.NYSE",
    "TEL.NYSE": "TEL.NYSE",
    "FTI.NYSE": "FTI.NYSE",
    "TDY.NYSE": "TDY.NYSE",
    "TFX.NYSE": "TFX.NYSE",
    "TXT.NYSE": "TXT.NYSE",
    "TJX.NYSE": "TJX.NYSE",
    "TT.NYSE": "TT.NYSE",
    "TDG.NYSE": "TDG.NYSE",
    "TRV.NYSE": "TRV.NYSE",
    "TFC.NYSE": "TFC.NYSE",
    "TWTR.NYSE": "TWTR.NYSE",
    "TYL.NYSE": "TYL.NYSE",
    "TSN.NYSE": "TSN.NYSE",
    "UDR.NYSE": "UDR.NYSE",
    "UAA.NYSE": "UAA.NYSE",
    "UA.NYSE": "UA.NYSE",
    "URI.NYSE": "URI.NYSE",
    "UHS.NYSE": "UHS.NYSE",
    "UNM.NYSE": "UNM.NYSE",
    "VLO.NYSE": "VLO.NYSE",
    "VTR.NYSE": "VTR.NYSE",
    "VFC.NYSE": "VFC.NYSE",
    "VNO.NYSE": "VNO.NYSE",
    "VMC.NYSE": "VMC.NYSE",
    "WRB.NYSE": "WRB.NYSE",
    "WAB.NYSE": "WAB.NYSE",
    "WM.NYSE": "WM.NYSE",
    "WAT.NYSE": "WAT.NYSE",
    "WEC.NYSE": "WEC.NYSE",
    "WELL.NYSE": "WELL.NYSE",
    "WST.NYSE": "WST.NYSE",
    "WU.NYSE": "WU.NYSE",
    "WRK.NYSE": "WRK.NYSE",
    "WY.NYSE": "WY.NYSE",
    "WHR.NYSE": "WHR.NYSE",
    "WMB.NYSE": "WMB.NYSE",
    "XRX.NYSE": "XRX.NYSE",
    "XYL.NYSE": "XYL.NYSE",
    "YUM.NYSE": "YUM.NYSE",
    "ZBH.NYSE": "ZBH.NYSE",
    "ZTS.NYSE": "ZTS.NYSE",
    "SE.NYSE": "SE.NYSE",
    "SQ.NYSE": "SQ.NYSE",
    "RTX.NYSE": "RTX.NYSE",
    "SNAP.NYSE": "SNAP.NYSE",
    "SNOW.NYSE": "SNOW.NYSE",
    "VMW.NYSE": "VMW.NYSE",
    "SCCO.NYSE": "SCCO.NYSE",
    "CVNA.NYSE": "CVNA.NYSE",
    "BX.NYSE": "BX.NYSE",
    "EPD.NYSE": "EPD.NYSE",
    "TDOC.NYSE": "TDOC.NYSE",
    "RKT.NYSE": "RKT.NYSE",
    "PANW.NYSE": "PANW.NYSE",
    "W.NYSE": "W.NYSE",
    "KKR.NYSE": "KKR.NYSE",
    "NET.NYSE": "NET.NYSE",
    "YUMC.NYSE": "YUMC.NYSE",
    "MPLX.NYSE": "MPLX.NYSE",
    "PCG.NYSE": "PCG.NYSE",
    "HUBS.NYSE": "HUBS.NYSE",
    "EPAM.NYSE": "EPAM.NYSE",
    "UI.NYSE": "UI.NYSE",
    "GNRC.NYSE": "GNRC.NYSE",
    "QS.NYSE": "QS.NYSE",
    "CUK.NYSE": "CUK.NYSE",
    "ATUS.NYSE": "ATUS.NYSE",
    "ET.NYSE": "ET.NYSE",
    "TRU.NYSE": "TRU.NYSE",
    "HEI.NYSE": "HEI.NYSE",
    "INVH.NYSE": "INVH.NYSE",
    "SUI.NYSE": "SUI.NYSE",
    "ALLY.NYSE": "ALLY.NYSE",
    "OSH.NYSE": "OSH.NYSE",
    "MKL.NYSE": "MKL.NYSE",
    "DT.NYSE": "DT.NYSE",
    "AVLR.NYSE": "AVLR.NYSE",
    "ESTC.NYSE": "ESTC.NYSE",
    "AGR.NYSE": "AGR.NYSE",
    "CRL.NYSE": "CRL.NYSE",
    "GDDY.NYSE": "GDDY.NYSE",
    "CDAY.NYSE": "CDAY.NYSE",
    "SAM.NYSE": "SAM.NYSE",
    "ELAN.NYSE": "ELAN.NYSE",
    "FICO.NYSE": "FICO.NYSE",
    "SMG.NYSE": "SMG.NYSE",
    "CCK.NYSE": "CCK.NYSE",
    "MPW.NYSE": "MPW.NYSE",
    "MOH.NYSE": "MOH.NYSE",
    "BRO.NYSE": "BRO.NYSE",
    "WPC.NYSE": "WPC.NYSE",
    "TREX.NYSE": "TREX.NYSE",
    "EQH.NYSE": "EQH.NYSE",
    "FDS.NYSE": "FDS.NYSE",
    "NLY.NYSE": "NLY.NYSE",
    "PLAN.NYSE": "PLAN.NYSE",
    "FNF.NYSE": "FNF.NYSE",
    "MTN.NYSE": "MTN.NYSE",
    "APO.NYSE": "APO.NYSE",
    "WTRG.NYSE": "WTRG.NYSE",
    "ELS.NYSE": "ELS.NYSE",
    "BAH.NYSE": "BAH.NYSE",
    "RPM.NYSE": "RPM.NYSE",
    "LII.NYSE": "LII.NYSE",
    "DAR.NYSE": "DAR.NYSE",
    "WLK.NYSE": "WLK.NYSE",
    "TTC.NYSE": "TTC.NYSE",
    "BG.NYSE": "BG.NYSE",
    "BFAM.NYSE": "BFAM.NYSE",
    "GWRE.NYSE": "GWRE.NYSE",
    "CPT.NYSE": "CPT.NYSE",
    "CCIV.NYSE": "CCIV.NYSE",
    "SMAR.NYSE": "SMAR.NYSE",
    "LAD.NYSE": "LAD.NYSE",
    "MGP.NYSE": "MGP.NYSE",
    "RH.NYSE": "RH.NYSE",
    "TWLO.NYSE": "TWLO.NYSE",
    "MUX.NYSE": "MUX.NYSE",
    "BEST.NYSE": "BEST.NYSE",
    "ESGC.NYSE": "ESGC.NYSE",
    "PEI.NYSE": "PEI.NYSE",
    "QD.NYSE": "QD.NYSE",
    "CIG.NYSE": "CIG.NYSE",
    "LYG.NYSE": "LYG.NYSE",
    "TTI.NYSE": "TTI.NYSE",
    "ABEV.NYSE": "ABEV.NYSE",
    "BBAR.NYSE": "BBAR.NYSE",
    "KOS.NYSE": "KOS.NYSE",
    "WMC.NYSE": "WMC.NYSE",
    "GNW.NYSE": "GNW.NYSE",
    "CHS.NYSE": "CHS.NYSE",
    "RIG.NYSE": "RIG.NYSE",
    "NAT.NYSE": "NAT.NYSE",
    "SAN.NYSE": "SAN.NYSE",
    "DS.NYSE": "DS.NYSE",
    "WTI.NYSE": "WTI.NYSE",
    "FI.NYSE": "FI.NYSE",
    "NOK.NYSE": "NOK.NYSE",
    "MITT.NYSE": "MITT.NYSE",
    "IVR.NYSE": "IVR.NYSE",
    "RRD.NYSE": "RRD.NYSE",
    "MFA.NYSE": "MFA.NYSE",
    "BRFS.NYSE": "BRFS.NYSE",
    "CO.NYSE": "CO.NYSE",
    "BBD.NYSE": "BBD.NYSE",
    "SWN.NYSE": "SWN.NYSE",
    "AUY.NYSE": "AUY.NYSE",
    "TEF.NYSE": "TEF.NYSE",
    "ITUB.NYSE": "ITUB.NYSE",
    "HMY.NYSE": "HMY.NYSE",
    "HLX.NYSE": "HLX.NYSE",
    "EXK.NYSE": "EXK.NYSE",
    "GCI.NYSE": "GCI.NYSE",
    "ARCO.NYSE": "ARCO.NYSE",
    "VHC.NYSE": "VHC.NYSE",
    "CRK.NYSE": "CRK.NYSE",
    "GGB.NYSE": "GGB.NYSE",
    "GLOG.NYSE": "GLOG.NYSE",
    "CBD.NYSE": "CBD.NYSE",
    "PRTY.NYSE": "PRTY.NYSE",
    "GEO.NYSE": "GEO.NYSE",
    "DHT.NYSE": "DHT.NYSE",
    "AMRX.NYSE": "AMRX.NYSE",
    "AIV.NYSE": "AIV.NYSE",
    "ENBL.NYSE": "ENBL.NYSE",
    "CLNY.NYSE": "CLNY.NYSE",
    "BKD.NYSE": "BKD.NYSE",
    "PHK.NYSE": "PHK.NYSE",
    "FSM.NYSE": "FSM.NYSE",
    "CORR.NYSE": "CORR.NYSE",
    "CX.NYSE": "CX.NYSE",
    "KGC.NYSE": "KGC.NYSE",
    "TWO.NYSE": "TWO.NYSE",
    "SBS.NYSE": "SBS.NYSE",
    "SOGO.NYSE": "SOGO.NYSE",
    "GOL.NYSE": "GOL.NYSE",
    "AGRO.NYSE": "AGRO.NYSE",
    "MBT.NYSE": "MBT.NYSE",
    "PBI.NYSE": "PBI.NYSE",
    "PBR.NYSE": "PBR.NYSE",
    "COTY.NYSE": "COTY.NYSE",
    "BW.NYSE": "BW.NYSE",
    "AM.NYSE": "AM.NYSE",
    "ADT.NYSE": "ADT.NYSE",
    "UMC.NYSE": "UMC.NYSE",
    "NVGS.NYSE": "NVGS.NYSE",
    "BB.NYSE": "BB.NYSE",
    "CDE.NYSE": "CDE.NYSE",
    "GEL.NYSE": "GEL.NYSE",
    "BDJ.NYSE": "BDJ.NYSE",
    "AXL.NYSE": "AXL.NYSE",
    "AROC.NYSE": "AROC.NYSE",
    "TV.NYSE": "TV.NYSE",
    "TWI.NYSE": "TWI.NYSE",
    "CMRE.NYSE": "CMRE.NYSE",
    "DNOW.NYSE": "DNOW.NYSE",
    "RYAM.NYSE": "RYAM.NYSE",
    "RRC.NYSE": "RRC.NYSE",
    "GFI.NYSE": "GFI.NYSE",
    "PGRE.NYSE": "PGRE.NYSE",
    "AR.NYSE": "AR.NYSE",
    "LFC.NYSE": "LFC.NYSE",
    "INN.NYSE": "INN.NYSE",
    "DRH.NYSE": "DRH.NYSE",
    "CTT.NYSE": "CTT.NYSE",
    "BCS.NYSE": "BCS.NYSE",
    "RWT.NYSE": "RWT.NYSE",
    "PUMP.NYSE": "PUMP.NYSE",
    "SOL.NYSE": "SOL.NYSE",
    "RPAI.NYSE": "RPAI.NYSE",
    "NRZ.NYSE": "NRZ.NYSE",
    "EGO.NYSE": "EGO.NYSE",
    "FBP.NYSE": "FBP.NYSE",
    "RFP.NYSE": "RFP.NYSE",
    "ESRT.NYSE": "ESRT.NYSE",
    "FPI.NYSE": "FPI.NYSE",
    "CEN.NYSE": "CEN.NYSE",
    "TEVA.NYSE": "TEVA.NYSE",
    "LXP.NYSE": "LXP.NYSE",
    "LBRT.NYSE": "LBRT.NYSE",
    "HYLN.NYSE": "HYLN.NYSE",
    "USX.NYSE": "USX.NYSE",
    "MGY.NYSE": "MGY.NYSE",
    "HYT.NYSE": "HYT.NYSE",
    "SLCA.NYSE": "SLCA.NYSE",
    "NPTN.NYSE": "NPTN.NYSE",
    "TALO.NYSE": "TALO.NYSE",
    "ARR.NYSE": "ARR.NYSE",
    "CYH.NYSE": "CYH.NYSE",
    "DB.NYSE": "DB.NYSE",
    "ING.NYSE": "ING.NYSE",
    "CLDR.NYSE": "CLDR.NYSE",
    "SHO.NYSE": "SHO.NYSE",
    "EC.NYSE": "EC.NYSE",
    "CIM.NYSE": "CIM.NYSE",
    "VEDL.NYSE": "VEDL.NYSE",
    "BDN.NYSE": "BDN.NYSE",
    "SCM.NYSE": "SCM.NYSE",
    "RGS.NYSE": "RGS.NYSE",
    "CARS.NYSE": "CARS.NYSE",
    "CLDT.NYSE": "CLDT.NYSE",
    "CVA.NYSE": "CVA.NYSE",
    "GMRE.NYSE": "GMRE.NYSE",
    "SITC.NYSE": "SITC.NYSE",
    "SHLX.NYSE": "SHLX.NYSE",
    "DBD.NYSE": "DBD.NYSE",
    "AMX.NYSE": "AMX.NYSE",
    "MWA.NYSE": "MWA.NYSE",
    "SCS.NYSE": "SCS.NYSE",
    "EVRI.NYSE": "EVRI.NYSE",
    "PBF.NYSE": "PBF.NYSE",
    "EDU.NYSE": "EDU.NYSE",
    "OI.NYSE": "OI.NYSE",
    "CNX.NYSE": "CNX.NYSE",
    "YEXT.NYSE": "YEXT.NYSE",
    "KAR.NYSE": "KAR.NYSE",
    "VLRS.NYSE": "VLRS.NYSE",
    "USAC.NYSE": "USAC.NYSE",
    "ZUO.NYSE": "ZUO.NYSE",
    "CBB.NYSE": "CBB.NYSE",
    "MNRL.NYSE": "MNRL.NYSE",
    "IRT.NYSE": "IRT.NYSE",
    "CLI.NYSE": "CLI.NYSE",
    "RLGY.NYSE": "RLGY.NYSE",
    "RLJ.NYSE": "RLJ.NYSE",
    "M.NYSE": "M.NYSE",
    "ABR.NYSE": "ABR.NYSE",
    "KRO.NYSE": "KRO.NYSE",
    "FSR.NYSE": "FSR.NYSE",
    "IGT.NYSE": "IGT.NYSE",
    "MUR.NYSE": "MUR.NYSE",
    "HTGC.NYSE": "HTGC.NYSE",
    "AG.NYSE": "AG.NYSE",
    "UE.NYSE": "UE.NYSE",
    "MANU.NYSE": "MANU.NYSE",
    "SA.NYSE": "SA.NYSE",
    "CXP.NYSE": "CXP.NYSE",
    "SWCH.NYSE": "SWCH.NYSE",
    "LTHM.NYSE": "LTHM.NYSE",
    "AMWL.NYSE": "AMWL.NYSE",
    "CCJ.NYSE": "CCJ.NYSE",
    "TAK.NYSE": "TAK.NYSE",
    "HSC.NYSE": "HSC.NYSE",
    "PDM.NYSE": "PDM.NYSE",
    "SM.NYSE": "SM.NYSE",
    "VST.NYSE": "VST.NYSE",
    "DBI.NYSE": "DBI.NYSE",
    "EQT.NYSE": "EQT.NYSE",
    "CCU.NYSE": "CCU.NYSE",
    "NS.NYSE": "NS.NYSE",
    "CLF.NYSE": "CLF.NYSE",
    "TPC.NYSE": "TPC.NYSE",
    "STNG.NYSE": "STNG.NYSE",
    "VALE.NYSE": "VALE.NYSE",
    "PTY.NYSE": "PTY.NYSE",
    "SBSW.NYSE": "SBSW.NYSE",
    "GPK.NYSE": "GPK.NYSE",
    "GNL.NYSE": "GNL.NYSE",
    "SRG.NYSE": "SRG.NYSE",
    "DX.NYSE": "DX.NYSE",
    "INFY.NYSE": "INFY.NYSE",
    "GTN.NYSE": "GTN.NYSE",
    "CVI.NYSE": "CVI.NYSE",
    "AKR.NYSE": "AKR.NYSE",
    "EQNR.NYSE": "EQNR.NYSE",
    "SBH.NYSE": "SBH.NYSE",
    "TME.NYSE": "TME.NYSE",
    "TECK.NYSE": "TECK.NYSE",
    "TGNA.NYSE": "TGNA.NYSE",
    "TROX.NYSE": "TROX.NYSE",
    "BRX.NYSE": "BRX.NYSE",
    "TTM.NYSE": "TTM.NYSE",
    "KW.NYSE": "KW.NYSE",
    "GOLD.NYSE": "GOLD.NYSE",
    "CAL.NYSE": "CAL.NYSE",
    "FSK.NYSE": "FSK.NYSE",
    "MTW.NYSE": "MTW.NYSE",
    "CADE.NYSE": "CADE.NYSE",
    "AZUL.NYSE": "AZUL.NYSE",
    "TPH.NYSE": "TPH.NYSE",
    "RAD.NYSE": "RAD.NYSE",
    "PSTG.NYSE": "PSTG.NYSE",
    "PK.NYSE": "PK.NYSE",
    "IMAX.NYSE": "IMAX.NYSE",
    "FLR.NYSE": "FLR.NYSE",
    "OUT.NYSE": "OUT.NYSE",
    "AU.NYSE": "AU.NYSE",
    "GLP.NYSE": "GLP.NYSE",
    "ATI.NYSE": "ATI.NYSE",
    "DK.NYSE": "DK.NYSE",
    "HRB.NYSE": "HRB.NYSE",
    "WRE.NYSE": "WRE.NYSE",
    "CNK.NYSE": "CNK.NYSE",
    "ORI.NYSE": "ORI.NYSE",
    "PLTR.NYSE": "PLTR.NYSE",
    "RDN.NYSE": "RDN.NYSE",
    "EPRT.NYSE": "EPRT.NYSE",
    "EB.NYSE": "EB.NYSE",
    "BOX.NYSE": "BOX.NYSE",
    "MTDR.NYSE": "MTDR.NYSE",
    "PEB.NYSE": "PEB.NYSE",
    "FLO.NYSE": "FLO.NYSE",
    "DAN.NYSE": "DAN.NYSE",
    "BSAC.NYSE": "BSAC.NYSE",
    "STWD.NYSE": "STWD.NYSE",
    "LEVI.NYSE": "LEVI.NYSE",
    "MD.NYSE": "MD.NYSE",
    "CNO.NYSE": "CNO.NYSE",
    "DDD.NYSE": "DDD.NYSE",
    "BE.NYSE": "BE.NYSE",
    "HOME.NYSE": "HOME.NYSE",
    "CLR.NYSE": "CLR.NYSE",
    "TUP.NYSE": "TUP.NYSE",
    "MX.NYSE": "MX.NYSE",
    "HP.NYSE": "HP.NYSE",
    "ELF.NYSE": "ELF.NYSE",
    "AQUA.NYSE": "AQUA.NYSE",
    "OFC.NYSE": "OFC.NYSE",
    "WRI.NYSE": "WRI.NYSE",
    "SKM.NYSE": "SKM.NYSE",
    "FTAI.NYSE": "FTAI.NYSE",
    "HPP.NYSE": "HPP.NYSE",
    "NOMD.NYSE": "NOMD.NYSE",
    "FCPT.NYSE": "FCPT.NYSE",
    "HTA.NYSE": "HTA.NYSE",
    "EQC.NYSE": "EQC.NYSE",
    "CWEN.NYSE": "CWEN.NYSE",
    "HUN.NYSE": "HUN.NYSE",
    "ZTO.NYSE": "ZTO.NYSE",
    "CC.NYSE": "CC.NYSE",
    "PBA.NYSE": "PBA.NYSE",
    "GTY.NYSE": "GTY.NYSE",
    "MTOR.NYSE": "MTOR.NYSE",
    "MDLA.NYSE": "MDLA.NYSE",
    "SPCE.NYSE": "SPCE.NYSE",
    "HMC.NYSE": "HMC.NYSE",
    "HSBC.NYSE": "HSBC.NYSE",
    "AXTA.NYSE": "AXTA.NYSE",
    "VIPS.NYSE": "VIPS.NYSE",
    "AVTR.NYSE": "AVTR.NYSE",
    "JEF.NYSE": "JEF.NYSE",
    "AEO.NYSE": "AEO.NYSE",
    "MDP.NYSE": "MDP.NYSE",
    "HR.NYSE": "HR.NYSE",
    "CMC.NYSE": "CMC.NYSE",
    "BXMT.NYSE": "BXMT.NYSE",
    "MDU.NYSE": "MDU.NYSE",
    "TRGP.NYSE": "TRGP.NYSE",
    "AA.NYSE": "AA.NYSE",
    "TMHC.NYSE": "TMHC.NYSE",
    "LRN.NYSE": "LRN.NYSE",
    "VSTO.NYSE": "VSTO.NYSE",
    "BXS.NYSE": "BXS.NYSE",
    "JBGS.NYSE": "JBGS.NYSE",
    "DEI.NYSE": "DEI.NYSE",
    "AAT.NYSE": "AAT.NYSE",
    "WLL.NYSE": "WLL.NYSE",
    "EGHT.NYSE": "EGHT.NYSE",
    "ASAN.NYSE": "ASAN.NYSE",
    "STOR.NYSE": "STOR.NYSE",
    "AMH.NYSE": "AMH.NYSE",
    "MMI.NYSE": "MMI.NYSE",
    "STAG.NYSE": "STAG.NYSE",
    "MXL.NYSE": "MXL.NYSE",
    "LPI.NYSE": "LPI.NYSE",
    "CUZ.NYSE": "CUZ.NYSE",
    "UNFI.NYSE": "UNFI.NYSE",
    "JWN.NYSE": "JWN.NYSE",
    "CPE.NYSE": "CPE.NYSE",
    "ANF.NYSE": "ANF.NYSE",
    "TPX.NYSE": "TPX.NYSE",
    "JMIA.NYSE": "JMIA.NYSE",
    "KBR.NYSE": "KBR.NYSE",
    "OMI.NYSE": "OMI.NYSE",
    "MAXR.NYSE": "MAXR.NYSE",
    "HGV.NYSE": "HGV.NYSE",
    "SAVE.NYSE": "SAVE.NYSE",
    "PLT.NYSE": "PLT.NYSE",
    "NIO.NYSE": "NIO.NYSE",
    "BTI.NYSE": "BTI.NYSE",
    "USFD.NYSE": "USFD.NYSE",
    "NVTA.NYSE": "NVTA.NYSE",
    "OHI.NYSE": "OHI.NYSE",
    "NCR.NYSE": "NCR.NYSE",
    "ARMK.NYSE": "ARMK.NYSE",
    "GVA.NYSE": "GVA.NYSE",
    "EPC.NYSE": "EPC.NYSE",
    "CUBE.NYSE": "CUBE.NYSE",
    "COLD.NYSE": "COLD.NYSE",
    "TX.NYSE": "TX.NYSE",
    "OLN.NYSE": "OLN.NYSE",
    "ATGE.NYSE": "ATGE.NYSE",
    "TDC.NYSE": "TDC.NYSE",
    "YELP.NYSE": "YELP.NYSE",
    "HOG.NYSE": "HOG.NYSE",
    "VER.NYSE": "VER.NYSE",
    "NSA.NYSE": "NSA.NYSE",
    "MAIN.NYSE": "MAIN.NYSE",
    "RMAX.NYSE": "RMAX.NYSE",
    "WORK.NYSE": "WORK.NYSE",
    "PD.NYSE": "PD.NYSE",
    "UGI.NYSE": "UGI.NYSE",
    "KMT.NYSE": "KMT.NYSE",
    "VVI.NYSE": "VVI.NYSE",
    "JOE.NYSE": "JOE.NYSE",
    "PRG.NYSE": "PRG.NYSE",
    "HIW.NYSE": "HIW.NYSE",
    "SKX.NYSE": "SKX.NYSE",
    "LTC.NYSE": "LTC.NYSE",
    "NAV.NYSE": "NAV.NYSE",
    "ACC.NYSE": "ACC.NYSE",
    "BDC.NYSE": "BDC.NYSE",
    "ARCH.NYSE": "ARCH.NYSE",
    "HLF.NYSE": "HLF.NYSE",
    "BAM.NYSE": "BAM.NYSE",
    "NNN.NYSE": "NNN.NYSE",
    "BJ.NYSE": "BJ.NYSE",
    "LAZ.NYSE": "LAZ.NYSE",
    "FR.NYSE": "FR.NYSE",
    "DEN.NYSE": "DEN.NYSE",
    "SIX.NYSE": "SIX.NYSE",
    "AJRD.NYSE": "AJRD.NYSE",
    "ENR.NYSE": "ENR.NYSE",
    "RVLV.NYSE": "RVLV.NYSE",
    "GDOT.NYSE": "GDOT.NYSE",
    "PAGS.NYSE": "PAGS.NYSE",
    "ESNT.NYSE": "ESNT.NYSE",
    "AMRC.NYSE": "AMRC.NYSE",
    "TMX.NYSE": "TMX.NYSE",
    "SPR.NYSE": "SPR.NYSE",
    "KBH.NYSE": "KBH.NYSE",
    "EPR.NYSE": "EPR.NYSE",
    "NYT.NYSE": "NYT.NYSE",
    "SAH.NYSE": "SAH.NYSE",
    "KNX.NYSE": "KNX.NYSE",
    "CPRI.NYSE": "CPRI.NYSE",
    "THC.NYSE": "THC.NYSE",
    "FTCH.NYSE": "FTCH.NYSE",
    "CIT.NYSE": "CIT.NYSE",
    "ABM.NYSE": "ABM.NYSE",
    "SCI.NYSE": "SCI.NYSE",
    "NUS.NYSE": "NUS.NYSE",
    "CCEP.NYSE": "CCEP.NYSE",
    "ARGO.NYSE": "ARGO.NYSE",
    "REXR.NYSE": "REXR.NYSE",
    "THS.NYSE": "THS.NYSE",
    "JBL.NYSE": "JBL.NYSE",
    "HASI.NYSE": "HASI.NYSE",
    "SAIL.NYSE": "SAIL.NYSE",
    "BIP.NYSE": "BIP.NYSE",
    "WWE.NYSE": "WWE.NYSE",
    "CIEN.NYSE": "CIEN.NYSE",
    "FL.NYSE": "FL.NYSE",
    "HXL.NYSE": "HXL.NYSE",
    "GEF.NYSE": "GEF.NYSE",
    "PFGC.NYSE": "PFGC.NYSE",
    "FAF.NYSE": "FAF.NYSE",
    "DCI.NYSE": "DCI.NYSE",
    "UVV.NYSE": "UVV.NYSE",
    "TOL.NYSE": "TOL.NYSE",
    "AER.NYSE": "AER.NYSE",
    "LPX.NYSE": "LPX.NYSE",
    "TRNO.NYSE": "TRNO.NYSE",
    "KSS.NYSE": "KSS.NYSE",
    "MDC.NYSE": "MDC.NYSE",
    "XEC.NYSE": "XEC.NYSE",
    "NEWR.NYSE": "NEWR.NYSE",
    "BYD.NYSE": "BYD.NYSE",
    "BERY.NYSE": "BERY.NYSE",
    "GMED.NYSE": "GMED.NYSE",
    "GRA.NYSE": "GRA.NYSE",
    "BUD.NYSE": "BUD.NYSE",
    "SON.NYSE": "SON.NYSE",
    "GRUB.NYSE": "GRUB.NYSE",
    "BOOT.NYSE": "BOOT.NYSE",
    "ACM.NYSE": "ACM.NYSE",
    "KRC.NYSE": "KRC.NYSE",
    "BIG.NYSE": "BIG.NYSE",
    "ADC.NYSE": "ADC.NYSE",
    "EAT.NYSE": "EAT.NYSE",
    "SAFE.NYSE": "SAFE.NYSE",
    "UHT.NYSE": "UHT.NYSE",
    "ONTO.NYSE": "ONTO.NYSE",
    "NEP.NYSE": "NEP.NYSE",
    "ENV.NYSE": "ENV.NYSE",
    "YETI.NYSE": "YETI.NYSE",
    "ORA.NYSE": "ORA.NYSE",
    "R.NYSE": "R.NYSE",
    "SXT.NYSE": "SXT.NYSE",
    "GKOS.NYSE": "GKOS.NYSE",
    "BCO.NYSE": "BCO.NYSE",
    "PAG.NYSE": "PAG.NYSE",
    "EHC.NYSE": "EHC.NYSE",
    "DKS.NYSE": "DKS.NYSE",
    "EBS.NYSE": "EBS.NYSE",
    "CHWY.NYSE": "CHWY.NYSE",
    "WGO.NYSE": "WGO.NYSE",
    "CPA.NYSE": "CPA.NYSE",
    "PLNT.NYSE": "PLNT.NYSE",
    "GIB.NYSE": "GIB.NYSE",
    "AYX.NYSE": "AYX.NYSE",
    "NSP.NYSE": "NSP.NYSE",
    "H.NYSE": "H.NYSE",
    "AIN.NYSE": "AIN.NYSE",
    "WCC.NYSE": "WCC.NYSE",
    "NVS.NYSE": "NVS.NYSE",
    "CHGG.NYSE": "CHGG.NYSE",
    "LSI.NYSE": "LSI.NYSE",
    "SPB.NYSE": "SPB.NYSE",
    "DIN.NYSE": "DIN.NYSE",
    "ASH.NYSE": "ASH.NYSE",
    "INGR.NYSE": "INGR.NYSE",
    "AN.NYSE": "AN.NYSE",
    "LMND.NYSE": "LMND.NYSE",
    "DELL.NYSE": "DELL.NYSE",
    "CRI.NYSE": "CRI.NYSE",
    "MTH.NYSE": "MTH.NYSE",
    "ENS.NYSE": "ENS.NYSE",
    "NBR.NYSE": "NBR.NYSE",
    "ATHM.NYSE": "ATHM.NYSE",
    "MTZ.NYSE": "MTZ.NYSE",
    "BMI.NYSE": "BMI.NYSE",
    "DDS.NYSE": "DDS.NYSE",
    "BC.NYSE": "BC.NYSE",
    "U.NYSE": "U.NYSE",
    "IDA.NYSE": "IDA.NYSE",
    "USNA.NYSE": "USNA.NYSE",
    "HHC.NYSE": "HHC.NYSE",
    "QTWO.NYSE": "QTWO.NYSE",
    "HRC.NYSE": "HRC.NYSE",
    "BFH.NYSE": "BFH.NYSE",
    "ARW.NYSE": "ARW.NYSE",
    "HAE.NYSE": "HAE.NYSE",
    "EME.NYSE": "EME.NYSE",
    "SHAK.NYSE": "SHAK.NYSE",
    "AFG.NYSE": "AFG.NYSE",
    "IBP.NYSE": "IBP.NYSE",
    "OSK.NYSE": "OSK.NYSE",
    "SNX.NYSE": "SNX.NYSE",
    "COR.NYSE": "COR.NYSE",
    "RL.NYSE": "RL.NYSE",
    "DASH.NYSE": "DASH.NYSE",
    "RGA.NYSE": "RGA.NYSE",
    "CNMD.NYSE": "CNMD.NYSE",
    "THG.NYSE": "THG.NYSE",
    "THO.NYSE": "THO.NYSE",
    "PII.NYSE": "PII.NYSE",
    "ZEN.NYSE": "ZEN.NYSE",
    "JBT.NYSE": "JBT.NYSE",
    "FCN.NYSE": "FCN.NYSE",
    "NVRO.NYSE": "NVRO.NYSE",
    "MUSA.NYSE": "MUSA.NYSE",
    "AGCO.NYSE": "AGCO.NYSE",
    "EGP.NYSE": "EGP.NYSE",
    "AMG.NYSE": "AMG.NYSE",
    "RS.NYSE": "RS.NYSE",
    "GPI.NYSE": "GPI.NYSE",
    "RNR.NYSE": "RNR.NYSE",
    "AYI.NYSE": "AYI.NYSE",
    "VAC.NYSE": "VAC.NYSE",
    "WSM.NYSE": "WSM.NYSE",
    "JLL.NYSE": "JLL.NYSE",
    "LEA.NYSE": "LEA.NYSE",
    "MSGS.NYSE": "MSGS.NYSE",
    "HUBB.NYSE": "HUBB.NYSE",
    "IIPR.NYSE": "IIPR.NYSE",
    "INSP.NYSE": "INSP.NYSE",
    "WEX.NYSE": "WEX.NYSE",
    "MED.NYSE": "MED.NYSE",
    "FVRR.NYSE": "FVRR.NYSE",
    "VEEV.NYSE": "VEEV.NYSE",
    "WSO.NYSE": "WSO.NYSE",
    "PEN.NYSE": "PEN.NYSE",
    "ALX.NYSE": "ALX.NYSE",
    "RNG.NYSE": "RNG.NYSE",
    "BURL.NYSE": "BURL.NYSE",
    "DECK.NYSE": "DECK.NYSE",
    "CHE.NYSE": "CHE.NYSE",
    "GHC.NYSE": "GHC.NYSE",
    "Y.NYSE": "Y.NYSE",
    "SHOP.NYSE": "SHOP.NYSE",
    "MAN.NYSE": "MAN.NYSE",
    "MAC.NYSE": "MAC.NYSE",
    "QTS.NYSE": "QTS.NYSE",
    "TAL.NYSE": "TAL.NYSE",
    "DBA.NYSE": "DBA.NYSE",
    "EEM.NYSE": "EEM.NYSE",
    "EWH.NYSE": "EWH.NYSE",
    "EWW.NYSE": "EWW.NYSE",
    "EWZ.NYSE": "EWZ.NYSE",
    "FXI.NYSE": "FXI.NYSE",
    "GDX.NYSE": "GDX.NYSE",
    "GDXJ.NYSE": "GDXJ.NYSE",
    "IEMG.NYSE": "IEMG.NYSE",
    "LQD.NYSE": "LQD.NYSE",
    "MJ.NYSE": "MJ.NYSE",
    "MOO.NYSE": "MOO.NYSE",
    "SIL.NYSE": "SIL.NYSE",
    "UNG.NYSE": "UNG.NYSE",
    "URA.NYSE": "URA.NYSE",
    "USO.NYSE": "USO.NYSE",
    "VYM.NYSE": "VYM.NYSE",
    "XLE.NYSE": "XLE.NYSE",
    "XLF.NYSE": "XLF.NYSE",
    "XLI.NYSE": "XLI.NYSE",
    "XLP.NYSE": "XLP.NYSE",
    "XLU.NYSE": "XLU.NYSE",
    "XOP.NYSE": "XOP.NYSE"
};

console.log('All Stocks:', Object.keys(orig).length)

let wehave = {
    "AMC.ASX":"AMC.ASX",
    "AMP.ASX":"AMP.ASX",
    "ANZ.ASX":"ANZ.ASX",
    "BHP.ASX":"BHP.ASX",
    "BXB.ASX":"BXB.ASX",
    "CBA.ASX":"CBA.ASX",
    "CSL.ASX":"CSL.ASX",
    "FMG.ASX":"FMG.ASX",
    "IAG.ASX":"IAG.ASX",
    "MQG.ASX":"MQG.ASX",
    "NAB.ASX":"NAB.ASX",
    "QBE.ASX":"QBE.ASX",
    "RIO.ASX":"RIO.ASX",
    "SCG.ASX":"SCG.ASX",
    "SUN.ASX":"SUN.ASX",
    "TCL.ASX":"TCL.ASX",
    "TLS.ASX":"TLS.ASX",
    "WBC.ASX":"WBC.ASX",
    "WES.ASX":"WES.ASX",
    "WOW.ASX":"WOW.ASX",
    "WPL.ASX":"WPL.ASX",
    "A.NYSE":"A.NYSE",
    "AA.NYSE":"AA.NYSE",
    "AAP.NYSE":"AAP.NYSE",
    "AAT.NYSE":"AAT.NYSE",
    "ABBV.NYSE":"ABBV.NYSE",
    "ABC.NYSE":"ABC.NYSE",
    "ABEV.NYSE":"ABEV.NYSE",
    "ABM.NYSE":"ABM.NYSE",
    "ABR.NYSE":"ABR.NYSE",
    "ABT.NYSE":"ABT.NYSE",
    "ACB.NYSE":"ACB.NYSE",
    "ACC.NYSE":"ACC.NYSE",
    "ACM.NYSE":"ACM.NYSE",
    "ACN.NYSE":"ACN.NYSE",
    "ADC.NYSE":"ADC.NYSE",
    "ADM.NYSE":"ADM.NYSE",
    "BFH.NYSE":"BFH.NYSE",
    "ADT.NYSE":"ADT.NYSE",
    "AEE.NYSE":"AEE.NYSE",
    "AEO.NYSE":"AEO.NYSE",
    "AER.NYSE":"AER.NYSE",
    "AES.NYSE":"AES.NYSE",
    "AFG.NYSE":"AFG.NYSE",
    "AFL.NYSE":"AFL.NYSE",
    "AG.NYSE":"AG.NYSE",
    "AGCO.NYSE":"AGCO.NYSE",
    "AGN.NYSE":"AGN.NYSE",
    "AGR.NYSE":"AGR.NYSE",
    "AGRO.NYSE":"AGRO.NYSE",
    "AIG.NYSE":"AIG.NYSE",
    "AIN.NYSE":"AIN.NYSE",
    "AIV.NYSE":"AIV.NYSE",
    "AIZ.NYSE":"AIZ.NYSE",
    "AJG.NYSE":"AJG.NYSE",
    "AJRD.NYSE":"AJRD.NYSE",
    "AKR.NYSE":"AKR.NYSE",
    "ALB.NYSE":"ALB.NYSE",
    "ALK.NYSE":"ALK.NYSE",
    "ALL.NYSE":"ALL.NYSE",
    "ALLE.NYSE":"ALLE.NYSE",
    "ALLY.NYSE":"ALLY.NYSE",
    "ALX.NYSE":"ALX.NYSE",
    "AM.NYSE":"AM.NYSE",
    "AMCR.NYSE":"AMCR.NYSE",
    "AME.NYSE":"AME.NYSE",
    "AMG.NYSE":"AMG.NYSE",
    "AMH.NYSE":"AMH.NYSE",
    "AMP.NYSE":"AMP.NYSE",
    "AMRC.NYSE":"AMRC.NYSE",
    "AMRX.NYSE":"AMRX.NYSE",
    "AMT.NYSE":"AMT.NYSE",
    "AMWL.NYSE":"AMWL.NYSE",
    "AMX.NYSE":"AMX.NYSE",
    "AN.NYSE":"AN.NYSE",
    "ANET.NYSE":"ANET.NYSE",
    "ANF.NYSE":"ANF.NYSE",
    "ANTM.NYSE":"ANTM.NYSE",
    "AON.NYSE":"AON.NYSE",
    "AOS.NYSE":"AOS.NYSE",
    "APD.NYSE":"APD.NYSE",
    "APH.NYSE":"APH.NYSE",
    "APO.NYSE":"APO.NYSE",
    "APTV.NYSE":"APTV.NYSE",
    "AQUA.NYSE":"AQUA.NYSE",
    "AR.NYSE":"AR.NYSE",
    "ARCH.NYSE":"ARCH.NYSE",
    "ARCO.NYSE":"ARCO.NYSE",
    "ARE.NYSE":"ARE.NYSE",
    "ARGO.NYSE":"ARGO.NYSE",
    "ARMK.NYSE":"ARMK.NYSE",
    "AROC.NYSE":"AROC.NYSE",
    "ARR.NYSE":"ARR.NYSE",
    "ARW.NYSE":"ARW.NYSE",
    "ASAN.NYSE":"ASAN.NYSE",
    "ASH.NYSE":"ASH.NYSE",
    "ATGE.NYSE":"ATGE.NYSE",
    "ATHM.NYSE":"ATHM.NYSE",
    "ATI.NYSE":"ATI.NYSE",
    "ATO.NYSE":"ATO.NYSE",
    "ATUS.NYSE":"ATUS.NYSE",
    "AU.NYSE":"AU.NYSE",
    "AUY.NYSE":"AUY.NYSE",
    "AVB.NYSE":"AVB.NYSE",
    "AVLR.NYSE":"AVLR.NYSE",
    "AVTR.NYSE":"AVTR.NYSE",
    "AVY.NYSE":"AVY.NYSE",
    "AWK.NYSE":"AWK.NYSE",
    "AXL.NYSE":"AXL.NYSE",
    "AXP.NYSE":"AXP.NYSE",
    "AXTA.NYSE":"AXTA.NYSE",
    "AYI.NYSE":"AYI.NYSE",
    "AYX.NYSE":"AYX.NYSE",
    "AZO.NYSE":"AZO.NYSE",
    "AZUL.NYSE":"AZUL.NYSE",
    "BA.NYSE":"BA.NYSE",
    "BABA.NYSE":"BABA.NYSE",
    "BAC.NYSE":"BAC.NYSE",
    "BAH.NYSE":"BAH.NYSE",
    "BAM.NYSE":"BAM.NYSE",
    "BAX.NYSE":"BAX.NYSE",
    "BB.NYSE":"BB.NYSE",
    "BBAR.NYSE":"BBAR.NYSE",
    "BBD.NYSE":"BBD.NYSE",
    "BBY.NYSE":"BBY.NYSE",
    "BC.NYSE":"BC.NYSE",
    "BCO.NYSE":"BCO.NYSE",
    "BCS.NYSE":"BCS.NYSE",
    "BDC.NYSE":"BDC.NYSE",
    "BDJ.NYSE":"BDJ.NYSE",
    "BDN.NYSE":"BDN.NYSE",
    "BDX.NYSE":"BDX.NYSE",
    "BE.NYSE":"BE.NYSE",
    "BEN.NYSE":"BEN.NYSE",
    "BERY.NYSE":"BERY.NYSE",
    "BEST.NYSE":"BEST.NYSE",
    "BF/B.NYSE":"BF/B.NYSE",
    "BFAM.NYSE":"BFAM.NYSE",
    "BG.NYSE":"BG.NYSE",
    "BIG.NYSE":"BIG.NYSE",
    "BIO.NYSE":"BIO.NYSE",
    "BIP.NYSE":"BIP.NYSE",
    "BJ.NYSE":"BJ.NYSE",
    "BK.NYSE":"BK.NYSE",
    "BKD.NYSE":"BKD.NYSE",
    "BKR.NYSE":"BKR.NYSE",
    "BLK.NYSE":"BLK.NYSE",
    "BLL.NYSE":"BLL.NYSE",
    "BMI.NYSE":"BMI.NYSE",
    "BMY.NYSE":"BMY.NYSE",
    "BOOT.NYSE":"BOOT.NYSE",
    "BOX.NYSE":"BOX.NYSE",
    "BR.NYSE":"BR.NYSE",
    "BRFS.NYSE":"BRFS.NYSE",
    "BRK-B.NYSE":"BRK-B.NYSE",
    "BRO.NYSE":"BRO.NYSE",
    "BRX.NYSE":"BRX.NYSE",
    "BSAC.NYSE":"BSAC.NYSE",
    "BSX.NYSE":"BSX.NYSE",
    "BTI.NYSE":"BTI.NYSE",
    "BUD.NYSE":"BUD.NYSE",
    "BURL.NYSE":"BURL.NYSE",
    "BW.NYSE":"BW.NYSE",
    "BWA.NYSE":"BWA.NYSE",
    "BX.NYSE":"BX.NYSE",
    "BXMT.NYSE":"BXMT.NYSE",
    "BXP.NYSE":"BXP.NYSE",
    "BXS.NYSE":"BXS.NYSE",
    "BYD.NYSE":"BYD.NYSE",
    "C.NYSE":"C.NYSE",
    "CADE.NYSE":"CADE.NYSE",
    "CAG.NYSE":"CAG.NYSE",
    "CAH.NYSE":"CAH.NYSE",
    "CAL.NYSE":"CAL.NYSE",
    "CARR.NYSE":"CARR.NYSE",
    "CARS.NYSE":"CARS.NYSE",
    "CAT.NYSE":"CAT.NYSE",
    "CB.NYSE":"CB.NYSE",
    "CBB.NYSE":"CBB.NYSE",
    "CBD.NYSE":"CBD.NYSE",
    "CBRE.NYSE":"CBRE.NYSE",
    "CC.NYSE":"CC.NYSE",
    "CCEP.NYSE":"CCEP.NYSE",
    "CCI.NYSE":"CCI.NYSE",
    "CCIV.NYSE":"CCIV.NYSE",
    "CCJ.NYSE":"CCJ.NYSE",
    "CCK.NYSE":"CCK.NYSE",
    "CCL.NYSE":"CCL.NYSE",
    "CCU.NYSE":"CCU.NYSE",
    "CDAY.NYSE":"CDAY.NYSE",
    "CDE.NYSE":"CDE.NYSE",
    "CE.NYSE":"CE.NYSE",
    "CEN.NYSE":"CEN.NYSE",
    "CF.NYSE":"CF.NYSE",
    "CFG.NYSE":"CFG.NYSE",
    "CGC.NYSE":"CGC.NYSE",
    "CHD.NYSE":"CHD.NYSE",
    "CHE.NYSE":"CHE.NYSE",
    "CHGG.NYSE":"CHGG.NYSE",
    "CHS.NYSE":"CHS.NYSE",
    "CHWY.NYSE":"CHWY.NYSE",
    "CI.NYSE":"CI.NYSE",
    "CIEN.NYSE":"CIEN.NYSE",
    "CIG.NYSE":"CIG.NYSE",
    "CIM.NYSE":"CIM.NYSE",
    "CIT.NYSE":"CIT.NYSE",
    "CL.NYSE":"CL.NYSE",
    "CLDR.NYSE":"CLDR.NYSE",
    "CLDT.NYSE":"CLDT.NYSE",
    "CLF.NYSE":"CLF.NYSE",
    "CLI.NYSE":"CLI.NYSE",
    "CLNY.NYSE":"CLNY.NYSE",
    "CLR.NYSE":"CLR.NYSE",
    "CLX.NYSE":"CLX.NYSE",
    "CMA.NYSE":"CMA.NYSE",
    "CMC.NYSE":"CMC.NYSE",
    "CMG.NYSE":"CMG.NYSE",
    "CMI.NYSE":"CMI.NYSE",
    "CMRE.NYSE":"CMRE.NYSE",
    "CMS.NYSE":"CMS.NYSE",
    "CNC.NYSE":"CNC.NYSE",
    "CNK.NYSE":"CNK.NYSE",
    "CNMD.NYSE":"CNMD.NYSE",
    "CNO.NYSE":"CNO.NYSE",
    "CNP.NYSE":"CNP.NYSE",
    "CNX.NYSE":"CNX.NYSE",
    "CO.NYSE":"CO.NYSE",
    "COF.NYSE":"COF.NYSE",
    "COG.NYSE":"COG.NYSE",
    "COLD.NYSE":"COLD.NYSE",
    "COO.NYSE":"COO.NYSE",
    "COP.NYSE":"COP.NYSE",
    "COR.NYSE":"COR.NYSE",
    "CORR.NYSE":"CORR.NYSE",
    "COTY.NYSE":"COTY.NYSE",
    "CPA.NYSE":"CPA.NYSE",
    "CPB.NYSE":"CPB.NYSE",
    "CPE.NYSE":"CPE.NYSE",
    "CPRI.NYSE":"CPRI.NYSE",
    "CPT.NYSE":"CPT.NYSE",
    "CRI.NYSE":"CRI.NYSE",
    "CRK.NYSE":"CRK.NYSE",
    "CRL.NYSE":"CRL.NYSE",
    "CRM.NYSE":"CRM.NYSE",
    "CTLT.NYSE":"CTLT.NYSE",
    "CTT.NYSE":"CTT.NYSE",
    "CTVA.NYSE":"CTVA.NYSE",
    "CUBE.NYSE":"CUBE.NYSE",
    "CUK.NYSE":"CUK.NYSE",
    "CUZ.NYSE":"CUZ.NYSE",
    "CVA.NYSE":"CVA.NYSE",
    "CVI.NYSE":"CVI.NYSE",
    "CVNA.NYSE":"CVNA.NYSE",
    "CVS.NYSE":"CVS.NYSE",
    "CVX.NYSE":"CVX.NYSE",
    "CWEN.NYSE":"CWEN.NYSE",
    "CX.NYSE":"CX.NYSE",
    "CXP.NYSE":"CXP.NYSE",
    "CYH.NYSE":"CYH.NYSE",
    "D.NYSE":"D.NYSE",
    "DAL.NYSE":"DAL.NYSE",
    "DAN.NYSE":"DAN.NYSE",
    "DAR.NYSE":"DAR.NYSE",
    "DASH.NYSE":"DASH.NYSE",
    "DB.NYSE":"DB.NYSE",
    "DBA.NYSE":"DBA.NYSE",
    "DBD.NYSE":"DBD.NYSE",
    "DBI.NYSE":"DBI.NYSE",
    "DCI.NYSE":"DCI.NYSE",
    "DD.NYSE":"DD.NYSE",
    "DDD.NYSE":"DDD.NYSE",
    "DDS.NYSE":"DDS.NYSE",
    "DE.NYSE":"DE.NYSE",
    "DECK.NYSE":"DECK.NYSE",
    "DEI.NYSE":"DEI.NYSE",
    "DELL.NYSE":"DELL.NYSE",
    "DEN.NYSE":"DEN.NYSE",
    "DEO.NYSE":"DEO.NYSE",
    "DFS.NYSE":"DFS.NYSE",
    "DG.NYSE":"DG.NYSE",
    "DGX.NYSE":"DGX.NYSE",
    "DHI.NYSE":"DHI.NYSE",
    "DHR.NYSE":"DHR.NYSE",
    "DHT.NYSE":"DHT.NYSE",
    "DIN.NYSE":"DIN.NYSE",
    "DIS.NYSE":"DIS.NYSE",
    "DK.NYSE":"DK.NYSE",
    "DKS.NYSE":"DKS.NYSE",
    "DLR.NYSE":"DLR.NYSE",
    "DNOW.NYSE":"DNOW.NYSE",
    "DOV.NYSE":"DOV.NYSE",
    "DOW.NYSE":"DOW.NYSE",
    "DPZ.NYSE":"DPZ.NYSE",
    "DRE.NYSE":"DRE.NYSE",
    "DRH.NYSE":"DRH.NYSE",
    "DRI.NYSE":"DRI.NYSE",
    "DS.NYSE":"DS.NYSE",
    "DT.NYSE":"DT.NYSE",
    "DTE.NYSE":"DTE.NYSE",
    "DUK.NYSE":"DUK.NYSE",
    "DVA.NYSE":"DVA.NYSE",
    "DVN.NYSE":"DVN.NYSE",
    "DX.NYSE":"DX.NYSE",
    "DXC.NYSE":"DXC.NYSE",
    "EAT.NYSE":"EAT.NYSE",
    "EB.NYSE":"EB.NYSE",
    "EBS.NYSE":"EBS.NYSE",
    "EC.NYSE":"EC.NYSE",
    "ECL.NYSE":"ECL.NYSE",
    "ED.NYSE":"ED.NYSE",
    "EDU.NYSE":"EDU.NYSE",
    "EEM.NYSE":"EEM.NYSE",
    "EFX.NYSE":"EFX.NYSE",
    "EGHT.NYSE":"EGHT.NYSE",
    "EGO.NYSE":"EGO.NYSE",
    "EGP.NYSE":"EGP.NYSE",
    "EHC.NYSE":"EHC.NYSE",
    "EIX.NYSE":"EIX.NYSE",
    "EL.NYSE":"EL.NYSE",
    "ELAN.NYSE":"ELAN.NYSE",
    "ELF.NYSE":"ELF.NYSE",
    "ELS.NYSE":"ELS.NYSE",
    "EME.NYSE":"EME.NYSE",
    "EMN.NYSE":"EMN.NYSE",
    "EMR.NYSE":"EMR.NYSE",
    "ENBL.NYSE":"ENBL.NYSE",
    "ENR.NYSE":"ENR.NYSE",
    "ENS.NYSE":"ENS.NYSE",
    "ENV.NYSE":"ENV.NYSE",
    "EOG.NYSE":"EOG.NYSE",
    "EPAM.NYSE":"EPAM.NYSE",
    "EPC.NYSE":"EPC.NYSE",
    "EPD.NYSE":"EPD.NYSE",
    "EPR.NYSE":"EPR.NYSE",
    "EPRT.NYSE":"EPRT.NYSE",
    "EQC.NYSE":"EQC.NYSE",
    "EQH.NYSE":"EQH.NYSE",
    "EQNR.NYSE":"EQNR.NYSE",
    "EQR.NYSE":"EQR.NYSE",
    "EQT.NYSE":"EQT.NYSE",
    "ES.NYSE":"ES.NYSE",
    "ESGC.NYSE":"ESGC.NYSE",
    "ESNT.NYSE":"ESNT.NYSE",
    "ESRT.NYSE":"ESRT.NYSE",
    "ESS.NYSE":"ESS.NYSE",
    "ESTC.NYSE":"ESTC.NYSE",
    "ET.NYSE":"ET.NYSE",
    "ETN.NYSE":"ETN.NYSE",
    "ETR.NYSE":"ETR.NYSE",
    "EVRG.NYSE":"EVRG.NYSE",
    "EVRI.NYSE":"EVRI.NYSE",
    "EW.NYSE":"EW.NYSE",
    "EWH.NYSE":"EWH.NYSE",
    "EWW.NYSE":"EWW.NYSE",
    "EWZ.NYSE":"EWZ.NYSE",
    "EXK.NYSE":"EXK.NYSE",
    "EXR.NYSE":"EXR.NYSE",
    "F.NYSE":"F.NYSE",
    "FAF.NYSE":"FAF.NYSE",
    "FBHS.NYSE":"FBHS.NYSE",
    "FBP.NYSE":"FBP.NYSE",
    "FCN.NYSE":"FCN.NYSE",
    "FCPT.NYSE":"FCPT.NYSE",
    "FCX.NYSE":"FCX.NYSE",
    "FDS.NYSE":"FDS.NYSE",
    "FDX.NYSE":"FDX.NYSE",
    "FE.NYSE":"FE.NYSE",
    "FI.NYSE":"FI.NYSE",
    "FICO.NYSE":"FICO.NYSE",
    "FIS.NYSE":"FIS.NYSE",
    "FL.NYSE":"FL.NYSE",
    "FLO.NYSE":"FLO.NYSE",
    "FLR.NYSE":"FLR.NYSE",
    "FLS.NYSE":"FLS.NYSE",
    "FLT.NYSE":"FLT.NYSE",
    "FMC.NYSE":"FMC.NYSE",
    "FNF.NYSE":"FNF.NYSE",
    "FPI.NYSE":"FPI.NYSE",
    "FR.NYSE":"FR.NYSE",
    "FRC.NYSE":"FRC.NYSE",
    "FRT.NYSE":"FRT.NYSE",
    "FSK.NYSE":"FSK.NYSE",
    "FSM.NYSE":"FSM.NYSE",
    "FSR.NYSE":"FSR.NYSE",
    "FTAI.NYSE":"FTAI.NYSE",
    "FTCH.NYSE":"FTCH.NYSE",
    "FTI.NYSE":"FTI.NYSE",
    "FTV.NYSE":"FTV.NYSE",
    "FVRR.NYSE":"FVRR.NYSE",
    "FXI.NYSE":"FXI.NYSE",
    "GCI.NYSE":"GCI.NYSE",
    "GD.NYSE":"GD.NYSE",
    "GDDY.NYSE":"GDDY.NYSE",
    "GDOT.NYSE":"GDOT.NYSE",
    "GDX.NYSE":"GDX.NYSE",
    "GDXJ.NYSE":"GDXJ.NYSE",
    "GE.NYSE":"GE.NYSE",
    "GEF.NYSE":"GEF.NYSE",
    "GEL.NYSE":"GEL.NYSE",
    "GEO.NYSE":"GEO.NYSE",
    "GFI.NYSE":"GFI.NYSE",
    "GGB.NYSE":"GGB.NYSE",
    "GHC.NYSE":"GHC.NYSE",
    "GIB.NYSE":"GIB.NYSE",
    "GIS.NYSE":"GIS.NYSE",
    "GKOS.NYSE":"GKOS.NYSE",
    "GL.NYSE":"GL.NYSE",
    "GLOG.NYSE":"GLOG.NYSE",
    "GLP.NYSE":"GLP.NYSE",
    "GLW.NYSE":"GLW.NYSE",
    "GM.NYSE":"GM.NYSE",
    "GMED.NYSE":"GMED.NYSE",
    "GMRE.NYSE":"GMRE.NYSE",
    "GNL.NYSE":"GNL.NYSE",
    "GNRC.NYSE":"GNRC.NYSE",
    "GNW.NYSE":"GNW.NYSE",
    "GOL.NYSE":"GOL.NYSE",
    "GOLD.NYSE":"GOLD.NYSE",
    "GPI.NYSE":"GPI.NYSE",
    "GPK.NYSE":"GPK.NYSE",
    "GPN.NYSE":"GPN.NYSE",
    "GPS.NYSE":"GPS.NYSE",
    "GRA.NYSE":"GRA.NYSE",
    "GRUB.NYSE":"GRUB.NYSE",
    "GS.NYSE":"GS.NYSE",
    "GTN.NYSE":"GTN.NYSE",
    "GTY.NYSE":"GTY.NYSE",
    "GVA.NYSE":"GVA.NYSE",
    "GWRE.NYSE":"GWRE.NYSE",
    "GWW.NYSE":"GWW.NYSE",
    "H.NYSE":"H.NYSE",
    "HAE.NYSE":"HAE.NYSE",
    "HAL.NYSE":"HAL.NYSE",
    "HASI.NYSE":"HASI.NYSE",
    "HBI.NYSE":"HBI.NYSE",
    "HCA.NYSE":"HCA.NYSE",
    "HD.NYSE":"HD.NYSE",
    "HEI.NYSE":"HEI.NYSE",
    "HES.NYSE":"HES.NYSE",
    "HFC.NYSE":"HFC.NYSE",
    "HGV.NYSE":"HGV.NYSE",
    "HHC.NYSE":"HHC.NYSE",
    "HIG.NYSE":"HIG.NYSE",
    "HII.NYSE":"HII.NYSE",
    "HIW.NYSE":"HIW.NYSE",
    "HLF.NYSE":"HLF.NYSE",
    "HLT.NYSE":"HLT.NYSE",
    "HLX.NYSE":"HLX.NYSE",
    "HMC.NYSE":"HMC.NYSE",
    "HMY.NYSE":"HMY.NYSE",
    "HOG.NYSE":"HOG.NYSE",
    "HOME.NYSE":"HOME.NYSE",
    "HON.NYSE":"HON.NYSE",
    "HP.NYSE":"HP.NYSE",
    "HPE.NYSE":"HPE.NYSE",
    "HPP.NYSE":"HPP.NYSE",
    "HPQ.NYSE":"HPQ.NYSE",
    "HR.NYSE":"HR.NYSE",
    "HRB.NYSE":"HRB.NYSE",
    "HRC.NYSE":"HRC.NYSE",
    "HRL.NYSE":"HRL.NYSE",
    "HSBC.NYSE":"HSBC.NYSE",
    "HSC.NYSE":"HSC.NYSE",
    "HSY.NYSE":"HSY.NYSE",
    "HTA.NYSE":"HTA.NYSE",
    "HTGC.NYSE":"HTGC.NYSE",
    "HUBB.NYSE":"HUBB.NYSE",
    "HUBS.NYSE":"HUBS.NYSE",
    "HUM.NYSE":"HUM.NYSE",
    "HUN.NYSE":"HUN.NYSE",
    "HWM.NYSE":"HWM.NYSE",
    "HXL.NYSE":"HXL.NYSE",
    "HYLN.NYSE":"HYLN.NYSE",
    "HYT.NYSE":"HYT.NYSE",
    "IBM.NYSE":"IBM.NYSE",
    "IBP.NYSE":"IBP.NYSE",
    "ICE.NYSE":"ICE.NYSE",
    "IDA.NYSE":"IDA.NYSE",
    "IEMG.NYSE":"IEMG.NYSE",
    "IEX.NYSE":"IEX.NYSE",
    "IFF.NYSE":"IFF.NYSE",
    "IGT.NYSE":"IGT.NYSE",
    "IIPR.NYSE":"IIPR.NYSE",
    "IMAX.NYSE":"IMAX.NYSE",
    "INFO.NYSE":"INFO.NYSE",
    "INFY.NYSE":"INFY.NYSE",
    "ING.NYSE":"ING.NYSE",
    "INGR.NYSE":"INGR.NYSE",
    "INN.NYSE":"INN.NYSE",
    "INSP.NYSE":"INSP.NYSE",
    "INVH.NYSE":"INVH.NYSE",
    "IP.NYSE":"IP.NYSE",
    "IPG.NYSE":"IPG.NYSE",
    "IQV.NYSE":"IQV.NYSE",
    "IR.NYSE":"IR.NYSE",
    "IRM.NYSE":"IRM.NYSE",
    "IRT.NYSE":"IRT.NYSE",
    "IT.NYSE":"IT.NYSE",
    "ITUB.NYSE":"ITUB.NYSE",
    "ITW.NYSE":"ITW.NYSE",
    "IVR.NYSE":"IVR.NYSE",
    "IVZ.NYSE":"IVZ.NYSE",
    "J.NYSE":"J.NYSE",
    "JBGS.NYSE":"JBGS.NYSE",
    "JBL.NYSE":"JBL.NYSE",
    "JBT.NYSE":"JBT.NYSE",
    "JCI.NYSE":"JCI.NYSE",
    "JEF.NYSE":"JEF.NYSE",
    "JLL.NYSE":"JLL.NYSE",
    "JMIA.NYSE":"JMIA.NYSE",
    "JNJ.NYSE":"JNJ.NYSE",
    "JNPR.NYSE":"JNPR.NYSE",
    "JOE.NYSE":"JOE.NYSE",
    "JPM.NYSE":"JPM.NYSE",
    "JWN.NYSE":"JWN.NYSE",
    "K.NYSE":"K.NYSE",
    "KAR.NYSE":"KAR.NYSE",
    "KBH.NYSE":"KBH.NYSE",
    "KBR.NYSE":"KBR.NYSE",
    "KEY.NYSE":"KEY.NYSE",
    "KEYS.NYSE":"KEYS.NYSE",
    "KGC.NYSE":"KGC.NYSE",
    "KIM.NYSE":"KIM.NYSE",
    "KKR.NYSE":"KKR.NYSE",
    "KMB.NYSE":"KMB.NYSE",
    "KMI.NYSE":"KMI.NYSE",
    "KMT.NYSE":"KMT.NYSE",
    "KMX.NYSE":"KMX.NYSE",
    "KNX.NYSE":"KNX.NYSE",
    "KO.NYSE":"KO.NYSE",
    "KOS.NYSE":"KOS.NYSE",
    "KR.NYSE":"KR.NYSE",
    "KRC.NYSE":"KRC.NYSE",
    "KRO.NYSE":"KRO.NYSE",
    "KSS.NYSE":"KSS.NYSE",
    "KSU.NYSE":"KSU.NYSE",
    "KW.NYSE":"KW.NYSE",
    "L.NYSE":"L.NYSE",
    "LAD.NYSE":"LAD.NYSE",
    "LAZ.NYSE":"LAZ.NYSE",
    "LB.NYSE":"LB.NYSE",
    "LBRT.NYSE":"LBRT.NYSE",
    "LDOS.NYSE":"LDOS.NYSE",
    "LEA.NYSE":"LEA.NYSE",
    "LEG.NYSE":"LEG.NYSE",
    "LEN.NYSE":"LEN.NYSE",
    "LEVI.NYSE":"LEVI.NYSE",
    "LFC.NYSE":"LFC.NYSE",
    "LH.NYSE":"LH.NYSE",
    "LHX.NYSE":"LHX.NYSE",
    "LII.NYSE":"LII.NYSE",
    "LIN.NYSE":"LIN.NYSE",
    "LLY.NYSE":"LLY.NYSE",
    "LMND.NYSE":"LMND.NYSE",
    "LMT.NYSE":"LMT.NYSE",
    "LNC.NYSE":"LNC.NYSE",
    "LOW.NYSE":"LOW.NYSE",
    "LPI.NYSE":"LPI.NYSE",
    "LPX.NYSE":"LPX.NYSE",
    "LQD.NYSE":"LQD.NYSE",
    "LRN.NYSE":"LRN.NYSE",
    "LSI.NYSE":"LSI.NYSE",
    "LTC.NYSE":"LTC.NYSE",
    "LTHM.NYSE":"LTHM.NYSE",
    "LUMN.NYSE":"LUMN.NYSE",
    "LUV.NYSE":"LUV.NYSE",
    "LVS.NYSE":"LVS.NYSE",
    "LW.NYSE":"LW.NYSE",
    "LXP.NYSE":"LXP.NYSE",
    "LYB.NYSE":"LYB.NYSE",
    "LYG.NYSE":"LYG.NYSE",
    "LYV.NYSE":"LYV.NYSE",
    "M.NYSE":"M.NYSE",
    "MA.NYSE":"MA.NYSE",
    "MAA.NYSE":"MAA.NYSE",
    "MAC.NYSE":"MAC.NYSE",
    "MAIN.NYSE":"MAIN.NYSE",
    "MAN.NYSE":"MAN.NYSE",
    "MANU.NYSE":"MANU.NYSE",
    "MAS.NYSE":"MAS.NYSE",
    "MAXR.NYSE":"MAXR.NYSE",
    "MBT.NYSE":"MBT.NYSE",
    "MCD.NYSE":"MCD.NYSE",
    "MCK.NYSE":"MCK.NYSE",
    "MCO.NYSE":"MCO.NYSE",
    "MD.NYSE":"MD.NYSE",
    "MDC.NYSE":"MDC.NYSE",
    "MDLA.NYSE":"MDLA.NYSE",
    "MDP.NYSE":"MDP.NYSE",
    "MDT.NYSE":"MDT.NYSE",
    "MDU.NYSE":"MDU.NYSE",
    "MED.NYSE":"MED.NYSE",
    "MET.NYSE":"MET.NYSE",
    "MFA.NYSE":"MFA.NYSE",
    "MGM.NYSE":"MGM.NYSE",
    "MGP.NYSE":"MGP.NYSE",
    "MGY.NYSE":"MGY.NYSE",
    "MHK.NYSE":"MHK.NYSE",
    "MITT.NYSE":"MITT.NYSE",
    "MJ.NYSE":"MJ.NYSE",
    "MKC.NYSE":"MKC.NYSE",
    "MKL.NYSE":"MKL.NYSE",
    "MLM.NYSE":"MLM.NYSE",
    "MMC.NYSE":"MMC.NYSE",
    "MMI.NYSE":"MMI.NYSE",
    "MMM.NYSE":"MMM.NYSE",
    "MNRL.NYSE":"MNRL.NYSE",
    "MO.NYSE":"MO.NYSE",
    "MOH.NYSE":"MOH.NYSE",
    "MOO.NYSE":"MOO.NYSE",
    "MOS.NYSE":"MOS.NYSE",
    "MPC.NYSE":"MPC.NYSE",
    "MPLX.NYSE":"MPLX.NYSE",
    "MPW.NYSE":"MPW.NYSE",
    "MRK.NYSE":"MRK.NYSE",
    "MRO.NYSE":"MRO.NYSE",
    "MS.NYSE":"MS.NYSE",
    "MSCI.NYSE":"MSCI.NYSE",
    "MSGS.NYSE":"MSGS.NYSE",
    "MSI.NYSE":"MSI.NYSE",
    "MTB.NYSE":"MTB.NYSE",
    "MTD.NYSE":"MTD.NYSE",
    "MTDR.NYSE":"MTDR.NYSE",
    "MTH.NYSE":"MTH.NYSE",
    "MTN.NYSE":"MTN.NYSE",
    "MTOR.NYSE":"MTOR.NYSE",
    "MTW.NYSE":"MTW.NYSE",
    "MTZ.NYSE":"MTZ.NYSE",
    "MUR.NYSE":"MUR.NYSE",
    "MUSA.NYSE":"MUSA.NYSE",
    "MUX.NYSE":"MUX.NYSE",
    "MWA.NYSE":"MWA.NYSE",
    "MX.NYSE":"MX.NYSE",
    "MXL.NYSE":"MXL.NYSE",
    "NAT.NYSE":"NAT.NYSE",
    "NAV.NYSE":"NAV.NYSE",
    "NBR.NYSE":"NBR.NYSE",
    "NCLH.NYSE":"NCLH.NYSE",
    "NCR.NYSE":"NCR.NYSE",
    "NEE.NYSE":"NEE.NYSE",
    "NEM.NYSE":"NEM.NYSE",
    "NEP.NYSE":"NEP.NYSE",
    "NET.NYSE":"NET.NYSE",
    "NEWR.NYSE":"NEWR.NYSE",
    "NI.NYSE":"NI.NYSE",
    "NIO.NYSE":"NIO.NYSE",
    "NKE.NYSE":"NKE.NYSE",
    "NLSN.NYSE":"NLSN.NYSE",
    "NLY.NYSE":"NLY.NYSE",
    "NNN.NYSE":"NNN.NYSE",
    "NOC.NYSE":"NOC.NYSE",
    "NOK.NYSE":"NOK.NYSE",
    "NOMD.NYSE":"NOMD.NYSE",
    "NOV.NYSE":"NOV.NYSE",
    "NOW.NYSE":"NOW.NYSE",
    "NPTN.NYSE":"NPTN.NYSE",
    "NRG.NYSE":"NRG.NYSE",
    "NRZ.NYSE":"NRZ.NYSE",
    "NS.NYSE":"NS.NYSE",
    "NSA.NYSE":"NSA.NYSE",
    "NSC.NYSE":"NSC.NYSE",
    "NSP.NYSE":"NSP.NYSE",
    "NUE.NYSE":"NUE.NYSE",
    "NUS.NYSE":"NUS.NYSE",
    "NVGS.NYSE":"NVGS.NYSE",
    "NVR.NYSE":"NVR.NYSE",
    "NVRO.NYSE":"NVRO.NYSE",
    "NVS.NYSE":"NVS.NYSE",
    "NVTA.NYSE":"NVTA.NYSE",
    "NYT.NYSE":"NYT.NYSE",
    "O.NYSE":"O.NYSE",
    "OFC.NYSE":"OFC.NYSE",
    "OHI.NYSE":"OHI.NYSE",
    "OI.NYSE":"OI.NYSE",
    "OKE.NYSE":"OKE.NYSE",
    "OLN.NYSE":"OLN.NYSE",
    "OMC.NYSE":"OMC.NYSE",
    "OMI.NYSE":"OMI.NYSE",
    "ONTO.NYSE":"ONTO.NYSE",
    "ORA.NYSE":"ORA.NYSE",
    "ORCL.NYSE":"ORCL.NYSE",
    "ORI.NYSE":"ORI.NYSE",
    "OSH.NYSE":"OSH.NYSE",
    "OSK.NYSE":"OSK.NYSE",
    "OTIS.NYSE":"OTIS.NYSE",
    "OUT.NYSE":"OUT.NYSE",
    "OXY.NYSE":"OXY.NYSE",
    "PAG.NYSE":"PAG.NYSE",
    "PAGS.NYSE":"PAGS.NYSE",
    "PANW.NYSE":"PANW.NYSE",
    "PAYC.NYSE":"PAYC.NYSE",
    "PBA.NYSE":"PBA.NYSE",
    "PBF.NYSE":"PBF.NYSE",
    "PBI.NYSE":"PBI.NYSE",
    "PBR.NYSE":"PBR.NYSE",
    "PCG.NYSE":"PCG.NYSE",
    "PD.NYSE":"PD.NYSE",
    "PDM.NYSE":"PDM.NYSE",
    "PEAK.NYSE":"PEAK.NYSE",
    "PEB.NYSE":"PEB.NYSE",
    "PEG.NYSE":"PEG.NYSE",
    "PEI.NYSE":"PEI.NYSE",
    "PEN.NYSE":"PEN.NYSE",
    "PFE.NYSE":"PFE.NYSE",
    "PFGC.NYSE":"PFGC.NYSE",
    "PG.NYSE":"PG.NYSE",
    "PGR.NYSE":"PGR.NYSE",
    "PGRE.NYSE":"PGRE.NYSE",
    "PH.NYSE":"PH.NYSE",
    "PHK.NYSE":"PHK.NYSE",
    "PHM.NYSE":"PHM.NYSE",
    "PII.NYSE":"PII.NYSE",
    "PINS.NYSE":"PINS.NYSE",
    "PK.NYSE":"PK.NYSE",
    "PKG.NYSE":"PKG.NYSE",
    "PKI.NYSE":"PKI.NYSE",
    "PLAN.NYSE":"PLAN.NYSE",
    "PLD.NYSE":"PLD.NYSE",
    "PLNT.NYSE":"PLNT.NYSE",
    "PLT.NYSE":"PLT.NYSE",
    "PLTR.NYSE":"PLTR.NYSE",
    "PM.NYSE":"PM.NYSE",
    "PNC.NYSE":"PNC.NYSE",
    "PNR.NYSE":"PNR.NYSE",
    "PNW.NYSE":"PNW.NYSE",
    "PPG.NYSE":"PPG.NYSE",
    "PPL.NYSE":"PPL.NYSE",
    "PRG.NYSE":"PRG.NYSE",
    "PRGO.NYSE":"PRGO.NYSE",
    "PRTY.NYSE":"PRTY.NYSE",
    "PRU.NYSE":"PRU.NYSE",
    "PSA.NYSE":"PSA.NYSE",
    "PSTG.NYSE":"PSTG.NYSE",
    "PSX.NYSE":"PSX.NYSE",
    "PTY.NYSE":"PTY.NYSE",
    "PUMP.NYSE":"PUMP.NYSE",
    "PVH.NYSE":"PVH.NYSE",
    "PWR.NYSE":"PWR.NYSE",
    "PXD.NYSE":"PXD.NYSE",
    "QD.NYSE":"QD.NYSE",
    "QS.NYSE":"QS.NYSE",
    "QTS.NYSE":"QTS.NYSE",
    "QTWO.NYSE":"QTWO.NYSE",
    "R.NYSE":"R.NYSE",
    "RAD.NYSE":"RAD.NYSE",
    "RCL.NYSE":"RCL.NYSE",
    "RDN.NYSE":"RDN.NYSE",
    "RE.NYSE":"RE.NYSE",
    "REXR.NYSE":"REXR.NYSE",
    "RF.NYSE":"RF.NYSE",
    "RFP.NYSE":"RFP.NYSE",
    "RGA.NYSE":"RGA.NYSE",
    "RGS.NYSE":"RGS.NYSE",
    "RH.NYSE":"RH.NYSE",
    "RHI.NYSE":"RHI.NYSE",
    "RIG.NYSE":"RIG.NYSE",
    "RJF.NYSE":"RJF.NYSE",
    "RKT.NYSE":"RKT.NYSE",
    "RL.NYSE":"RL.NYSE",
    "RLGY.NYSE":"RLGY.NYSE",
    "RLJ.NYSE":"RLJ.NYSE",
    "RMAX.NYSE":"RMAX.NYSE",
    "RMD.NYSE":"RMD.NYSE",
    "RNG.NYSE":"RNG.NYSE",
    "RNR.NYSE":"RNR.NYSE",
    "ROK.NYSE":"ROK.NYSE",
    "ROL.NYSE":"ROL.NYSE",
    "ROP.NYSE":"ROP.NYSE",
    "RPAI.NYSE":"RPAI.NYSE",
    "RPM.NYSE":"RPM.NYSE",
    "RRC.NYSE":"RRC.NYSE",
    "RRD.NYSE":"RRD.NYSE",
    "RS.NYSE":"RS.NYSE",
    "RSG.NYSE":"RSG.NYSE",
    "RTX.NYSE":"RTX.NYSE",
    "RVLV.NYSE":"RVLV.NYSE",
    "RWT.NYSE":"RWT.NYSE",
    "RYAM.NYSE":"RYAM.NYSE",
    "RYN.NYSE":"RYN.NYSE",
    "SA.NYSE":"SA.NYSE",
    "SAFE.NYSE":"SAFE.NYSE",
    "SAH.NYSE":"SAH.NYSE",
    "SAIL.NYSE":"SAIL.NYSE",
    "SAM.NYSE":"SAM.NYSE",
    "SAN.NYSE":"SAN.NYSE",
    "SAVE.NYSE":"SAVE.NYSE",
    "SBH.NYSE":"SBH.NYSE",
    "SBS.NYSE":"SBS.NYSE",
    "SBSW.NYSE":"SBSW.NYSE",
    "SCCO.NYSE":"SCCO.NYSE",
    "SCHW.NYSE":"SCHW.NYSE",
    "SCI.NYSE":"SCI.NYSE",
    "SCM.NYSE":"SCM.NYSE",
    "SCS.NYSE":"SCS.NYSE",
    "SE.NYSE":"SE.NYSE",
    "SEE.NYSE":"SEE.NYSE",
    "SHAK.NYSE":"SHAK.NYSE",
    "SHLX.NYSE":"SHLX.NYSE",
    "SHO.NYSE":"SHO.NYSE",
    "SHOP.NYSE":"SHOP.NYSE",
    "SHW.NYSE":"SHW.NYSE",
    "SIL.NYSE":"SIL.NYSE",
    "SITC.NYSE":"SITC.NYSE",
    "SIX.NYSE":"SIX.NYSE",
    "SJM.NYSE":"SJM.NYSE",
    "SKM.NYSE":"SKM.NYSE",
    "SKX.NYSE":"SKX.NYSE",
    "SLB.NYSE":"SLB.NYSE",
    "SLCA.NYSE":"SLCA.NYSE",
    "SLG.NYSE":"SLG.NYSE",
    "SM.NYSE":"SM.NYSE",
    "SMAR.NYSE":"SMAR.NYSE",
    "SMG.NYSE":"SMG.NYSE",
    "SNA.NYSE":"SNA.NYSE",
    "SNAP.NYSE":"SNAP.NYSE",
    "SNOW.NYSE":"SNOW.NYSE",
    "SNX.NYSE":"SNX.NYSE",
    "SO.NYSE":"SO.NYSE",
    "SOGO.NYSE":"SOGO.NYSE",
    "SOL.NYSE":"SOL.NYSE",
    "SON.NYSE":"SON.NYSE",
    "SPB.NYSE":"SPB.NYSE",
    "SPCE.NYSE":"SPCE.NYSE",
    "SPG.NYSE":"SPG.NYSE",
    "SPGI.NYSE":"SPGI.NYSE",
    "SPOT.NYSE":"SPOT.NYSE",
    "SPR.NYSE":"SPR.NYSE",
    "SQ.NYSE":"SQ.NYSE",
    "SRE.NYSE":"SRE.NYSE",
    "SRG.NYSE":"SRG.NYSE",
    "STAG.NYSE":"STAG.NYSE",
    "STE.NYSE":"STE.NYSE",
    "STNG.NYSE":"STNG.NYSE",
    "STOR.NYSE":"STOR.NYSE",
    "STT.NYSE":"STT.NYSE",
    "STWD.NYSE":"STWD.NYSE",
    "STZ.NYSE":"STZ.NYSE",
    "SUI.NYSE":"SUI.NYSE",
    "SWCH.NYSE":"SWCH.NYSE",
    "SWK.NYSE":"SWK.NYSE",
    "SWN.NYSE":"SWN.NYSE",
    "SXT.NYSE":"SXT.NYSE",
    "SYF.NYSE":"SYF.NYSE",
    "SYK.NYSE":"SYK.NYSE",
    "SYY.NYSE":"SYY.NYSE",
    "T.NYSE":"T.NYSE",
    "TAK.NYSE":"TAK.NYSE",
    "TAL.NYSE":"TAL.NYSE",
    "TALO.NYSE":"TALO.NYSE",
    "TAP.NYSE":"TAP.NYSE",
    "TDC.NYSE":"TDC.NYSE",
    "TDG.NYSE":"TDG.NYSE",
    "TDOC.NYSE":"TDOC.NYSE",
    "TDY.NYSE":"TDY.NYSE",
    "TECK.NYSE":"TECK.NYSE",
    "TEF.NYSE":"TEF.NYSE",
    "TEL.NYSE":"TEL.NYSE",
    "TEVA.NYSE":"TEVA.NYSE",
    "TFC.NYSE":"TFC.NYSE",
    "TFX.NYSE":"TFX.NYSE",
    "TGNA.NYSE":"TGNA.NYSE",
    "TGT.NYSE":"TGT.NYSE",
    "THC.NYSE":"THC.NYSE",
    "THG.NYSE":"THG.NYSE",
    "THO.NYSE":"THO.NYSE",
    "THS.NYSE":"THS.NYSE",
    "TJX.NYSE":"TJX.NYSE",
    "TM.NYSE":"TM.NYSE",
    "TME.NYSE":"TME.NYSE",
    "TMHC.NYSE":"TMHC.NYSE",
    "TMO.NYSE":"TMO.NYSE",
    "TMX.NYSE":"TMX.NYSE",
    "TOL.NYSE":"TOL.NYSE",
    "TPC.NYSE":"TPC.NYSE",
    "TPH.NYSE":"TPH.NYSE",
    "TPR.NYSE":"TPR.NYSE",
    "TPX.NYSE":"TPX.NYSE",
    "TREX.NYSE":"TREX.NYSE",
    "TRGP.NYSE":"TRGP.NYSE",
    "TRNO.NYSE":"TRNO.NYSE",
    "TROX.NYSE":"TROX.NYSE",
    "TRU.NYSE":"TRU.NYSE",
    "TRV.NYSE":"TRV.NYSE",
    "TSN.NYSE":"TSN.NYSE",
    "TT.NYSE":"TT.NYSE",
    "TTC.NYSE":"TTC.NYSE",
    "TTI.NYSE":"TTI.NYSE",
    "TTM.NYSE":"TTM.NYSE",
    "TUP.NYSE":"TUP.NYSE",
    "TV.NYSE":"TV.NYSE",
    "TWI.NYSE":"TWI.NYSE",
    "TWLO.NYSE":"TWLO.NYSE",
    "TWO.NYSE":"TWO.NYSE",
    "TWTR.NYSE":"TWTR.NYSE",
    "TX.NYSE":"TX.NYSE",
    "TXT.NYSE":"TXT.NYSE",
    "TYL.NYSE":"TYL.NYSE",
    "U.NYSE":"U.NYSE",
    "UA.NYSE":"UA.NYSE",
    "UAA.NYSE":"UAA.NYSE",
    "UBER.NYSE":"UBER.NYSE",
    "UDR.NYSE":"UDR.NYSE",
    "UE.NYSE":"UE.NYSE",
    "UGI.NYSE":"UGI.NYSE",
    "UHS.NYSE":"UHS.NYSE",
    "UHT.NYSE":"UHT.NYSE",
    "UI.NYSE":"UI.NYSE",
    "UMC.NYSE":"UMC.NYSE",
    "UNFI.NYSE":"UNFI.NYSE",
    "UNG.NYSE":"UNG.NYSE",
    "UNH.NYSE":"UNH.NYSE",
    "UNM.NYSE":"UNM.NYSE",
    "UNP.NYSE":"UNP.NYSE",
    "UPS.NYSE":"UPS.NYSE",
    "URA.NYSE":"URA.NYSE",
    "URI.NYSE":"URI.NYSE",
    "USAC.NYSE":"USAC.NYSE",
    "USB.NYSE":"USB.NYSE",
    "USFD.NYSE":"USFD.NYSE",
    "USNA.NYSE":"USNA.NYSE",
    "USO.NYSE":"USO.NYSE",
    "USX.NYSE":"USX.NYSE",
    "UVV.NYSE":"UVV.NYSE",
    "V.NYSE":"V.NYSE",
    "VAC.NYSE":"VAC.NYSE",
    "VALE.NYSE":"VALE.NYSE",
    "VEDL.NYSE":"VEDL.NYSE",
    "VEEV.NYSE":"VEEV.NYSE",
    "VER.NYSE":"VER.NYSE",
    "VFC.NYSE":"VFC.NYSE",
    "VHC.NYSE":"VHC.NYSE",
    "VIPS.NYSE":"VIPS.NYSE",
    "VLO.NYSE":"VLO.NYSE",
    "VLRS.NYSE":"VLRS.NYSE",
    "VMC.NYSE":"VMC.NYSE",
    "VMW.NYSE":"VMW.NYSE",
    "VNO.NYSE":"VNO.NYSE",
    "VST.NYSE":"VST.NYSE",
    "VSTO.NYSE":"VSTO.NYSE",
    "VTR.NYSE":"VTR.NYSE",
    "VVI.NYSE":"VVI.NYSE",
    "VYM.NYSE":"VYM.NYSE",
    "VZ.NYSE":"VZ.NYSE",
    "W.NYSE":"W.NYSE",
    "WAB.NYSE":"WAB.NYSE",
    "WAT.NYSE":"WAT.NYSE",
    "WCC.NYSE":"WCC.NYSE",
    "WEC.NYSE":"WEC.NYSE",
    "WELL.NYSE":"WELL.NYSE",
    "WEX.NYSE":"WEX.NYSE",
    "WFC.NYSE":"WFC.NYSE",
    "WGO.NYSE":"WGO.NYSE",
    "WHR.NYSE":"WHR.NYSE",
    "WLK.NYSE":"WLK.NYSE",
    "WLL.NYSE":"WLL.NYSE",
    "WM.NYSE":"WM.NYSE",
    "WMB.NYSE":"WMB.NYSE",
    "WMC.NYSE":"WMC.NYSE",
    "WMT.NYSE":"WMT.NYSE",
    "WORK.NYSE":"WORK.NYSE",
    "WPC.NYSE":"WPC.NYSE",
    "WRB.NYSE":"WRB.NYSE",
    "WRE.NYSE":"WRE.NYSE",
    "WRI.NYSE":"WRI.NYSE",
    "WRK.NYSE":"WRK.NYSE",
    "WSM.NYSE":"WSM.NYSE",
    "WSO.NYSE":"WSO.NYSE",
    "WST.NYSE":"WST.NYSE",
    "WTI.NYSE":"WTI.NYSE",
    "WTRG.NYSE":"WTRG.NYSE",
    "WU.NYSE":"WU.NYSE",
    "WWE.NYSE":"WWE.NYSE",
    "WY.NYSE":"WY.NYSE",
    "XEC.NYSE":"XEC.NYSE",
    "XLE.NYSE":"XLE.NYSE",
    "XLF.NYSE":"XLF.NYSE",
    "XLI.NYSE":"XLI.NYSE",
    "XLP.NYSE":"XLP.NYSE",
    "XLU.NYSE":"XLU.NYSE",
    "XOM.NYSE":"XOM.NYSE",
    "XOP.NYSE":"XOP.NYSE",
    "XRX.NYSE":"XRX.NYSE",
    "XYL.NYSE":"XYL.NYSE",
    "Y.NYSE":"Y.NYSE",
    "YELP.NYSE":"YELP.NYSE",
    "YETI.NYSE":"YETI.NYSE",
    "YEXT.NYSE":"YEXT.NYSE",
    "YUM.NYSE":"YUM.NYSE",
    "YUMC.NYSE":"YUMC.NYSE",
    "ZBH.NYSE":"ZBH.NYSE",
    "ZEN.NYSE":"ZEN.NYSE",
    "ZTO.NYSE":"ZTO.NYSE",
    "ZTS.NYSE":"ZTS.NYSE",
    "ZUO.NYSE":"ZUO.NYSE",
    "AAL.NAS":"AAL.NAS",
    "AAPL.NAS":"AAPL.NAS",
    "AAXJ.NAS":"AAXJ.NAS",
    "ABCB.NAS":"ABCB.NAS",
    "ABMD.NAS":"ABMD.NAS",
    "ABNB.NAS":"ABNB.NAS",
    "ABUS.NAS":"ABUS.NAS",
    "ACAD.NAS":"ACAD.NAS",
    "ACMR.NAS":"ACMR.NAS",
    "ACRX.NAS":"ACRX.NAS",
    "ACWI.NAS":"ACWI.NAS",
    "ADAP.NAS":"ADAP.NAS",
    "ADBE.NAS":"ADBE.NAS",
    "ADI.NAS":"ADI.NAS",
    "ADP.NAS":"ADP.NAS",
    "ADSK.NAS":"ADSK.NAS",
    "ADVM.NAS":"ADVM.NAS",
    "AEP.NAS":"AEP.NAS",
    "AFRM.NAS":"AFRM.NAS",
    "AGEN.NAS":"AGEN.NAS",
    "AGNC.NAS":"AGNC.NAS",
    "AGRX.NAS":"AGRX.NAS",
    "AINV.NAS":"AINV.NAS",
    "AKAM.NAS":"AKAM.NAS",
    "ALDX.NAS":"ALDX.NAS",
    "ALGN.NAS":"ALGN.NAS",
    "ALNY.NAS":"ALNY.NAS",
    "ALRM.NAS":"ALRM.NAS",
    "ALT.NAS":"ALT.NAS",
    "ALVR.NAS":"ALVR.NAS",
    "ALXN.NAS":"ALXN.NAS",
    "AMAT.NAS":"AMAT.NAS",
    "AMBA.NAS":"AMBA.NAS",
    "AMD.NAS":"AMD.NAS",
    "AMED.NAS":"AMED.NAS",
    "AMGN.NAS":"AMGN.NAS",
    "AMRS.NAS":"AMRS.NAS",
    "AMZN.NAS":"AMZN.NAS",
    "ANDE.NAS":"ANDE.NAS",
    "ANGI.NAS":"ANGI.NAS",
    "ANSS.NAS":"ANSS.NAS",
    "APA.NAS":"APA.NAS",
    "APHA.NAS":"APHA.NAS",
    "APPF.NAS":"APPF.NAS",
    "APPN.NAS":"APPN.NAS",
    "ARAY.NAS":"ARAY.NAS",
    "ARCC.NAS":"ARCC.NAS",
    "ARCT.NAS":"ARCT.NAS",
    "ARWR.NAS":"ARWR.NAS",
    "ATHX.NAS":"ATHX.NAS",
    "ATNX.NAS":"ATNX.NAS",
    "ATRA.NAS":"ATRA.NAS",
    "ATRS.NAS":"ATRS.NAS",
    "ATVI.NAS":"ATVI.NAS",
    "AVAV.NAS":"AVAV.NAS",
    "AVGO.NAS":"AVGO.NAS",
    "AVID.NAS":"AVID.NAS",
    "AVT.NAS":"AVT.NAS",
    "AVXL.NAS":"AVXL.NAS",
    "AXGN.NAS":"AXGN.NAS",
    "AXSM.NAS":"AXSM.NAS",
    "AY.NAS":"AY.NAS",
    "AYRO.NAS":"AYRO.NAS",
    "AYTU.NAS":"AYTU.NAS",
    "AZPN.NAS":"AZPN.NAS",
    "BBBY.NAS":"BBBY.NAS",
    "BBIO.NAS":"BBIO.NAS",
    "BCRX.NAS":"BCRX.NAS",
    "BGCP.NAS":"BGCP.NAS",
    "BHF.NAS":"BHF.NAS",
    "BIDU.NAS":"BIDU.NAS",
    "BIIB.NAS":"BIIB.NAS",
    "BILI.NAS":"BILI.NAS",
    "BKNG.NAS":"BKNG.NAS",
    "BLDR.NAS":"BLDR.NAS",
    "BLFS.NAS":"BLFS.NAS",
    "BLMN.NAS":"BLMN.NAS",
    "BLNK.NAS":"BLNK.NAS",
    "BLUE.NAS":"BLUE.NAS",
    "BMRN.NAS":"BMRN.NAS",
    "BNGO.NAS":"BNGO.NAS",
    "BNTX.NAS":"BNTX.NAS",
    "BPMC.NAS":"BPMC.NAS",
    "BPY.NAS":"BPY.NAS",
    "BRKR.NAS":"BRKR.NAS",
    "BRKS.NAS":"BRKS.NAS",
    "BSY.NAS":"BSY.NAS",
    "BYND.NAS":"BYND.NAS",
    "BZUN.NAS":"BZUN.NAS",
    "CACC.NAS":"CACC.NAS",
    "CAKE.NAS":"CAKE.NAS",
    "CAMP.NAS":"CAMP.NAS",
    "CAN.NAS":"CAN.NAS",
    "CAR.NAS":"CAR.NAS",
    "CARA.NAS":"CARA.NAS",
    "CASA.NAS":"CASA.NAS",
    "CASY.NAS":"CASY.NAS",
    "CBAY.NAS":"CBAY.NAS",
    "CBRL.NAS":"CBRL.NAS",
    "CDEV.NAS":"CDEV.NAS",
    "CDLX.NAS":"CDLX.NAS",
    "CDNS.NAS":"CDNS.NAS",
    "CDW.NAS":"CDW.NAS",
    "CDXS.NAS":"CDXS.NAS",
    "CERN.NAS":"CERN.NAS",
    "CERS.NAS":"CERS.NAS",
    "CEVA.NAS":"CEVA.NAS",
    "CG.NAS":"CG.NAS",
    "CGNX.NAS":"CGNX.NAS",
    "CHDN.NAS":"CHDN.NAS",
    "CHEF.NAS":"CHEF.NAS",
    "CHKP.NAS":"CHKP.NAS",
    "CHMA.NAS":"CHMA.NAS",
    "CHRS.NAS":"CHRS.NAS",
    "CHRW.NAS":"CHRW.NAS",
    "CHTR.NAS":"CHTR.NAS",
    "CIBR.NAS":"CIBR.NAS",
    "CINF.NAS":"CINF.NAS",
    "CLDX.NAS":"CLDX.NAS",
    "CLMT.NAS":"CLMT.NAS",
    "CLNE.NAS":"CLNE.NAS",
    "CLSK.NAS":"CLSK.NAS",
    "CLVS.NAS":"CLVS.NAS",
    "CMCSA.NAS":"CMCSA.NAS",
    "CME.NAS":"CME.NAS",
    "CNDT.NAS":"CNDT.NAS",
    "CNST.NAS":"CNST.NAS",
    "CODX.NAS":"CODX.NAS",
    "COMM.NAS":"COMM.NAS",
    "CONE.NAS":"CONE.NAS",
    "CONN.NAS":"CONN.NAS",
    "CORE.NAS":"CORE.NAS",
    "COST.NAS":"COST.NAS",
    "COUP.NAS":"COUP.NAS",
    "CPRT.NAS":"CPRT.NAS",
    "CPRX.NAS":"CPRX.NAS",
    "CRBP.NAS":"CRBP.NAS",
    "CREE.NAS":"CREE.NAS",
    "CRIS.NAS":"CRIS.NAS",
    "CRMD.NAS":"CRMD.NAS",
    "CRNT.NAS":"CRNT.NAS",
    "CRON.NAS":"CRON.NAS",
    "CROX.NAS":"CROX.NAS",
    "CRSP.NAS":"CRSP.NAS",
    "CRUS.NAS":"CRUS.NAS",
    "CRWD.NAS":"CRWD.NAS",
    "CSCO.NAS":"CSCO.NAS",
    "CSGP.NAS":"CSGP.NAS",
    "CSIQ.NAS":"CSIQ.NAS",
    "CSOD.NAS":"CSOD.NAS",
    "CSX.NAS":"CSX.NAS",
    "CTAS.NAS":"CTAS.NAS",
    "CTSH.NAS":"CTSH.NAS",
    "CTXS.NAS":"CTXS.NAS",
    "CVAC.NAS":"CVAC.NAS",
    "CWCO.NAS":"CWCO.NAS",
    "CYBR.NAS":"CYBR.NAS",
    "CYTK.NAS":"CYTK.NAS",
    "CZR.NAS":"CZR.NAS",
    "DBX.NAS":"DBX.NAS",
    "DDOG.NAS":"DDOG.NAS",
    "DENN.NAS":"DENN.NAS",
    "DISCA.NAS":"DISCA.NAS",
    "DISCK.NAS":"DISCK.NAS",
    "DISH.NAS":"DISH.NAS",
    "DKNG.NAS":"DKNG.NAS",
    "DLTR.NAS":"DLTR.NAS",
    "DOCU.NAS":"DOCU.NAS",
    "DOMO.NAS":"DOMO.NAS",
    "DOYU.NAS":"DOYU.NAS",
    "DTIL.NAS":"DTIL.NAS",
    "DVAX.NAS":"DVAX.NAS",
    "DVY.NAS":"DVY.NAS",
    "DXCM.NAS":"DXCM.NAS",
    "EA.NAS":"EA.NAS",
    "EBAY.NAS":"EBAY.NAS",
    "EDIT.NAS":"EDIT.NAS",
    "EEFT.NAS":"EEFT.NAS",
    "EGAN.NAS":"EGAN.NAS",
    "EGLE.NAS":"EGLE.NAS",
    "EH.NAS":"EH.NAS",
    "EHTH.NAS":"EHTH.NAS",
    "EMB.NAS":"EMB.NAS",
    "ENPH.NAS":"ENPH.NAS",
    "ENTG.NAS":"ENTG.NAS",
    "EOLS.NAS":"EOLS.NAS",
    "EPZM.NAS":"EPZM.NAS",
    "EQIX.NAS":"EQIX.NAS",
    "ERIC.NAS":"ERIC.NAS",
    "ERIE.NAS":"ERIE.NAS",
    "ETSY.NAS":"ETSY.NAS",
    "EVBG.NAS":"EVBG.NAS",
    "EVER.NAS":"EVER.NAS",
    "EXAS.NAS":"EXAS.NAS",
    "EXC.NAS":"EXC.NAS",
    "EXEL.NAS":"EXEL.NAS",
    "EXPD.NAS":"EXPD.NAS",
    "EXPE.NAS":"EXPE.NAS",
    "EXPI.NAS":"EXPI.NAS",
    "FANG.NAS":"FANG.NAS",
    "FAST.NAS":"FAST.NAS",
    "FATE.NAS":"FATE.NAS",
    "FB.NAS":"FB.NAS",
    "FCEL.NAS":"FCEL.NAS",
    "FEYE.NAS":"FEYE.NAS",
    "FFIV.NAS":"FFIV.NAS",
    "FISV.NAS":"FISV.NAS",
    "FITB.NAS":"FITB.NAS",
    "FIVE.NAS":"FIVE.NAS",
    "FIVN.NAS":"FIVN.NAS",
    "FIZZ.NAS":"FIZZ.NAS",
    "FLEX.NAS":"FLEX.NAS",
    "FLWS.NAS":"FLWS.NAS",
    "FOLD.NAS":"FOLD.NAS",
    "FOSL.NAS":"FOSL.NAS",
    "FOX.NAS":"FOX.NAS",
    "FOXA.NAS":"FOXA.NAS",
    "FROG.NAS":"FROG.NAS",
    "FRPT.NAS":"FRPT.NAS",
    "FRSX.NAS":"FRSX.NAS",
    "FSLR.NAS":"FSLR.NAS",
    "FTNT.NAS":"FTNT.NAS",
    "FWONA.NAS":"FWONA.NAS",
    "FWONK.NAS":"FWONK.NAS",
    "GDRX.NAS":"GDRX.NAS",
    "GERN.NAS":"GERN.NAS",
    "GEVO.NAS":"GEVO.NAS",
    "GIII.NAS":"GIII.NAS",
    "GILD.NAS":"GILD.NAS",
    "GLAD.NAS":"GLAD.NAS",
    "GLNG.NAS":"GLNG.NAS",
    "GLPI.NAS":"GLPI.NAS",
    "GNPX.NAS":"GNPX.NAS",
    "GNTX.NAS":"GNTX.NAS",
    "GNUS.NAS":"GNUS.NAS",
    "GO.NAS":"GO.NAS",
    "GOGO.NAS":"GOGO.NAS",
    "GOOD.NAS":"GOOD.NAS",
    "GOOG.NAS":"GOOG.NAS",
    "GOSS.NAS":"GOSS.NAS",
    "GPC.NAS":"GPC.NAS",
    "GPRE.NAS":"GPRE.NAS",
    "GPRO.NAS":"GPRO.NAS",
    "GRMN.NAS":"GRMN.NAS",
    "GSKY.NAS":"GSKY.NAS",
    "GT.NAS":"GT.NAS",
    "HA.NAS":"HA.NAS",
    "HAIN.NAS":"HAIN.NAS",
    "HALO.NAS":"HALO.NAS",
    "HAS.NAS":"HAS.NAS",
    "HBAN.NAS":"HBAN.NAS",
    "HEAR.NAS":"HEAR.NAS",
    "HLIT.NAS":"HLIT.NAS",
    "HMHC.NAS":"HMHC.NAS",
    "HOLX.NAS":"HOLX.NAS",
    "HQY.NAS":"HQY.NAS",
    "HSIC.NAS":"HSIC.NAS",
    "HST.NAS":"HST.NAS",
    "HTBX.NAS":"HTBX.NAS",
    "HTHT.NAS":"HTHT.NAS",
    "IAC.NAS":"IAC.NAS",
    "IBB.NAS":"IBB.NAS",
    "IBKR.NAS":"IBKR.NAS",
    "ICPT.NAS":"ICPT.NAS",
    "IDCC.NAS":"IDCC.NAS",
    "IDEX.NAS":"IDEX.NAS",
    "IDXX.NAS":"IDXX.NAS",
    "IEF.NAS":"IEF.NAS",
    "IEP.NAS":"IEP.NAS",
    "IFRX.NAS":"IFRX.NAS",
    "IHRT.NAS":"IHRT.NAS",
    "IIVI.NAS":"IIVI.NAS",
    "ILMN.NAS":"ILMN.NAS",
    "ILPT.NAS":"ILPT.NAS",
    "IMGN.NAS":"IMGN.NAS",
    "INCY.NAS":"INCY.NAS",
    "INFN.NAS":"INFN.NAS",
    "INGN.NAS":"INGN.NAS",
    "INO.NAS":"INO.NAS",
    "INSG.NAS":"INSG.NAS",
    "INTC.NAS":"INTC.NAS",
    "INTU.NAS":"INTU.NAS",
    "IONS.NAS":"IONS.NAS",
    "IPGP.NAS":"IPGP.NAS",
    "IRBT.NAS":"IRBT.NAS",
    "IRDM.NAS":"IRDM.NAS",
    "IRTC.NAS":"IRTC.NAS",
    "ISBC.NAS":"ISBC.NAS",
    "ISRG.NAS":"ISRG.NAS",
    "ISTB.NAS":"ISTB.NAS",
    "ITCI.NAS":"ITCI.NAS",
    "ITRI.NAS":"ITRI.NAS",
    "IUSB.NAS":"IUSB.NAS",
    "IUSG.NAS":"IUSG.NAS",
    "IUSV.NAS":"IUSV.NAS",
    "IXUS.NAS":"IXUS.NAS",
    "IZEA.NAS":"IZEA.NAS",
    "JACK.NAS":"JACK.NAS",
    "JAZZ.NAS":"JAZZ.NAS",
    "JBHT.NAS":"JBHT.NAS",
    "JBLU.NAS":"JBLU.NAS",
    "JFU.NAS":"JFU.NAS",
    "JKHY.NAS":"JKHY.NAS",
    "JOBS.NAS":"JOBS.NAS",
    "JOUT.NAS":"JOUT.NAS",
    "KDMN.NAS":"KDMN.NAS",
    "KDP.NAS":"KDP.NAS",
    "KHC.NAS":"KHC.NAS",
    "KIN.NAS":"KIN.NAS",
    "KLAC.NAS":"KLAC.NAS",
    "KNDI.NAS":"KNDI.NAS",
    "KTOS.NAS":"KTOS.NAS",
    "LAMR.NAS":"LAMR.NAS",
    "LAZR.NAS":"LAZR.NAS",
    "LBRDA.NAS":"LBRDA.NAS",
    "LBRDK.NAS":"LBRDK.NAS",
    "LBTYA.NAS":"LBTYA.NAS",
    "LBTYK.NAS":"LBTYK.NAS",
    "LECO.NAS":"LECO.NAS",
    "LI.NAS":"LI.NAS",
    "LILA.NAS":"LILA.NAS",
    "LITE.NAS":"LITE.NAS",
    "LKQ.NAS":"LKQ.NAS",
    "LLNW.NAS":"LLNW.NAS",
    "LNT.NAS":"LNT.NAS",
    "LOGI.NAS":"LOGI.NAS",
    "LPLA.NAS":"LPLA.NAS",
    "LPSN.NAS":"LPSN.NAS",
    "LRCX.NAS":"LRCX.NAS",
    "LSCC.NAS":"LSCC.NAS",
    "LSXMK.NAS":"LSXMK.NAS",
    "LTRPA.NAS":"LTRPA.NAS",
    "LULU.NAS":"LULU.NAS",
    "LUNA.NAS":"LUNA.NAS",
    "LXRX.NAS":"LXRX.NAS",
    "LYFT.NAS":"LYFT.NAS",
    "MAR.NAS":"MAR.NAS",
    "MARA.NAS":"MARA.NAS",
    "MARK.NAS":"MARK.NAS",
    "MASI.NAS":"MASI.NAS",
    "MAT.NAS":"MAT.NAS",
    "MCHI.NAS":"MCHI.NAS",
    "MCHP.NAS":"MCHP.NAS",
    "MCRB.NAS":"MCRB.NAS",
    "MDB.NAS":"MDB.NAS",
    "MDIV.NAS":"MDIV.NAS",
    "MDLZ.NAS":"MDLZ.NAS",
    "MELI.NAS":"MELI.NAS",
    "MGI.NAS":"MGI.NAS",
    "MITK.NAS":"MITK.NAS",
    "MKSI.NAS":"MKSI.NAS",
    "MKTX.NAS":"MKTX.NAS",
    "MLCO.NAS":"MLCO.NAS",
    "MMYT.NAS":"MMYT.NAS",
    "MNKD.NAS":"MNKD.NAS",
    "MNST.NAS":"MNST.NAS",
    "MOMO.NAS":"MOMO.NAS",
    "MORN.NAS":"MORN.NAS",
    "MPWR.NAS":"MPWR.NAS",
    "MRCY.NAS":"MRCY.NAS",
    "MRNA.NAS":"MRNA.NAS",
    "MRNS.NAS":"MRNS.NAS",
    "MRTX.NAS":"MRTX.NAS",
    "MRVL.NAS":"MRVL.NAS",
    "MSFT.NAS":"MSFT.NAS",
    "MSTR.NAS":"MSTR.NAS",
    "MTCH.NAS":"MTCH.NAS",
    "MU.NAS":"MU.NAS",
    "MVIS.NAS":"MVIS.NAS",
    "MXIM.NAS":"MXIM.NAS",
    "NARI.NAS":"NARI.NAS",
    "NATI.NAS":"NATI.NAS",
    "NAVI.NAS":"NAVI.NAS",
    "NBEV.NAS":"NBEV.NAS",
    "NBIX.NAS":"NBIX.NAS",
    "NCMI.NAS":"NCMI.NAS",
    "NDAQ.NAS":"NDAQ.NAS",
    "NDLS.NAS":"NDLS.NAS",
    "NDSN.NAS":"NDSN.NAS",
    "NERV.NAS":"NERV.NAS",
    "NESR.NAS":"NESR.NAS",
    "NFLX.NAS":"NFLX.NAS",
    "NICE.NAS":"NICE.NAS",
    "NIU.NAS":"NIU.NAS",
    "NKLA.NAS":"NKLA.NAS",
    "NKTR.NAS":"NKTR.NAS",
    "NLOK.NAS":"NLOK.NAS",
    "NMIH.NAS":"NMIH.NAS",
    "NMRK.NAS":"NMRK.NAS",
    "NNDM.NAS":"NNDM.NAS",
    "NOVN.NAS":"NOVN.NAS",
    "NTAP.NAS":"NTAP.NAS",
    "NTES.NAS":"NTES.NAS",
    "NTLA.NAS":"NTLA.NAS",
    "NTNX.NAS":"NTNX.NAS",
    "NTRA.NAS":"NTRA.NAS",
    "NTRS.NAS":"NTRS.NAS",
    "NUAN.NAS":"NUAN.NAS",
    "NUVA.NAS":"NUVA.NAS",
    "NVAX.NAS":"NVAX.NAS",
    "NVCR.NAS":"NVCR.NAS",
    "NVDA.NAS":"NVDA.NAS",
    "NWL.NAS":"NWL.NAS",
    "NWS.NAS":"NWS.NAS",
    "NWSA.NAS":"NWSA.NAS",
    "NXPI.NAS":"NXPI.NAS",
    "NXST.NAS":"NXST.NAS",
    "NYMT.NAS":"NYMT.NAS",
    "OCGN.NAS":"OCGN.NAS",
    "OCUL.NAS":"OCUL.NAS",
    "ODFL.NAS":"ODFL.NAS",
    "ODP.NAS":"ODP.NAS",
    "OKTA.NAS":"OKTA.NAS",
    "OLED.NAS":"OLED.NAS",
    "OLLI.NAS":"OLLI.NAS",
    "ON.NAS":"ON.NAS",
    "ONEM.NAS":"ONEM.NAS",
    "ONTX.NAS":"ONTX.NAS",
    "OPEN.NAS":"OPEN.NAS",
    "OPI.NAS":"OPI.NAS",
    "OPK.NAS":"OPK.NAS",
    "ORBC.NAS":"ORBC.NAS",
    "ORLY.NAS":"ORLY.NAS",
    "ORTX.NAS":"ORTX.NAS",
    "OSTK.NAS":"OSTK.NAS",
    "OSUR.NAS":"OSUR.NAS",
    "OVID.NAS":"OVID.NAS",
    "PAA.NAS":"PAA.NAS",
    "PACB.NAS":"PACB.NAS",
    "PAGP.NAS":"PAGP.NAS",
    "PAYX.NAS":"PAYX.NAS",
    "PBCT.NAS":"PBCT.NAS",
    "PBYI.NAS":"PBYI.NAS",
    "PCAR.NAS":"PCAR.NAS",
    "PCH.NAS":"PCH.NAS",
    "PCTY.NAS":"PCTY.NAS",
    "PCVX.NAS":"PCVX.NAS",
    "PDCE.NAS":"PDCE.NAS",
    "PDCO.NAS":"PDCO.NAS",
    "PDD.NAS":"PDD.NAS",
    "PEGA.NAS":"PEGA.NAS",
    "PENN.NAS":"PENN.NAS",
    "PEP.NAS":"PEP.NAS",
    "PFF.NAS":"PFF.NAS",
    "PFG.NAS":"PFG.NAS",
    "PFLT.NAS":"PFLT.NAS",
    "PFPT.NAS":"PFPT.NAS",
    "PGEN.NAS":"PGEN.NAS",
    "PGNY.NAS":"PGNY.NAS",
    "PINC.NAS":"PINC.NAS",
    "PLAY.NAS":"PLAY.NAS",
    "PLCE.NAS":"PLCE.NAS",
    "PLUG.NAS":"PLUG.NAS",
    "PLYA.NAS":"PLYA.NAS",
    "PNNT.NAS":"PNNT.NAS",
    "PODD.NAS":"PODD.NAS",
    "POOL.NAS":"POOL.NAS",
    "POWI.NAS":"POWI.NAS",
    "PPD.NAS":"PPD.NAS",
    "PRAH.NAS":"PRAH.NAS",
    "PRFT.NAS":"PRFT.NAS",
    "PRQR.NAS":"PRQR.NAS",
    "PRTK.NAS":"PRTK.NAS",
    "PRVB.NAS":"PRVB.NAS",
    "PSEC.NAS":"PSEC.NAS",
    "PTC.NAS":"PTC.NAS",
    "PTEN.NAS":"PTEN.NAS",
    "PTON.NAS":"PTON.NAS",
    "PVAC.NAS":"PVAC.NAS",
    "PYPL.NAS":"PYPL.NAS",
    "PZZA.NAS":"PZZA.NAS",
    "QCOM.NAS":"QCOM.NAS",
    "QDEL.NAS":"QDEL.NAS",
    "QFIN.NAS":"QFIN.NAS",
    "QIWI.NAS":"QIWI.NAS",
    "QQQ.NAS":"QQQ.NAS",
    "QRTEA.NAS":"QRTEA.NAS",
    "QRVO.NAS":"QRVO.NAS",
    "QURE.NAS":"QURE.NAS",
    "RDFN.NAS":"RDFN.NAS",
    "RDWR.NAS":"RDWR.NAS",
    "REG.NAS":"REG.NAS",
    "REGI.NAS":"REGI.NAS",
    "REGN.NAS":"REGN.NAS",
    "RESN.NAS":"RESN.NAS",
    "RETA.NAS":"RETA.NAS",
    "RGEN.NAS":"RGEN.NAS",
    "RIGL.NAS":"RIGL.NAS",
    "ROIC.NAS":"ROIC.NAS",
    "ROKU.NAS":"ROKU.NAS",
    "ROST.NAS":"ROST.NAS",
    "RPD.NAS":"RPD.NAS",
    "RPRX.NAS":"RPRX.NAS",
    "RRGB.NAS":"RRGB.NAS",
    "RUBY.NAS":"RUBY.NAS",
    "RUN.NAS":"RUN.NAS",
    "RUTH.NAS":"RUTH.NAS",
    "RVMD.NAS":"RVMD.NAS",
    "RVNC.NAS":"RVNC.NAS",
    "RYAAY.NAS":"RYAAY.NAS",
    "SABR.NAS":"SABR.NAS",
    "SAFM.NAS":"SAFM.NAS",
    "SAGE.NAS":"SAGE.NAS",
    "SANM.NAS":"SANM.NAS",
    "SBAC.NAS":"SBAC.NAS",
    "SBGI.NAS":"SBGI.NAS",
    "SBNY.NAS":"SBNY.NAS",
    "SBRA.NAS":"SBRA.NAS",
    "SBUX.NAS":"SBUX.NAS",
    "SDC.NAS":"SDC.NAS",
    "SDGR.NAS":"SDGR.NAS",
    "SEDG.NAS":"SEDG.NAS",
    "SEIC.NAS":"SEIC.NAS",
    "SELB.NAS":"SELB.NAS",
    "SFIX.NAS":"SFIX.NAS",
    "SFM.NAS":"SFM.NAS",
    "SFT.NAS":"SFT.NAS",
    "SGEN.NAS":"SGEN.NAS",
    "SGMO.NAS":"SGMO.NAS",
    "SHV.NAS":"SHV.NAS",
    "SHY.NAS":"SHY.NAS",
    "SIRI.NAS":"SIRI.NAS",
    "SIVB.NAS":"SIVB.NAS",
    "SKYW.NAS":"SKYW.NAS",
    "SKYY.NAS":"SKYY.NAS",
    "SLAB.NAS":"SLAB.NAS",
    "SLGN.NAS":"SLGN.NAS",
    "SLM.NAS":"SLM.NAS",
    "SMH.NAS":"SMH.NAS",
    "SMTC.NAS":"SMTC.NAS",
    "SNDL.NAS":"SNDL.NAS",
    "SNDX.NAS":"SNDX.NAS",
    "SNEX.NAS":"SNEX.NAS",
    "SNPS.NAS":"SNPS.NAS",
    "SNSR.NAS":"SNSR.NAS",
    "SOLO.NAS":"SOLO.NAS",
    "SONO.NAS":"SONO.NAS",
    "SOXX.NAS":"SOXX.NAS",
    "SPLK.NAS":"SPLK.NAS",
    "SPPI.NAS":"SPPI.NAS",
    "SPTN.NAS":"SPTN.NAS",
    "SPWH.NAS":"SPWH.NAS",
    "SPWR.NAS":"SPWR.NAS",
    "SRCL.NAS":"SRCL.NAS",
    "SRNE.NAS":"SRNE.NAS",
    "SRPT.NAS":"SRPT.NAS",
    "SSNC.NAS":"SSNC.NAS",
    "SSRM.NAS":"SSRM.NAS",
    "SSSS.NAS":"SSSS.NAS",
    "SSTI.NAS":"SSTI.NAS",
    "STAY.NAS":"STAY.NAS",
    "STLD.NAS":"STLD.NAS",
    "STMP.NAS":"STMP.NAS",
    "STNE.NAS":"STNE.NAS",
    "STOK.NAS":"STOK.NAS",
    "STX.NAS":"STX.NAS",
    "SURF.NAS":"SURF.NAS",
    "SVC.NAS":"SVC.NAS",
    "SVMK.NAS":"SVMK.NAS",
    "SWAV.NAS":"SWAV.NAS",
    "SWBI.NAS":"SWBI.NAS",
    "SWKS.NAS":"SWKS.NAS",
    "SY.NAS":"SY.NAS",
    "SYNA.NAS":"SYNA.NAS",
    "SYNH.NAS":"SYNH.NAS",
    "TACO.NAS":"TACO.NAS",
    "TCOM.NAS":"TCOM.NAS",
    "TEAM.NAS":"TEAM.NAS",
    "TECH.NAS":"TECH.NAS",
    "TELL.NAS":"TELL.NAS",
    "TER.NAS":"TER.NAS",
    "TIGO.NAS":"TIGO.NAS",
    "TLRY.NAS":"TLRY.NAS",
    "TLT.NAS":"TLT.NAS",
    "TMUS.NAS":"TMUS.NAS",
    "TNDM.NAS":"TNDM.NAS",
    "TNXP.NAS":"TNXP.NAS",
    "TPIC.NAS":"TPIC.NAS",
    "TREE.NAS":"TREE.NAS",
    "TRIP.NAS":"TRIP.NAS",
    "TRMB.NAS":"TRMB.NAS",
    "TROW.NAS":"TROW.NAS",
    "TRVG.NAS":"TRVG.NAS",
    "TRVN.NAS":"TRVN.NAS",
    "TSCO.NAS":"TSCO.NAS",
    "TSEM.NAS":"TSEM.NAS",
    "TSLA.NAS":"TSLA.NAS",
    "TTCF.NAS":"TTCF.NAS",
    "TTD.NAS":"TTD.NAS",
    "TTOO.NAS":"TTOO.NAS",
    "TTWO.NAS":"TTWO.NAS",
    "TVTY.NAS":"TVTY.NAS",
    "TXG.NAS":"TXG.NAS",
    "TXMD.NAS":"TXMD.NAS",
    "TXN.NAS":"TXN.NAS",
    "TXRH.NAS":"TXRH.NAS",
    "UAL.NAS":"UAL.NAS",
    "UEIC.NAS":"UEIC.NAS",
    "ULTA.NAS":"ULTA.NAS",
    "UNIT.NAS":"UNIT.NAS",
    "UPWK.NAS":"UPWK.NAS",
    "URBN.NAS":"URBN.NAS",
    "USCR.NAS":"USCR.NAS",
    "UTHR.NAS":"UTHR.NAS",
    "VBIV.NAS":"VBIV.NAS",
    "VC.NAS":"VC.NAS",
    "VCYT.NAS":"VCYT.NAS",
    "VEON.NAS":"VEON.NAS",
    "VG.NAS":"VG.NAS",
    "VIAC.NAS":"VIAC.NAS",
    "VIAV.NAS":"VIAV.NAS",
    "VIR.NAS":"VIR.NAS",
    "VKTX.NAS":"VKTX.NAS",
    "VONG.NAS":"VONG.NAS",
    "VRA.NAS":"VRA.NAS",
    "VRAY.NAS":"VRAY.NAS",
    "VREX.NAS":"VREX.NAS",
    "VRM.NAS":"VRM.NAS",
    "VRSK.NAS":"VRSK.NAS",
    "VRSN.NAS":"VRSN.NAS",
    "VRTX.NAS":"VRTX.NAS",
    "VSTM.NAS":"VSTM.NAS",
    "VTIP.NAS":"VTIP.NAS",
    "VTRS.NAS":"VTRS.NAS",
    "VUZI.NAS":"VUZI.NAS",
    "VXRT.NAS":"VXRT.NAS",
    "VYGR.NAS":"VYGR.NAS",
    "VYNE.NAS":"VYNE.NAS",
    "WATT.NAS":"WATT.NAS",
    "WB.NAS":"WB.NAS",
    "WBA.NAS":"WBA.NAS",
    "WDAY.NAS":"WDAY.NAS",
    "WDC.NAS":"WDC.NAS",
    "WEN.NAS":"WEN.NAS",
    "WETF.NAS":"WETF.NAS",
    "WIMI.NAS":"WIMI.NAS",
    "WISH.NAS":"WISH.NAS",
    "WIX.NAS":"WIX.NAS",
    "WKHS.NAS":"WKHS.NAS",
    "WLTW.NAS":"WLTW.NAS",
    "WMG.NAS":"WMG.NAS",
    "WTRH.NAS":"WTRH.NAS",
    "WW.NAS":"WW.NAS",
    "WYNN.NAS":"WYNN.NAS",
    "XBIT.NAS":"XBIT.NAS",
    "XEL.NAS":"XEL.NAS",
    "XLNX.NAS":"XLNX.NAS",
    "XNET.NAS":"XNET.NAS",
    "XP.NAS":"XP.NAS",
    "XRAY.NAS":"XRAY.NAS",
    "XSPA.NAS":"XSPA.NAS",
    "YNDX.NAS":"YNDX.NAS",
    "Z.NAS":"Z.NAS",
    "ZBRA.NAS":"ZBRA.NAS",
    "ZG.NAS":"ZG.NAS",
    "ZI.NAS":"ZI.NAS",
    "ZION.NAS":"ZION.NAS",
    "ZM.NAS":"ZM.NAS",
    "ZNGA.NAS":"ZNGA.NAS",
    "ZS.NAS":"ZS.NAS",
    "ZYNE.NAS":"ZYNE.NAS",
    "ZYXI.NAS":"ZYXI.NAS"
};

console.log('Website have:', Object.keys(wehave).length)

let orig_keys = Object.keys(orig);
let wehave_keys = Object.keys(wehave);
let in_orig_not_in_wehave = [];
let in_wehave_not_in_orig = [];

orig_keys.map(key => {
    if (!wehave[key]) {
        in_orig_not_in_wehave.push(key);
    }
});

wehave_keys.map(key => {
    if (!orig[key]) {
        in_wehave_not_in_orig.push(key);
    }
});

console.log('in_orig_not_in_wehave:', in_orig_not_in_wehave);
console.log('in_wehave_not_in_orig:', in_wehave_not_in_orig);
